'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebUserForms_frmAddZone

    '''<summary>
    '''frmNewTypeZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmNewTypeZone As Global.VTLive40.WebUserForms_frmNewTypeZone

    '''<summary>
    '''lblAddZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddZone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitleFormAddZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitleFormAddZone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbType As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lblCmbTypeDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCmbTypeDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblShiftFromTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShiftFromTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFromTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFromTime As Global.DevExpress.Web.ASPxTimeEdit

    '''<summary>
    '''cmbShiftFromTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbShiftFromTime As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lblShiftToTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShiftToTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtToTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToTime As Global.DevExpress.Web.ASPxTimeEdit

    '''<summary>
    '''cmbShiftToTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbShiftToTime As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''chkIsLocked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsLocked As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''lblIsLocked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIsLocked As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.DevExpress.Web.ASPxButton
End Class
