
DROP TABLE TMPCALENDAREMPLOYEE
GO

CREATE TABLE TMPCALENDAREMPLOYEE (
	[IDEmployee] [numeric](18, 0) not NULL,
	[EMPLEADO] [nvarchar] (50) null,
	[MES] [int] NOT NULL ,
	[NOMBRE] [nvarchar] (50) NULL ,
	[DIAS] [int] NULL ,
	[horasdia1] [numeric] (9, 6) NOT NULL ,
	[horasdia2] [numeric] (9, 6) NOT NULL ,
	[horasdia3] [numeric] (9, 6) NOT NULL ,
	[horasdia4] [numeric] (9, 6) NOT NULL ,
	[horasdia5] [numeric] (9, 6) NOT NULL ,
	[horasdia6] [numeric] (9, 6) NOT NULL ,
	[horasdia7] [numeric] (9, 6) NOT NULL ,
	[horasdia8] [numeric] (9, 6) NOT NULL ,
	[horasdia9] [numeric] (9, 6) NOT NULL ,
	[horasdia10] [numeric] (9, 6) NOT NULL ,
	[horasdia11] [numeric] (9, 6) NOT NULL ,
	[horasdia12] [numeric] (9, 6) NOT NULL ,
	[horasdia13] [numeric] (9, 6) NOT NULL ,
	[horasdia14] [numeric] (9, 6) NOT NULL ,
	[horasdia15] [numeric] (9, 6) NOT NULL ,
	[horasdia16] [numeric] (9, 6) NOT NULL ,
	[horasdia17] [numeric] (9, 6) NOT NULL ,
	[horasdia18] [numeric] (9, 6) NOT NULL ,
	[horasdia19] [numeric] (9, 6) NOT NULL ,
	[horasdia20] [numeric] (9, 6) NOT NULL ,
	[horasdia21] [numeric] (9, 6) NOT NULL ,
	[horasdia22] [numeric] (9, 6) NOT NULL ,
	[horasdia23] [numeric] (9, 6) NOT NULL ,
	[horasdia24] [numeric] (9, 6) NOT NULL ,
	[horasdia25] [numeric] (9, 6) NOT NULL ,
	[horasdia26] [numeric] (9, 6) NOT NULL ,
	[horasdia27] [numeric] (9, 6) NOT NULL ,
	[horasdia28] [numeric] (9, 6) NOT NULL ,
	[horasdia29] [numeric] (9, 6) NOT NULL ,
	[horasdia30] [numeric] (9, 6) NOT NULL ,
	[horasdia31] [numeric] (9, 6) NOT NULL ,
	[TOTALHORAS] [nvarchar] (50) NULL ,
	[TOTALDIAS] [int] NULL ,
	[TotalHorasAnuales] [numeric](18, 2)  NULL,
	[TotalDiasAnuales] [numeric](18, 0)  NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] WITH NOCHECK ADD 
	CONSTRAINT [PK_TMPCALENDAREMPLOYEE] PRIMARY KEY  NONCLUSTERED 
	(
		[IDEmployee],
		[MES]

	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia1]  DEFAULT ((0)) FOR [horasdia1]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia2]  DEFAULT ((0)) FOR [horasdia2]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia3]  DEFAULT ((0)) FOR [horasdia3]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia4]  DEFAULT ((0)) FOR [horasdia4]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia5]  DEFAULT ((0)) FOR [horasdia5]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia6]  DEFAULT ((0)) FOR [horasdia6]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia7]  DEFAULT ((0)) FOR [horasdia7]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia8]  DEFAULT ((0)) FOR [horasdia8]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia9]  DEFAULT ((0)) FOR [horasdia9]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia10]  DEFAULT ((0)) FOR [horasdia10]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia11]  DEFAULT ((0)) FOR [horasdia11]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia12]  DEFAULT ((0)) FOR [horasdia12]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia13]  DEFAULT ((0)) FOR [horasdia13]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia14]  DEFAULT ((0)) FOR [horasdia14]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia15]  DEFAULT ((0)) FOR [horasdia15]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia16]  DEFAULT ((0)) FOR [horasdia16]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia17]  DEFAULT ((0)) FOR [horasdia17]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia18]  DEFAULT ((0)) FOR [horasdia18]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia19]  DEFAULT ((0)) FOR [horasdia19]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia20]  DEFAULT ((0)) FOR [horasdia20]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia21]  DEFAULT ((0)) FOR [horasdia21]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia22]  DEFAULT ((0)) FOR [horasdia22]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia23]  DEFAULT ((0)) FOR [horasdia23]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia24]  DEFAULT ((0)) FOR [horasdia24]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia25]  DEFAULT ((0)) FOR [horasdia25]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia26]  DEFAULT ((0)) FOR [horasdia26]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia27]  DEFAULT ((0)) FOR [horasdia27]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia28]  DEFAULT ((0)) FOR [horasdia28]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia29]  DEFAULT ((0)) FOR [horasdia29]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia30]  DEFAULT ((0)) FOR [horasdia30]
GO
ALTER TABLE [dbo].[TMPCALENDAREMPLOYEE] ADD  CONSTRAINT [DF_TMPCALENDAREMPLOYEE_horasdia31]  DEFAULT ((0)) FOR [horasdia31]
GO


DROP TABLE [TMPANNUALINDIVIDUALCALENDAR]
GO

CREATE TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR](
	[IDEmployee] [numeric](18, 0) NOT NULL,
	[EMPLEADO] [nvarchar](50) NULL,
	[MES] [int] NOT NULL,
	[AÑO] [int] NOT NULL,
	[NOMBRE] [nvarchar](50) NULL,
	[DIAS] [int] NULL,
	[horasdia1] [numeric] (9, 6) NOT NULL ,
	[horasdia2] [numeric] (9, 6) NOT NULL ,
	[horasdia3] [numeric] (9, 6) NOT NULL ,
	[horasdia4] [numeric] (9, 6) NOT NULL ,
	[horasdia5] [numeric] (9, 6) NOT NULL ,
	[horasdia6] [numeric] (9, 6) NOT NULL ,
	[horasdia7] [numeric] (9, 6) NOT NULL ,
	[horasdia8] [numeric] (9, 6) NOT NULL ,
	[horasdia9] [numeric] (9, 6) NOT NULL ,
	[horasdia10] [numeric] (9, 6) NOT NULL ,
	[horasdia11] [numeric] (9, 6) NOT NULL ,
	[horasdia12] [numeric] (9, 6) NOT NULL ,
	[horasdia13] [numeric] (9, 6) NOT NULL ,
	[horasdia14] [numeric] (9, 6) NOT NULL ,
	[horasdia15] [numeric] (9, 6) NOT NULL ,
	[horasdia16] [numeric] (9, 6) NOT NULL ,
	[horasdia17] [numeric] (9, 6) NOT NULL ,
	[horasdia18] [numeric] (9, 6) NOT NULL ,
	[horasdia19] [numeric] (9, 6) NOT NULL ,
	[horasdia20] [numeric] (9, 6) NOT NULL ,
	[horasdia21] [numeric] (9, 6) NOT NULL ,
	[horasdia22] [numeric] (9, 6) NOT NULL ,
	[horasdia23] [numeric] (9, 6) NOT NULL ,
	[horasdia24] [numeric] (9, 6) NOT NULL ,
	[horasdia25] [numeric] (9, 6) NOT NULL ,
	[horasdia26] [numeric] (9, 6) NOT NULL ,
	[horasdia27] [numeric] (9, 6) NOT NULL ,
	[horasdia28] [numeric] (9, 6) NOT NULL ,
	[horasdia29] [numeric] (9, 6) NOT NULL ,
	[horasdia30] [numeric] (9, 6) NOT NULL ,
	[horasdia31] [numeric] (9, 6) NOT NULL ,
	[TOTALHORAS] [numeric] (9, 6) NOT NULL ,
	[TOTALDIAS] [int] NULL,
	[TotalHorasAnuales] [numeric](18, 2) NULL,
	[TotalDiasAnuales] [numeric](18, 0) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] WITH NOCHECK ADD 
	CONSTRAINT [PK_TMPANNUALINDIVIDUALCALENDAR] PRIMARY KEY  NONCLUSTERED 
	(
	[IDEmployee] ASC,
	[MES] ASC,
	[AÑO] ASC
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia1]  DEFAULT ((0)) FOR [horasdia1]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia2]  DEFAULT ((0)) FOR [horasdia2]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia3]  DEFAULT ((0)) FOR [horasdia3]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia4]  DEFAULT ((0)) FOR [horasdia4]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia5]  DEFAULT ((0)) FOR [horasdia5]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia6]  DEFAULT ((0)) FOR [horasdia6]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia7]  DEFAULT ((0)) FOR [horasdia7]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia8]  DEFAULT ((0)) FOR [horasdia8]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia9]  DEFAULT ((0)) FOR [horasdia9]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia10]  DEFAULT ((0)) FOR [horasdia10]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia11]  DEFAULT ((0)) FOR [horasdia11]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia12]  DEFAULT ((0)) FOR [horasdia12]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia13]  DEFAULT ((0)) FOR [horasdia13]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia14]  DEFAULT ((0)) FOR [horasdia14]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia15]  DEFAULT ((0)) FOR [horasdia15]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia16]  DEFAULT ((0)) FOR [horasdia16]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia17]  DEFAULT ((0)) FOR [horasdia17]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia18]  DEFAULT ((0)) FOR [horasdia18]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia19]  DEFAULT ((0)) FOR [horasdia19]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia20]  DEFAULT ((0)) FOR [horasdia20]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia21]  DEFAULT ((0)) FOR [horasdia21]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia22]  DEFAULT ((0)) FOR [horasdia22]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia23]  DEFAULT ((0)) FOR [horasdia23]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia24]  DEFAULT ((0)) FOR [horasdia24]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia25]  DEFAULT ((0)) FOR [horasdia25]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia26]  DEFAULT ((0)) FOR [horasdia26]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia27]  DEFAULT ((0)) FOR [horasdia27]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia28]  DEFAULT ((0)) FOR [horasdia28]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia29]  DEFAULT ((0)) FOR [horasdia29]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia30]  DEFAULT ((0)) FOR [horasdia30]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_horasdia31]  DEFAULT ((0)) FOR [horasdia31]
GO
ALTER TABLE [dbo].[TMPANNUALINDIVIDUALCALENDAR] ADD  CONSTRAINT [DF_TMPANNUALINDIVIDUALCALENDAR_TOTALHORAS]  DEFAULT ((0)) FOR [TOTALHORAS]
GO



-- Actualizamos versión de BBDD
UPDATE sysroParameters SET Data='296' WHERE ID='DBVersion'
GO

