'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DocumentEmployees

    '''<summary>
    '''lblDeliveredDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeliveredDocuments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnExportToXls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportToXls As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnAddDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDoc As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnDownloadAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDownloadAll As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''hdnScopeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnScopeInfo As Global.DevExpress.Web.ASPxHiddenField

    '''<summary>
    '''hdnEmployeeDocumentsConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEmployeeDocumentsConfig As Global.DevExpress.Web.ASPxHiddenField

    '''<summary>
    '''GridDeliveredDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDeliveredDocs As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''GridExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridExporter As Global.DevExpress.Web.ASPxGridViewExporter

    '''<summary>
    '''EditDocumentPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditDocumentPopup As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''NewDocumentPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewDocumentPopup As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''CaptchaObjectPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaptchaObjectPopup As Global.DevExpress.Web.ASPxPopupControl
End Class
