# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: environment
    type: string
    default: ''
  - name: artifactoryService
    type: string
    default: ""
  - name: artifactoryBuildName
    type: string
    default: ""
  - name: artifactoryTargetRepo
    type: string
    default: ''
  - name: artifacts
    type: object
    default: ''

stages:
  - stage: PromoteArtifactory
    displayName: "Promote Artifactory"
    condition: succeeded()
    dependsOn: ['Build','PublishToArtifactory','Publish']
    jobs:
    - deployment: promote_artifactory
      variables:
        artifactoryBuildNumber: $[ stageDependencies.Build.Compile.outputs['buildVersion.BuildNumber'] ]
      pool:
        vmImage: windows-latest
      environment: cegid_vti_app_${{ parameters.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            - ${{ each vtartifact in parameters.artifacts }}:
              - ${{ if eq(vtartifact.enabled, true) }} :
                  ###############################################
                  # Promote artifact to Jfrog production repos
                  ###############################################
                - task: JFrogBuildPromotion@1
                  displayName: 'Promote - "${{ vtartifact.artifactoryFolderName }}"'
                  inputs:
                    artifactoryConnection: '${{ parameters.artifactoryService }}'
                    buildName: '${{ parameters.artifactoryBuildName }}-${{ vtartifact.artifactoryFolderName }}'
                    buildNumber: $(artifactoryBuildNumber)
                    targetRepo: '${{ parameters.artifactoryTargetRepo }}'
                    status: 'Released'
                    includeDependencies: false
                    copy: true
                    dryRun: false