'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://isengard/VTLiveBusiness/Audit/Audit.asmx")>  _
        Public ReadOnly Property BaseWeb_AuditService_wsAuditService() As String
            Get
                Return CType(Me("BaseWeb_AuditService_wsAuditService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://isengard/VTLiveBusiness/LabAgree/LabAgreeService.asmx")>  _
        Public ReadOnly Property BaseWeb_LabAgreeService_wsLabAgree() As String
            Get
                Return CType(Me("BaseWeb_LabAgreeService_wsLabAgree"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/VTLiveBusinessDev/Programmed%20Causes/wsProgrammedCauses.asmx")>  _
        Public ReadOnly Property BaseWeb_ProgrammedCausesService_wsProgrammedCauses() As String
            Get
                Return CType(Me("BaseWeb_ProgrammedCausesService_wsProgrammedCauses"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://isengard/VTLiveBusiness/Cameras/CamerasService.asmx")>  _
        Public ReadOnly Property BaseWeb_CameraService_wsCamerasService() As String
            Get
                Return CType(Me("BaseWeb_CameraService_wsCamerasService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/VTLiveBusinessDev/SecurityOptions/SecurityOptionsService.asmx")>  _
        Public ReadOnly Property BaseWeb_SecurityOptionsService_wsSecurityOptions() As String
            Get
                Return CType(Me("BaseWeb_SecurityOptionsService_wsSecurityOptions"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/VTDiagnosticsBusinessDev/Diagnostics/Diagnostics.asmx")>  _
        Public ReadOnly Property BaseWeb_Diagnostics_wsDiagnosticsService() As String
            Get
                Return CType(Me("BaseWeb_Diagnostics_wsDiagnosticsService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/VTLiveBusinessDev/EventsScheduler/WSEventScheduler.asmx")>  _
        Public ReadOnly Property BaseWeb_EventSchedulerService_wsEventScheduler() As String
            Get
                Return CType(Me("BaseWeb_EventSchedulerService_wsEventScheduler"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/VTLiveBusinessDev/EventsScheduler/WSEventScheduler.asmx")>  _
        Public ReadOnly Property BaseWeb_EventSchedulerService_wsLiveTasks() As String
            Get
                Return CType(Me("BaseWeb_EventSchedulerService_wsLiveTasks"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://isengard/VTLiveBusiness/Security/SecurityChartService.asmx")>  _
        Public ReadOnly Property BaseWeb_SecurityChartService_wsSecurityChart() As String
            Get
                Return CType(Me("BaseWeb_SecurityChartService_wsSecurityChart"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/Employees/EmployeesSvc.svc")>  _
        Public ReadOnly Property BaseWeb_EmployeeSVC_employeesvc() As String
            Get
                Return CType(Me("BaseWeb_EmployeeSVC_employeesvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/Documents/DocumentsSvc.svc")>  _
        Public ReadOnly Property BaseWeb_DocumentSVC_documentsvc() As String
            Get
                Return CType(Me("BaseWeb_DocumentSVC_documentsvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/ProgrammedHolidays/ProgrammedHolidaysSvc.svc")>  _
        Public ReadOnly Property BaseWeb_ProgrammedHolidaySVC_documentsvc() As String
            Get
                Return CType(Me("BaseWeb_ProgrammedHolidaySVC_documentsvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/ProgrammedHolidays/ProgrammedHolidaysSvc.svc")>  _
        Public ReadOnly Property BaseWeb_AISchedulingSVC_aischedulingsvc() As String
            Get
                Return CType(Me("BaseWeb_AISchedulingSVC_aischedulingsvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/ScheduleRules/ScheduleRulesSvc.svc")>  _
        Public ReadOnly Property BaseWeb_ScheduleRulesSVC_schedulerulessvc() As String
            Get
                Return CType(Me("BaseWeb_ScheduleRulesSVC_schedulerulessvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/Calendar/CalendarSvc.svc")>  _
        Public ReadOnly Property BaseWeb_CalendarSVC_schedulerulessvc() As String
            Get
                Return CType(Me("BaseWeb_CalendarSVC_schedulerulessvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/Common/CommonSvc.svc")>  _
        Public ReadOnly Property BaseWeb_CommonSVC_schedulerulessvc() As String
            Get
                Return CType(Me("BaseWeb_CommonSVC_schedulerulessvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/Security/SecuritySvc.svc")>  _
        Public ReadOnly Property BaseWeb_SecuritySVC_securitysvc() As String
            Get
                Return CType(Me("BaseWeb_SecuritySVC_securitysvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/ProgrammedHolidays/ProgrammedHolidaysSvc.svc")>  _
        Public ReadOnly Property BaseWeb_ProgrammedHolidaySVC_programmedholidaysvc() As String
            Get
                Return CType(Me("BaseWeb_ProgrammedHolidaySVC_programmedholidaysvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/Calendar/CalendarSvc.svc")>  _
        Public ReadOnly Property BaseWeb_CalendarSVC_calendarsvc() As String
            Get
                Return CType(Me("BaseWeb_CalendarSVC_calendarsvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/Common/CommonSvc.svc")>  _
        Public ReadOnly Property BaseWeb_CommonSVC_commonsvc() As String
            Get
                Return CType(Me("BaseWeb_CommonSVC_commonsvc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:8031/Datalink/DatalinkSvc.svc")>  _
        Public ReadOnly Property BaseWeb_DatalinkSVC_datalinksvc() As String
            Get
                Return CType(Me("BaseWeb_DatalinkSVC_datalinksvc"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Robotics.Web.Base.My.MySettings
            Get
                Return Global.Robotics.Web.Base.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
