'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebUserForms_frmCompositions

    '''<summary>
    '''divComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divComposition As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCompTit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompTit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''conceptCompositionData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents conceptCompositionData As Global.DevExpress.Web.ASPxHiddenField

    '''<summary>
    '''lblValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ckCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckCause As Global.DevExpress.Web.ASPxRadioButton

    '''<summary>
    '''cmbCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCause As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ckValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckValue As Global.DevExpress.Web.ASPxRadioButton

    '''<summary>
    '''cmbValueDailyCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbValueDailyCause As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbValueCustomCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbValueCustomCause As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ckDayContainsCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckDayContainsCause As Global.DevExpress.Web.ASPxRadioButton

    '''<summary>
    '''cmbDayContainsCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDayContainsCause As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ckShift control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckShift As Global.DevExpress.Web.ASPxRadioButton

    '''<summary>
    '''cmbShift control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbShift As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lblDaysType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDaysType As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cmbDaysType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDaysType As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ckIncidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckIncidence As Global.DevExpress.Web.ASPxRadioButton

    '''<summary>
    '''cmbDayCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDayCause As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lblDayCauseType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDayCauseType As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cmbDaysTypeCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDaysTypeCause As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lbltxtFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtFactor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ckFixedValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckFixedValue As Global.DevExpress.Web.ASPxRadioButton

    '''<summary>
    '''txtFactorComposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactorComposition As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ckFactorUserField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckFactorUserField As Global.DevExpress.Web.ASPxRadioButton

    '''<summary>
    '''cmbFactorUserField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFactorUserField As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lblCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCriteria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optChkCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optChkCondition As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblChkCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChkCondition As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblChkCondDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChkCondDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divListActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divListActions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCauses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCauses As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgAddListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddListValue As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''imgRemoveListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRemoveListValue As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblNewCauseTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewCauseTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtNewCauseOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtNewCauseOK As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''ibtNewCauseCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtNewCauseCancel As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblCauseTitle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCauseTitle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbCauseAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCauseAdd As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lblopPlus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblopPlus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblopMinus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblopMinus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divConditionsCauses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConditionsCauses As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCompares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompares As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbCompare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCompare As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lblTypeValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTypeValues As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbTypeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTypeValue As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''lblValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValues As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbCauseType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCauseType As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtValueType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValueType As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cmbCauseUField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCauseUField As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''hdnMustRefresh_PageBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMustRefresh_PageBase As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.DevExpress.Web.ASPxButton
End Class
