'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Mixer")>  _
Partial Public Class AbsencesDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("MixerConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property sysrovwAbsences() As System.Data.Linq.Table(Of sysrovwAbsences)
		Get
			Return Me.GetTable(Of sysrovwAbsences)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.sysrovwAbsencesEx")>  _
Partial Public Class sysrovwAbsences
	
	Private _ID As System.Nullable(Of Long)
	
	Private _IDRelatedObject As System.Nullable(Of Integer)
	
	Private _IDCause As System.Nullable(Of Short)
	
	Private _IDEmployee As Integer
	
	Private _BeginDate As System.Nullable(Of Date)
	
	Private _FinishDate As System.Nullable(Of Date)
	
	Private _BeginTime As System.Nullable(Of Date)
	
	Private _EndTime As System.Nullable(Of Date)
	
	Private _Description As String
	
	Private _DocumentsDelivered As System.Nullable(Of Integer)
	
	Private _Status As String
	
	Private _AbsenceType As String
	
	Private _EmployeeName As String
	
	Private _CauseName As String
	
	Private _IDGroup As Integer
	
	Private _FullGroupName As String
	
	Private _Path As String
	
	Private _CurrentEmployee As System.Nullable(Of Integer)
	
	Private _BeginDateMobility As Date
	
	Private _EndDateMobility As Date
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", DbType:="BigInt")>  _
	Public Property ID() As System.Nullable(Of Long)
		Get
			Return Me._ID
		End Get
		Set
			If (Me._ID.Equals(value) = false) Then
				Me._ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDRelatedObject", DbType:="Int")>  _
	Public Property IDRelatedObject() As System.Nullable(Of Integer)
		Get
			Return Me._IDRelatedObject
		End Get
		Set
			If (Me._IDRelatedObject.Equals(value) = false) Then
				Me._IDRelatedObject = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDCause", DbType:="SmallInt")>  _
	Public Property IDCause() As System.Nullable(Of Short)
		Get
			Return Me._IDCause
		End Get
		Set
			If (Me._IDCause.Equals(value) = false) Then
				Me._IDCause = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDEmployee", DbType:="Int NOT NULL")>  _
	Public Property IDEmployee() As Integer
		Get
			Return Me._IDEmployee
		End Get
		Set
			If ((Me._IDEmployee = value)  _
						= false) Then
				Me._IDEmployee = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BeginDate", DbType:="DateTime")>  _
	Public Property BeginDate() As System.Nullable(Of Date)
		Get
			Return Me._BeginDate
		End Get
		Set
			If (Me._BeginDate.Equals(value) = false) Then
				Me._BeginDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FinishDate", DbType:="DateTime")>  _
	Public Property FinishDate() As System.Nullable(Of Date)
		Get
			Return Me._FinishDate
		End Get
		Set
			If (Me._FinishDate.Equals(value) = false) Then
				Me._FinishDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BeginTime", DbType:="DateTime")>  _
	Public Property BeginTime() As System.Nullable(Of Date)
		Get
			Return Me._BeginTime
		End Get
		Set
			If (Me._BeginTime.Equals(value) = false) Then
				Me._BeginTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndTime", DbType:="DateTime")>  _
	Public Property EndTime() As System.Nullable(Of Date)
		Get
			Return Me._EndTime
		End Get
		Set
			If (Me._EndTime.Equals(value) = false) Then
				Me._EndTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Description", DbType:="NVarChar(MAX)")>  _
	Public Property Description() As String
		Get
			Return Me._Description
		End Get
		Set
			If (String.Equals(Me._Description, value) = false) Then
				Me._Description = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DocumentsDelivered", DbType:="Int")>  _
	Public Property DocumentsDelivered() As System.Nullable(Of Integer)
		Get
			Return Me._DocumentsDelivered
		End Get
		Set
			If (Me._DocumentsDelivered.Equals(value) = false) Then
				Me._DocumentsDelivered = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="VarChar(2)")>  _
	Public Property Status() As String
		Get
			Return Me._Status
		End Get
		Set
			If (String.Equals(Me._Status, value) = false) Then
				Me._Status = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AbsenceType", DbType:="VarChar(17)")>  _
	Public Property AbsenceType() As String
		Get
			Return Me._AbsenceType
		End Get
		Set
			If (String.Equals(Me._AbsenceType, value) = false) Then
				Me._AbsenceType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeName", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property EmployeeName() As String
		Get
			Return Me._EmployeeName
		End Get
		Set
			If (String.Equals(Me._EmployeeName, value) = false) Then
				Me._EmployeeName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CauseName", DbType:="NVarChar(64) NOT NULL", CanBeNull:=false)>  _
	Public Property CauseName() As String
		Get
			Return Me._CauseName
		End Get
		Set
			If (String.Equals(Me._CauseName, value) = false) Then
				Me._CauseName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDGroup", DbType:="Int NOT NULL")>  _
	Public Property IDGroup() As Integer
		Get
			Return Me._IDGroup
		End Get
		Set
			If ((Me._IDGroup = value)  _
						= false) Then
				Me._IDGroup = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FullGroupName", DbType:="VarChar(300)")>  _
	Public Property FullGroupName() As String
		Get
			Return Me._FullGroupName
		End Get
		Set
			If (String.Equals(Me._FullGroupName, value) = false) Then
				Me._FullGroupName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Path", DbType:="NVarChar(100)")>  _
	Public Property Path() As String
		Get
			Return Me._Path
		End Get
		Set
			If (String.Equals(Me._Path, value) = false) Then
				Me._Path = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CurrentEmployee", DbType:="Int")>  _
	Public Property CurrentEmployee() As System.Nullable(Of Integer)
		Get
			Return Me._CurrentEmployee
		End Get
		Set
			If (Me._CurrentEmployee.Equals(value) = false) Then
				Me._CurrentEmployee = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BeginDateMobility", DbType:="SmallDateTime NOT NULL")>  _
	Public Property BeginDateMobility() As Date
		Get
			Return Me._BeginDateMobility
		End Get
		Set
			If ((Me._BeginDateMobility = value)  _
						= false) Then
				Me._BeginDateMobility = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndDateMobility", DbType:="SmallDateTime NOT NULL")>  _
	Public Property EndDateMobility() As Date
		Get
			Return Me._EndDateMobility
		End Get
		Set
			If ((Me._EndDateMobility = value)  _
						= false) Then
				Me._EndDateMobility = value
			End If
		End Set
	End Property
End Class
