'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Merck")>  _
Partial Public Class AccessDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("MerckConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property sysroAccessPlates() As System.Data.Linq.Table(Of sysroAccessPlates)
		Get
			Return Me.GetTable(Of sysroAccessPlates)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.sysroAccessPlates")>  _
Partial Public Class sysroAccessPlates
	
	Private _ID As Decimal
	
	Private _IDEmployee As System.Nullable(Of Integer)
	
	Private _DatePunche As Date
	
	Private _TimePunche As String
	
	Private _TypeDetails As String
	
	Private _NameEmployee As String
	
	Private _NameZone As String
	
	Private _Path As String
	
	Private _CurrentEmployee As System.Nullable(Of Integer)
	
	Private _BeginDate As Date
	
	Private _IDGroup As Integer
	
	Private _EndDate As Date
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.Always, DbType:="Decimal(16,0) NOT NULL IDENTITY", IsDbGenerated:=true)>  _
	Public Property ID() As Decimal
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me._ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDEmployee", DbType:="Int")>  _
	Public Property IDEmployee() As System.Nullable(Of Integer)
		Get
			Return Me._IDEmployee
		End Get
		Set
			If (Me._IDEmployee.Equals(value) = false) Then
				Me._IDEmployee = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DatePunche", DbType:="DateTime NOT NULL")>  _
	Public Property DatePunche() As Date
		Get
			Return Me._DatePunche
		End Get
		Set
			If ((Me._DatePunche = value)  _
						= false) Then
				Me._DatePunche = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TimePunche", DbType:="VarChar(8)")>  _
	Public Property TimePunche() As String
		Get
			Return Me._TimePunche
		End Get
		Set
			If (String.Equals(Me._TimePunche, value) = false) Then
				Me._TimePunche = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TypeDetails", DbType:="NVarChar(MAX)")>  _
	Public Property TypeDetails() As String
		Get
			Return Me._TypeDetails
		End Get
		Set
			If (String.Equals(Me._TypeDetails, value) = false) Then
				Me._TypeDetails = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NameEmployee", DbType:="NVarChar(500)")>  _
	Public Property NameEmployee() As String
		Get
			Return Me._NameEmployee
		End Get
		Set
			If (String.Equals(Me._NameEmployee, value) = false) Then
				Me._NameEmployee = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NameZone", DbType:="NVarChar(50)")>  _
	Public Property NameZone() As String
		Get
			Return Me._NameZone
		End Get
		Set
			If (String.Equals(Me._NameZone, value) = false) Then
				Me._NameZone = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Path", DbType:="NVarChar(100)")>  _
	Public Property Path() As String
		Get
			Return Me._Path
		End Get
		Set
			If (String.Equals(Me._Path, value) = false) Then
				Me._Path = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CurrentEmployee", DbType:="Int")>  _
	Public Property CurrentEmployee() As System.Nullable(Of Integer)
		Get
			Return Me._CurrentEmployee
		End Get
		Set
			If (Me._CurrentEmployee.Equals(value) = false) Then
				Me._CurrentEmployee = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BeginDate", DbType:="SmallDateTime NOT NULL")>  _
	Public Property BeginDate() As Date
		Get
			Return Me._BeginDate
		End Get
		Set
			If ((Me._BeginDate = value)  _
						= false) Then
				Me._BeginDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDGroup", DbType:="Int NOT NULL")>  _
	Public Property IDGroup() As Integer
		Get
			Return Me._IDGroup
		End Get
		Set
			If ((Me._IDGroup = value)  _
						= false) Then
				Me._IDGroup = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndDate", DbType:="SmallDateTime NOT NULL")>  _
	Public Property EndDate() As Date
		Get
			Return Me._EndDate
		End Get
		Set
			If ((Me._EndDate = value)  _
						= false) Then
				Me._EndDate = value
			End If
		End Set
	End Property
End Class
