'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmProductiveUnitSelector

    '''<summary>
    '''lblPUnitSelectorTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPUnitSelectorTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPUnitInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPUnitInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPUnit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbAvailablePUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAvailablePUnits As Global.DevExpress.Web.ASPxComboBox
End Class
