'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Forms_NewTerminalWizard
    
    '''<summary>
    '''frmNewTerminalWizard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmNewTerminalWizard As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''upNewTerminalWizard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upNewTerminalWizard As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divStep0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep0 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''imgWelcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgWelcome As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblWelcome1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcome1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWelcome2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcome2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblWelcome3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcome3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnStepTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStepTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbStep1 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblStep1Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep1Title As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblStep1Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep1Error As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTerminalInfoTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTerminalInfoTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTerminalSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTerminalSN As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TerminalSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TerminalSN As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTerminalModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTerminalModel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TerminalModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TerminalModel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTerminalIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTerminalIP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TerminalIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TerminalIP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTerminalInfoRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTerminalInfoRegister As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTerminalRegisterDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTerminalRegisterDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegister As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DivStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivStep2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblStep2Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep2Title As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblStep2Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep2Error As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTerminalTypeDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTerminalTypeDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''optNewTerminal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNewTerminal As Global.VTLive40.roOptionPanelContainer
    
    '''<summary>
    '''optReplaceTerminal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optReplaceTerminal As Global.VTLive40.roOptionPanelContainer
    
    '''<summary>
    '''optTerminalGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optTerminalGroup As Global.VTLive40.roOptionPanelGroup
    
    '''<summary>
    '''divStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbStep3 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblStep3Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep3Title As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblReplaceTermDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReplaceTermDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''grdTerminales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTerminales As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TermToReplaceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TermToReplaceID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblStep3Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep3Error As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divStep4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbStep4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbStep4 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblStep4Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep4Title As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInsertName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInsertName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNameTerminal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameTerminal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblStep4Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep4Error As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btPrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btPrev As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btNext As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btEnd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdnCanClose_PageBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCanClose_PageBase As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnMustRefresh_PageBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMustRefresh_PageBase As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''MessageFrame1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageFrame1 As Global.VTLive40.Base_WebUserControls_MessageModalV2
End Class
