'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Base_Popups_roMessageBoxV2

    '''<summary>
    '''ObjectPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ObjectPopup As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''imgTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgTop As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divAviso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAviso As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgAviso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAviso As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblAviso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAviso As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnOption1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOption1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblOption1Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOption1Text As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblOption1Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOption1Description As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnOption2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOption2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblOption2Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOption2Text As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblOption2Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOption2Description As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnOption3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOption3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblOption3Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOption3Text As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblOption3Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOption3Description As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnOption4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOption4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblOption4Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOption4Text As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblOption4Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOption4Description As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
