Imports System.Runtime.Serialization

Namespace Audit

    <DataContract>
    Public Enum Action
        <EnumMember> aNone
        <EnumMember> aConnect
        <EnumMember> aDisconnect
        <EnumMember> aSelect
        <EnumMember> aMultiSelect
        <EnumMember> aUpdate
        <EnumMember> aInsert
        <EnumMember> aDelete
        <EnumMember> aExecuted
        <EnumMember> aConnectFail
        <EnumMember> aBlock
        <EnumMember> aUnblock
    End Enum

    <DataContract>
    Public Enum ObjectType
        <EnumMember> tNone
        <EnumMember> tConnection
        <EnumMember> tGroup
        <EnumMember> tEmployee
        <EnumMember> tEmployeeContract
        <EnumMember> tEmployeeGroup
        <EnumMember> tProgrammedAbsence
        <EnumMember> tProgrammedCause
        <EnumMember> tShift
        <EnumMember> tShiftGroup
        <EnumMember> tAccrualsRule
        <EnumMember> tAttendanceOptions
        <EnumMember> tGeneralOptions
        <EnumMember> tMove
        <EnumMember> tDailyCause
        <EnumMember> tUserField
        <EnumMember> tShiftLayer
        <EnumMember> tDataLinkImportEmployees
        <EnumMember> tUserTask
        <EnumMember> tAccessZone
        <EnumMember> tAccessGroup
        <EnumMember> tAccessPeriod
        <EnumMember> tRequest
        <EnumMember> tNotification
        <EnumMember> tCamera
        <EnumMember> tReportScheduler
        <EnumMember> tAccessGroupPermission
        <EnumMember> tAccessMove
        <EnumMember> tAccessPeriodDaily
        <EnumMember> tAccessPeriodHolidays
        <EnumMember> tActivity
        <EnumMember> tActivityCompany
        <EnumMember> tCapture
        <EnumMember> tCause
        <EnumMember> tConcept
        <EnumMember> tConceptComposition
        <EnumMember> tConceptGroup
        <EnumMember> tDataLink
        <EnumMember> tEmployeeUserField
        <EnumMember> tGroupUserField
        <EnumMember> tLabAgree
        <EnumMember> tLabAgreeRule
        <EnumMember> tLabAgreeAccrualRule
        <EnumMember> tStartupValues
        <EnumMember> tEntry
        <EnumMember> tReport
        <EnumMember> tReportProfile
        <EnumMember> tRequestApproval
        <EnumMember> tSchedulerRemarks
        <EnumMember> tDailySchedule
        <EnumMember> tRemark
        <EnumMember> tShiftRule
        <EnumMember> tShiftTimeZone
        <EnumMember> tTimeZone
        <EnumMember> tTerminal
        <EnumMember> tTerminalReader
        <EnumMember> tTerminalSiren
        <EnumMember> tZoneInactivity
        <EnumMember> tZonePlane
        <EnumMember> tParameters
        <EnumMember> tSchedulerDaily
        <EnumMember> tSchedulerPlanification
        <EnumMember> tSchedulerTemplate
        <EnumMember> tCopyPlanification
        <EnumMember> tDataLinkImportScheduler
        <EnumMember> tAssignment
        <EnumMember> tEmployeeAssignment
        <EnumMember> tDailyCoverage
        <EnumMember> tShiftAssignment
        <EnumMember> tDiningRoom
        <EnumMember> tTask
        <EnumMember> tDataLinkImportDailyCoverage
        <EnumMember> tIndicator
        <EnumMember> tTaskTemplate
        <EnumMember> tProjectTemplate
        <EnumMember> tTaskField
        <EnumMember> tTaskFieldDefinition
        <EnumMember> tEmergencyReport
        <EnumMember> tDataLinkImportTask
        <EnumMember> tDocumentAbsence
        <EnumMember> tAbsenceTracking
        <EnumMember> tSecurityOptions
        <EnumMember> tPassport
        <EnumMember> tSaaSService
        <EnumMember> tAccessData
        <EnumMember> tAttendanceData
        <EnumMember> tProductivData
        <EnumMember> tPassportPassword
        <EnumMember> tDailyPunchesDetail
        <EnumMember> tSchedulerHolidays
        <EnumMember> tSchedulerWeekly
        <EnumMember> tCopyPlanificationAdvanced
        <EnumMember> tCopyPlanificationToEmployees
        <EnumMember> tPassportPermissionsOverFeatures
        <EnumMember> tPassportPermissionsOverEmployees
        <EnumMember> tPassportPermissionsOverGroups
        <EnumMember> tSupervisedEmployeeData
        <EnumMember> tAdvancedParameter
        <EnumMember> tDataLinkImportProgrammedAbsences
        <EnumMember> tCaptcha
        <EnumMember> tLiveTask
        <EnumMember> tAccessAuthorization
        <EnumMember> tAssignCause
        <EnumMember> tUploadFile
        <EnumMember> tDownloadFile
        <EnumMember> tTerminalConfigFile
        <EnumMember> tTerminalSyncFile
        <EnumMember> tJustifiedIncidences
        <EnumMember> tEmployeeCenters
        <EnumMember> tMessageEmployees
        <EnumMember> tEventScheduler
        <EnumMember> tAssignCenters
        <EnumMember> tVisit
        <EnumMember> tVisitor
        <EnumMember> tDataLinkResult
        <EnumMember> tCompleteTasks
        <EnumMember> tCauseLimitValue
        <EnumMember> tLabAgreeCauseLimitValue
        <EnumMember> tSecurityNode
        <EnumMember> tSecurityNodePassport
        <EnumMember> tSecurityNodeGroup
        <EnumMember> tSecurityNodePassportException
        <EnumMember> tGroupFeature
        <EnumMember> tGroupFeaturePermissionOverFeature
        <EnumMember> tCalendar
        <EnumMember> tCalendarRow
        <EnumMember> tCalendarRowSummaryData
        <EnumMember> tDocumentTemplate
        <EnumMember> tDocument
        <EnumMember> tProgrammedHoliday
        <EnumMember> tRequestRule
        <EnumMember> tProgrammedOvertime
        <EnumMember> tProductiveUnit
        <EnumMember> tProductiveUnitMode
        <EnumMember> tProductiveUnitModePosition
        <EnumMember> tBudget
        <EnumMember> tBudgetRow
        <EnumMember> tDailyBudgetPosition
        <EnumMember> tCopyBudgetPlanificationAdvanced
        <EnumMember> tDatalinkWS
        <EnumMember> tPunchImage
        <EnumMember> tPassportConsent
        <EnumMember> tMassMarkConsents
        <EnumMember> tMassMobilityEmployees
        <EnumMember> tAccessMode
        <EnumMember> tLockDate
        <EnumMember> tCommunique
        <EnumMember> tRequestType
        <EnumMember> tCategoryType
        <EnumMember> tEmployeeOnTerminal
        <EnumMember> tGenius
        <EnumMember> tGeniusScheduler
        <EnumMember> tSSOConfig
        <EnumMember> tSurvey
        <EnumMember> tSurveyResponse
        <EnumMember> tSurveyResults
        <EnumMember> tTelecommute
        <EnumMember> tDailyRecord
        <EnumMember> tDataLinkImportGroups
        <EnumMember> tChannel
        <EnumMember> tChannelConversation
        <EnumMember> tChannelConversationMessage
        <EnumMember> tBot
        <EnumMember> tLogBook
        <EnumMember> tBotRule
        <EnumMember> tChannelConversationComplexity
        <EnumMember> tPassportPin
        <EnumMember> tA3PayrollImport
        <EnumMember> tCollective
        <EnumMember> tCollectiveDefinition
        <EnumMember> tCollectiveEmployees
    End Enum

End Namespace