'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EmergencyReport

    '''<summary>
    '''hdnModeEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnModeEdit As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''msgHasChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgHasChanges As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''msgHasErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgHasErrors As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''imgConfigurationOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgConfigurationOptions As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rowTabButtons1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTabButtons1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TABBUTTON_EmergencyOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TABBUTTON_EmergencyOptions As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblEmergencyOptionsTabButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmergencyOptionsTabButton As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upBody As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Img1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblSaveChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveChanges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUndoChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndoChanges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbEmergencyOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEmergencyOptions As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Label55 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label55 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmergencyOptionsInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmergencyOptionsInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Tr33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tr33 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tcEmergencyOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tcEmergencyOptions As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpEmergencyOptions_FreezeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpEmergencyOptions_FreezeDate As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblParametersTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParametersTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmergencyReportInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmergencyReportInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''opCheckEmergencyActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opCheckEmergencyActive As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''opCheckEmergencyActiveTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opCheckEmergencyActiveTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblClave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClave As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmergencyReportKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmergencyReportKey As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblURL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''aURLDescript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aURLDescript As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''tpEmergencyOptions_Database control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpEmergencyOptions_Database As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblEmergencyTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmergencyTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Img2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img2 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblSaveChangesBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveChangesBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUndoChangesBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndoChangesBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btRefresh As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnChanged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnChanged As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnIsPostBack_PageBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIsPostBack_PageBase As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ConfigurationOptions_TabVisibleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfigurationOptions_TabVisibleName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''MessageFrame1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageFrame1 As Global.VTLive40.Base_WebUserControls_MessageModalV2
End Class
