'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserField

    '''<summary>
    '''frmUserField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmUserField As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''LblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updError As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updUserField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updUserField As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''tabCtl01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabCtl01 As Global.VTLive40.base_WebUserControls_roTabContainerClient

    '''<summary>
    '''lblGeneralTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGeneralTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''imgUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUsed As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''descriptionTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descriptionTR As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDescriptionField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescriptionField As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTypes As Global.Robotics.WebControls.roComboBox

    '''<summary>
    '''cmbTypes_Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTypes_Text As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cmbTypes_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTypes_Value As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblAccessLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccessLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbAccessLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAccessLevels As Global.Robotics.WebControls.roComboBox

    '''<summary>
    '''cmbAccessLevels_Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAccessLevels_Text As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cmbAccessLevels_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAccessLevels_Value As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''historyTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents historyTR As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHistory As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''lblHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHistory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''categoriesTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoriesTR As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCategories As Global.Robotics.WebControls.roComboBox

    '''<summary>
    '''cmbCategories_Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCategories_Text As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cmbCategories_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCategories_Value As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''divAddCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAddCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgAddCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddCategory As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblListValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListValues As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbListValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbListValues As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''divListActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divListActions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgAddListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddListValue As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''imgRemoveListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRemoveListValue As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblAccessValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccessValidation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbAccessValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAccessValidation As Global.Robotics.WebControls.roComboBox

    '''<summary>
    '''cmbAccessValidation_Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAccessValidation_Text As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cmbAccessValidation_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAccessValidation_Value As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''uniqueTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uniqueTR As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkUnique control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUnique As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''lblUnique control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnique As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequestsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequestsInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestsInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optRequestAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optRequestAll As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblRequestAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequestAllDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestAllDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optRequestNobody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optRequestNobody As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblRequestNobody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestNobody As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequestNobodyDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestNobodyDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optRequestCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optRequestCriteria As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblRequestCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestCriteria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequestCriteriaDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestCriteriaDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequestCriteriaConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestCriteriaConfiguration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdvancedTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdvancedTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ConvertDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConvertDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConvert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConvert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbConvertType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbConvertType As Global.Robotics.WebControls.roComboBox

    '''<summary>
    '''cbConvert_Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbConvert_Text As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cbConvert_Value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbConvert_Value As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''optRequestGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optRequestGroup As Global.VTLive40.base_WebUserControls_roOptPanelClientGroup

    '''<summary>
    '''updActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updActions As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btAccept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAccept As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnCanClose_PageBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCanClose_PageBase As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnMustRefresh_PageBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMustRefresh_PageBase As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btNewCategoryOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btNewCategoryOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''updNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updNewCategory As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''mpxNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpxNewCategory As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hiddenTargetControlForNewCategoryPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenTargetControlForNewCategoryPopup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ropfNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ropfNewCategory As Global.Robotics.WebControls.roPopupFrameV2

    '''<summary>
    '''lblNewCategoryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewCategoryTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtNewCategoryOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtNewCategoryOK As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtNewCategoryCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtNewCategoryCancel As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblCategoryTitle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoryTitle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewCategory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btNewListValueOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btNewListValueOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btDeleteListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btDeleteListValue As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''updNewListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updNewListValue As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''mpxNewListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpxNewListValue As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hiddenTargetControlForNewListValuePopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenTargetControlForNewListValuePopup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divNewListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewListValue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ropfNewListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ropfNewListValue As Global.Robotics.WebControls.roPopupFrameV2

    '''<summary>
    '''imgNewListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewListValue As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblNewListValueTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewListValueTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtNewListValueOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtNewListValueOK As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtNewListValueCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtNewListValueCancel As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblListValueTitle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListValueTitle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewListValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewListValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btRequestCriteriaOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btRequestCriteriaOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''updRequestCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRequestCriteria As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''mpxRequestCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpxRequestCriteria As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hiddenTargetControlForRequestCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenTargetControlForRequestCriteria As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divRequestCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRequestCriteria As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ropfREquestCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ropfREquestCriteria As Global.Robotics.WebControls.roPopupFrameV2

    '''<summary>
    '''imgRequestCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRequestCriteria As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblRequestCriteriaTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestCriteriaTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibtRequestCriteriaOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtRequestCriteriaOK As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibtRequestCriteriaCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtRequestCriteriaCancel As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''usrRequestCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usrRequestCriteria As Global.VTLive40.WebUserControls_roUserCtlFieldCriteria

    '''<summary>
    '''MessageFrame1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageFrame1 As Global.VTLive40.Base_WebUserControls_MessageModalV2
End Class
