//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VisualTimeSageConnector.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExternalApiSoap", Namespace="http://tempuri.org/")]
    public partial class ExternalApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateOrUpdateEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrUpdateAbsenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrUpdateHolidaysOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrUpdateCalendarOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAbsencesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPunchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPunchesBetweenDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPunchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccrualsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrUpdateDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrUpdateEmployeeSAGE200cOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ExternalApi() {
            this.Url = global::VisualTimeSageConnector.Properties.Settings.Default.VTSAGE200CServicio_net_visualtime_acb3545_ExternalApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateOrUpdateEmployeeCompletedEventHandler CreateOrUpdateEmployeeCompleted;
        
        /// <remarks/>
        public event CreateOrUpdateAbsenceCompletedEventHandler CreateOrUpdateAbsenceCompleted;
        
        /// <remarks/>
        public event CreateOrUpdateHolidaysCompletedEventHandler CreateOrUpdateHolidaysCompleted;
        
        /// <remarks/>
        public event CreateOrUpdateCalendarCompletedEventHandler CreateOrUpdateCalendarCompleted;
        
        /// <remarks/>
        public event GetAbsencesCompletedEventHandler GetAbsencesCompleted;
        
        /// <remarks/>
        public event GetPunchesCompletedEventHandler GetPunchesCompleted;
        
        /// <remarks/>
        public event GetPunchesBetweenDatesCompletedEventHandler GetPunchesBetweenDatesCompleted;
        
        /// <remarks/>
        public event AddPunchesCompletedEventHandler AddPunchesCompleted;
        
        /// <remarks/>
        public event GetAccrualsCompletedEventHandler GetAccrualsCompleted;
        
        /// <remarks/>
        public event CreateOrUpdateDocumentCompletedEventHandler CreateOrUpdateDocumentCompleted;
        
        /// <remarks/>
        public event CreateOrUpdateEmployeeSAGE200cCompletedEventHandler CreateOrUpdateEmployeeSAGE200cCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrUpdateEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateOrUpdateEmployee(string UserName, string UserPwd, roDatalinkStandarEmployee oEmployee) {
            object[] results = this.Invoke("CreateOrUpdateEmployee", new object[] {
                        UserName,
                        UserPwd,
                        oEmployee});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateEmployeeAsync(string UserName, string UserPwd, roDatalinkStandarEmployee oEmployee) {
            this.CreateOrUpdateEmployeeAsync(UserName, UserPwd, oEmployee, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateEmployeeAsync(string UserName, string UserPwd, roDatalinkStandarEmployee oEmployee, object userState) {
            if ((this.CreateOrUpdateEmployeeOperationCompleted == null)) {
                this.CreateOrUpdateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateEmployeeOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateEmployee", new object[] {
                        UserName,
                        UserPwd,
                        oEmployee}, this.CreateOrUpdateEmployeeOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateEmployeeOperationCompleted(object arg) {
            if ((this.CreateOrUpdateEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateEmployeeCompleted(this, new CreateOrUpdateEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrUpdateAbsence", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateOrUpdateAbsence(string UserName, string UserPwd, roDatalinkStandarAbsence oAbsence) {
            object[] results = this.Invoke("CreateOrUpdateAbsence", new object[] {
                        UserName,
                        UserPwd,
                        oAbsence});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateAbsenceAsync(string UserName, string UserPwd, roDatalinkStandarAbsence oAbsence) {
            this.CreateOrUpdateAbsenceAsync(UserName, UserPwd, oAbsence, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateAbsenceAsync(string UserName, string UserPwd, roDatalinkStandarAbsence oAbsence, object userState) {
            if ((this.CreateOrUpdateAbsenceOperationCompleted == null)) {
                this.CreateOrUpdateAbsenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateAbsenceOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateAbsence", new object[] {
                        UserName,
                        UserPwd,
                        oAbsence}, this.CreateOrUpdateAbsenceOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateAbsenceOperationCompleted(object arg) {
            if ((this.CreateOrUpdateAbsenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateAbsenceCompleted(this, new CreateOrUpdateAbsenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrUpdateHolidays", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateOrUpdateHolidays(string UserName, string UserPwd, roDatalinkStandarHolidays oHolidays) {
            object[] results = this.Invoke("CreateOrUpdateHolidays", new object[] {
                        UserName,
                        UserPwd,
                        oHolidays});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateHolidaysAsync(string UserName, string UserPwd, roDatalinkStandarHolidays oHolidays) {
            this.CreateOrUpdateHolidaysAsync(UserName, UserPwd, oHolidays, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateHolidaysAsync(string UserName, string UserPwd, roDatalinkStandarHolidays oHolidays, object userState) {
            if ((this.CreateOrUpdateHolidaysOperationCompleted == null)) {
                this.CreateOrUpdateHolidaysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateHolidaysOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateHolidays", new object[] {
                        UserName,
                        UserPwd,
                        oHolidays}, this.CreateOrUpdateHolidaysOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateHolidaysOperationCompleted(object arg) {
            if ((this.CreateOrUpdateHolidaysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateHolidaysCompleted(this, new CreateOrUpdateHolidaysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrUpdateCalendar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateOrUpdateCalendar(string UserName, string UserPwd, roDatalinkStandarCalendar oCalendar) {
            object[] results = this.Invoke("CreateOrUpdateCalendar", new object[] {
                        UserName,
                        UserPwd,
                        oCalendar});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateCalendarAsync(string UserName, string UserPwd, roDatalinkStandarCalendar oCalendar) {
            this.CreateOrUpdateCalendarAsync(UserName, UserPwd, oCalendar, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateCalendarAsync(string UserName, string UserPwd, roDatalinkStandarCalendar oCalendar, object userState) {
            if ((this.CreateOrUpdateCalendarOperationCompleted == null)) {
                this.CreateOrUpdateCalendarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateCalendarOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateCalendar", new object[] {
                        UserName,
                        UserPwd,
                        oCalendar}, this.CreateOrUpdateCalendarOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateCalendarOperationCompleted(object arg) {
            if ((this.CreateOrUpdateCalendarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateCalendarCompleted(this, new CreateOrUpdateCalendarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAbsences", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public roDatalinkStandarAbsenceResponse GetAbsences(string UserName, string UserPwd, roDatalinkStandarAbsenceCriteria oAbsenceCriteria) {
            object[] results = this.Invoke("GetAbsences", new object[] {
                        UserName,
                        UserPwd,
                        oAbsenceCriteria});
            return ((roDatalinkStandarAbsenceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAbsencesAsync(string UserName, string UserPwd, roDatalinkStandarAbsenceCriteria oAbsenceCriteria) {
            this.GetAbsencesAsync(UserName, UserPwd, oAbsenceCriteria, null);
        }
        
        /// <remarks/>
        public void GetAbsencesAsync(string UserName, string UserPwd, roDatalinkStandarAbsenceCriteria oAbsenceCriteria, object userState) {
            if ((this.GetAbsencesOperationCompleted == null)) {
                this.GetAbsencesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAbsencesOperationCompleted);
            }
            this.InvokeAsync("GetAbsences", new object[] {
                        UserName,
                        UserPwd,
                        oAbsenceCriteria}, this.GetAbsencesOperationCompleted, userState);
        }
        
        private void OnGetAbsencesOperationCompleted(object arg) {
            if ((this.GetAbsencesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAbsencesCompleted(this, new GetAbsencesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPunches", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public roDatalinkStandardPunchResponse GetPunches(string UserName, string UserPwd, System.DateTime timestamp) {
            object[] results = this.Invoke("GetPunches", new object[] {
                        UserName,
                        UserPwd,
                        timestamp});
            return ((roDatalinkStandardPunchResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetPunchesAsync(string UserName, string UserPwd, System.DateTime timestamp) {
            this.GetPunchesAsync(UserName, UserPwd, timestamp, null);
        }
        
        /// <remarks/>
        public void GetPunchesAsync(string UserName, string UserPwd, System.DateTime timestamp, object userState) {
            if ((this.GetPunchesOperationCompleted == null)) {
                this.GetPunchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPunchesOperationCompleted);
            }
            this.InvokeAsync("GetPunches", new object[] {
                        UserName,
                        UserPwd,
                        timestamp}, this.GetPunchesOperationCompleted, userState);
        }
        
        private void OnGetPunchesOperationCompleted(object arg) {
            if ((this.GetPunchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPunchesCompleted(this, new GetPunchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPunchesBetweenDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public roDatalinkStandardPunchResponse GetPunchesBetweenDates(string UserName, string UserPwd, System.DateTime StartDate, System.DateTime EndDate) {
            object[] results = this.Invoke("GetPunchesBetweenDates", new object[] {
                        UserName,
                        UserPwd,
                        StartDate,
                        EndDate});
            return ((roDatalinkStandardPunchResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetPunchesBetweenDatesAsync(string UserName, string UserPwd, System.DateTime StartDate, System.DateTime EndDate) {
            this.GetPunchesBetweenDatesAsync(UserName, UserPwd, StartDate, EndDate, null);
        }
        
        /// <remarks/>
        public void GetPunchesBetweenDatesAsync(string UserName, string UserPwd, System.DateTime StartDate, System.DateTime EndDate, object userState) {
            if ((this.GetPunchesBetweenDatesOperationCompleted == null)) {
                this.GetPunchesBetweenDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPunchesBetweenDatesOperationCompleted);
            }
            this.InvokeAsync("GetPunchesBetweenDates", new object[] {
                        UserName,
                        UserPwd,
                        StartDate,
                        EndDate}, this.GetPunchesBetweenDatesOperationCompleted, userState);
        }
        
        private void OnGetPunchesBetweenDatesOperationCompleted(object arg) {
            if ((this.GetPunchesBetweenDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPunchesBetweenDatesCompleted(this, new GetPunchesBetweenDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddPunches", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public roDatalinkStandardPunchResponse AddPunches(string UserName, string UserPwd, roDatalinkStandardPunch[] oPunchList) {
            object[] results = this.Invoke("AddPunches", new object[] {
                        UserName,
                        UserPwd,
                        oPunchList});
            return ((roDatalinkStandardPunchResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddPunchesAsync(string UserName, string UserPwd, roDatalinkStandardPunch[] oPunchList) {
            this.AddPunchesAsync(UserName, UserPwd, oPunchList, null);
        }
        
        /// <remarks/>
        public void AddPunchesAsync(string UserName, string UserPwd, roDatalinkStandardPunch[] oPunchList, object userState) {
            if ((this.AddPunchesOperationCompleted == null)) {
                this.AddPunchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPunchesOperationCompleted);
            }
            this.InvokeAsync("AddPunches", new object[] {
                        UserName,
                        UserPwd,
                        oPunchList}, this.AddPunchesOperationCompleted, userState);
        }
        
        private void OnAddPunchesOperationCompleted(object arg) {
            if ((this.AddPunchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPunchesCompleted(this, new AddPunchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccruals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public roDatalinkStandarAccrualResponse GetAccruals(string UserName, string UserPwd, roDatalinkStandarAccrualCriteria oAccrualCriteria) {
            object[] results = this.Invoke("GetAccruals", new object[] {
                        UserName,
                        UserPwd,
                        oAccrualCriteria});
            return ((roDatalinkStandarAccrualResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccrualsAsync(string UserName, string UserPwd, roDatalinkStandarAccrualCriteria oAccrualCriteria) {
            this.GetAccrualsAsync(UserName, UserPwd, oAccrualCriteria, null);
        }
        
        /// <remarks/>
        public void GetAccrualsAsync(string UserName, string UserPwd, roDatalinkStandarAccrualCriteria oAccrualCriteria, object userState) {
            if ((this.GetAccrualsOperationCompleted == null)) {
                this.GetAccrualsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccrualsOperationCompleted);
            }
            this.InvokeAsync("GetAccruals", new object[] {
                        UserName,
                        UserPwd,
                        oAccrualCriteria}, this.GetAccrualsOperationCompleted, userState);
        }
        
        private void OnGetAccrualsOperationCompleted(object arg) {
            if ((this.GetAccrualsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccrualsCompleted(this, new GetAccrualsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrUpdateDocument", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public roDatalinkStandarDocumentResponse CreateOrUpdateDocument(string UserName, string UserPwd, roDatalinkStandardDocument oDocument) {
            object[] results = this.Invoke("CreateOrUpdateDocument", new object[] {
                        UserName,
                        UserPwd,
                        oDocument});
            return ((roDatalinkStandarDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateDocumentAsync(string UserName, string UserPwd, roDatalinkStandardDocument oDocument) {
            this.CreateOrUpdateDocumentAsync(UserName, UserPwd, oDocument, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateDocumentAsync(string UserName, string UserPwd, roDatalinkStandardDocument oDocument, object userState) {
            if ((this.CreateOrUpdateDocumentOperationCompleted == null)) {
                this.CreateOrUpdateDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateDocumentOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateDocument", new object[] {
                        UserName,
                        UserPwd,
                        oDocument}, this.CreateOrUpdateDocumentOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateDocumentOperationCompleted(object arg) {
            if ((this.CreateOrUpdateDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateDocumentCompleted(this, new CreateOrUpdateDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrUpdateEmployeeSAGE200c", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateOrUpdateEmployeeSAGE200c(string UserName, string UserPwd, roDatalinkEmployeeContractsHistory aContracts, roDatalinkStandarEmployee oEmployee) {
            object[] results = this.Invoke("CreateOrUpdateEmployeeSAGE200c", new object[] {
                        UserName,
                        UserPwd,
                        aContracts,
                        oEmployee});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrUpdateEmployeeSAGE200cAsync(string UserName, string UserPwd, roDatalinkEmployeeContractsHistory aContracts, roDatalinkStandarEmployee oEmployee) {
            this.CreateOrUpdateEmployeeSAGE200cAsync(UserName, UserPwd, aContracts, oEmployee, null);
        }
        
        /// <remarks/>
        public void CreateOrUpdateEmployeeSAGE200cAsync(string UserName, string UserPwd, roDatalinkEmployeeContractsHistory aContracts, roDatalinkStandarEmployee oEmployee, object userState) {
            if ((this.CreateOrUpdateEmployeeSAGE200cOperationCompleted == null)) {
                this.CreateOrUpdateEmployeeSAGE200cOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateEmployeeSAGE200cOperationCompleted);
            }
            this.InvokeAsync("CreateOrUpdateEmployeeSAGE200c", new object[] {
                        UserName,
                        UserPwd,
                        aContracts,
                        oEmployee}, this.CreateOrUpdateEmployeeSAGE200cOperationCompleted, userState);
        }
        
        private void OnCreateOrUpdateEmployeeSAGE200cOperationCompleted(object arg) {
            if ((this.CreateOrUpdateEmployeeSAGE200cCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrUpdateEmployeeSAGE200cCompleted(this, new CreateOrUpdateEmployeeSAGE200cCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandarEmployee {
        
        private string nombreEmpleadoField;
        
        private string uniqueEmployeeIDField;
        
        private string nifEmpleadoField;
        
        private string iDContractField;
        
        private string labAgreeNameField;
        
        private System.DateTime startContractDateField;
        
        private System.Nullable<System.DateTime> endContractDateField;
        
        private System.Nullable<System.DateTime> mobilityDateField;
        
        private eCompositeContractType compositeContractTypeField;
        
        private string cardNumberField;
        
        private string userNameField;
        
        private string supervisorGroupField;
        
        private string nivel0Field;
        
        private string nivel1Field;
        
        private string nivel2Field;
        
        private string nivel3Field;
        
        private string nivel4Field;
        
        private string nivel5Field;
        
        private string nivel6Field;
        
        private string nivel7Field;
        
        private string nivel8Field;
        
        private string nivel9Field;
        
        private string nivel10Field;
        
        private string[] activeAuthorizationsField;
        
        private roDatalinkEmployeeUserFieldValue[] userFieldsField;
        
        private string periodField;
        
        private string nifCopyPlanField;
        
        /// <remarks/>
        public string NombreEmpleado {
            get {
                return this.nombreEmpleadoField;
            }
            set {
                this.nombreEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueEmployeeID {
            get {
                return this.uniqueEmployeeIDField;
            }
            set {
                this.uniqueEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NifEmpleado {
            get {
                return this.nifEmpleadoField;
            }
            set {
                this.nifEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        public string IDContract {
            get {
                return this.iDContractField;
            }
            set {
                this.iDContractField = value;
            }
        }
        
        /// <remarks/>
        public string LabAgreeName {
            get {
                return this.labAgreeNameField;
            }
            set {
                this.labAgreeNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartContractDate {
            get {
                return this.startContractDateField;
            }
            set {
                this.startContractDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndContractDate {
            get {
                return this.endContractDateField;
            }
            set {
                this.endContractDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> MobilityDate {
            get {
                return this.mobilityDateField;
            }
            set {
                this.mobilityDateField = value;
            }
        }
        
        /// <remarks/>
        public eCompositeContractType CompositeContractType {
            get {
                return this.compositeContractTypeField;
            }
            set {
                this.compositeContractTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string SupervisorGroup {
            get {
                return this.supervisorGroupField;
            }
            set {
                this.supervisorGroupField = value;
            }
        }
        
        /// <remarks/>
        public string Nivel0 {
            get {
                return this.nivel0Field;
            }
            set {
                this.nivel0Field = value;
            }
        }
        
        /// <remarks/>
        public string Nivel1 {
            get {
                return this.nivel1Field;
            }
            set {
                this.nivel1Field = value;
            }
        }
        
        /// <remarks/>
        public string Nivel2 {
            get {
                return this.nivel2Field;
            }
            set {
                this.nivel2Field = value;
            }
        }
        
        /// <remarks/>
        public string Nivel3 {
            get {
                return this.nivel3Field;
            }
            set {
                this.nivel3Field = value;
            }
        }
        
        /// <remarks/>
        public string Nivel4 {
            get {
                return this.nivel4Field;
            }
            set {
                this.nivel4Field = value;
            }
        }
        
        /// <remarks/>
        public string Nivel5 {
            get {
                return this.nivel5Field;
            }
            set {
                this.nivel5Field = value;
            }
        }
        
        /// <remarks/>
        public string Nivel6 {
            get {
                return this.nivel6Field;
            }
            set {
                this.nivel6Field = value;
            }
        }
        
        /// <remarks/>
        public string Nivel7 {
            get {
                return this.nivel7Field;
            }
            set {
                this.nivel7Field = value;
            }
        }
        
        /// <remarks/>
        public string Nivel8 {
            get {
                return this.nivel8Field;
            }
            set {
                this.nivel8Field = value;
            }
        }
        
        /// <remarks/>
        public string Nivel9 {
            get {
                return this.nivel9Field;
            }
            set {
                this.nivel9Field = value;
            }
        }
        
        /// <remarks/>
        public string Nivel10 {
            get {
                return this.nivel10Field;
            }
            set {
                this.nivel10Field = value;
            }
        }
        
        /// <remarks/>
        public string[] ActiveAuthorizations {
            get {
                return this.activeAuthorizationsField;
            }
            set {
                this.activeAuthorizationsField = value;
            }
        }
        
        /// <remarks/>
        public roDatalinkEmployeeUserFieldValue[] UserFields {
            get {
                return this.userFieldsField;
            }
            set {
                this.userFieldsField = value;
            }
        }
        
        /// <remarks/>
        public string Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        public string NifCopyPlan {
            get {
                return this.nifCopyPlanField;
            }
            set {
                this.nifCopyPlanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum eCompositeContractType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        ContractAndDate,
        
        /// <remarks/>
        CompanyContractAndDate,
        
        /// <remarks/>
        ContractAndPeriod,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkEmployeeUserFieldValue {
        
        private string userFieldNameField;
        
        private string userFieldValueField;
        
        private System.DateTime userFieldValueDateField;
        
        /// <remarks/>
        public string UserFieldName {
            get {
                return this.userFieldNameField;
            }
            set {
                this.userFieldNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserFieldValue {
            get {
                return this.userFieldValueField;
            }
            set {
                this.userFieldValueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UserFieldValueDate {
            get {
                return this.userFieldValueDateField;
            }
            set {
                this.userFieldValueDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkEmployeeContract {
        
        private System.DateTime startContractDateField;
        
        private System.DateTime endContractDateField;
        
        private string iDContractField;
        
        private string labAgreeNameField;
        
        /// <remarks/>
        public System.DateTime StartContractDate {
            get {
                return this.startContractDateField;
            }
            set {
                this.startContractDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndContractDate {
            get {
                return this.endContractDateField;
            }
            set {
                this.endContractDateField = value;
            }
        }
        
        /// <remarks/>
        public string IDContract {
            get {
                return this.iDContractField;
            }
            set {
                this.iDContractField = value;
            }
        }
        
        /// <remarks/>
        public string LabAgreeName {
            get {
                return this.labAgreeNameField;
            }
            set {
                this.labAgreeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkEmployeeContractsHistory {
        
        private roDatalinkEmployeeContract[] contractsField;
        
        /// <remarks/>
        public roDatalinkEmployeeContract[] Contracts {
            get {
                return this.contractsField;
            }
            set {
                this.contractsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandarDocumentResponse {
        
        private int resultCodeField;
        
        private string resultDetailsField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultDetails {
            get {
                return this.resultDetailsField;
            }
            set {
                this.resultDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandardDocument {
        
        private string uniqueEmployeeIDField;
        
        private string nifEmpleadoField;
        
        private string documentTypeField;
        
        private string documentDataField;
        
        private string documentTitleField;
        
        private string documentExtensionField;
        
        private string documentRemarksField;
        
        /// <remarks/>
        public string UniqueEmployeeID {
            get {
                return this.uniqueEmployeeIDField;
            }
            set {
                this.uniqueEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NifEmpleado {
            get {
                return this.nifEmpleadoField;
            }
            set {
                this.nifEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentData {
            get {
                return this.documentDataField;
            }
            set {
                this.documentDataField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentTitle {
            get {
                return this.documentTitleField;
            }
            set {
                this.documentTitleField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentExtension {
            get {
                return this.documentExtensionField;
            }
            set {
                this.documentExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentRemarks {
            get {
                return this.documentRemarksField;
            }
            set {
                this.documentRemarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandarAccrual {
        
        private string uniqueEmployeeIDField;
        
        private string nifEmpleadoField;
        
        private string nifLetterField;
        
        private string accrualExportKeyField;
        
        private string accrualShortNameField;
        
        private System.DateTime accrualDateField;
        
        private double accrualValueField;
        
        /// <remarks/>
        public string UniqueEmployeeID {
            get {
                return this.uniqueEmployeeIDField;
            }
            set {
                this.uniqueEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NifEmpleado {
            get {
                return this.nifEmpleadoField;
            }
            set {
                this.nifEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        public string NifLetter {
            get {
                return this.nifLetterField;
            }
            set {
                this.nifLetterField = value;
            }
        }
        
        /// <remarks/>
        public string AccrualExportKey {
            get {
                return this.accrualExportKeyField;
            }
            set {
                this.accrualExportKeyField = value;
            }
        }
        
        /// <remarks/>
        public string AccrualShortName {
            get {
                return this.accrualShortNameField;
            }
            set {
                this.accrualShortNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AccrualDate {
            get {
                return this.accrualDateField;
            }
            set {
                this.accrualDateField = value;
            }
        }
        
        /// <remarks/>
        public double AccrualValue {
            get {
                return this.accrualValueField;
            }
            set {
                this.accrualValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandarAccrualResponse {
        
        private int resultCodeField;
        
        private roDatalinkStandarAccrual[] accrualsField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public roDatalinkStandarAccrual[] Accruals {
            get {
                return this.accrualsField;
            }
            set {
                this.accrualsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandarAccrualCriteria {
        
        private string uniqueEmployeeIDField;
        
        private string nifEmpleadoField;
        
        private string nifLetterField;
        
        private System.DateTime startAccrualPeriodField;
        
        private System.DateTime endAccrualPeriodField;
        
        /// <remarks/>
        public string UniqueEmployeeID {
            get {
                return this.uniqueEmployeeIDField;
            }
            set {
                this.uniqueEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NifEmpleado {
            get {
                return this.nifEmpleadoField;
            }
            set {
                this.nifEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        public string NifLetter {
            get {
                return this.nifLetterField;
            }
            set {
                this.nifLetterField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartAccrualPeriod {
            get {
                return this.startAccrualPeriodField;
            }
            set {
                this.startAccrualPeriodField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndAccrualPeriod {
            get {
                return this.endAccrualPeriodField;
            }
            set {
                this.endAccrualPeriodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandardPunch {
        
        private string uniqueEmployeeIDField;
        
        private string nifEmpleadoField;
        
        private string nifLetterField;
        
        private PunchTypeEnum typeField;
        
        private PunchTypeEnum actualTypeField;
        
        private System.DateTime dateTimeField;
        
        private int iDTerminalField;
        
        private string typeDataField;
        
        private string gPSField;
        
        private string field1Field;
        
        private string field2Field;
        
        private string field3Field;
        
        private System.Nullable<double> field4Field;
        
        private System.Nullable<double> field5Field;
        
        private System.Nullable<double> field6Field;
        
        private int resultCodeField;
        
        private string resultDescriptionField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string UniqueEmployeeID {
            get {
                return this.uniqueEmployeeIDField;
            }
            set {
                this.uniqueEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NifEmpleado {
            get {
                return this.nifEmpleadoField;
            }
            set {
                this.nifEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        public string NifLetter {
            get {
                return this.nifLetterField;
            }
            set {
                this.nifLetterField = value;
            }
        }
        
        /// <remarks/>
        public PunchTypeEnum Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public PunchTypeEnum ActualType {
            get {
                return this.actualTypeField;
            }
            set {
                this.actualTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public int IDTerminal {
            get {
                return this.iDTerminalField;
            }
            set {
                this.iDTerminalField = value;
            }
        }
        
        /// <remarks/>
        public string TypeData {
            get {
                return this.typeDataField;
            }
            set {
                this.typeDataField = value;
            }
        }
        
        /// <remarks/>
        public string GPS {
            get {
                return this.gPSField;
            }
            set {
                this.gPSField = value;
            }
        }
        
        /// <remarks/>
        public string Field1 {
            get {
                return this.field1Field;
            }
            set {
                this.field1Field = value;
            }
        }
        
        /// <remarks/>
        public string Field2 {
            get {
                return this.field2Field;
            }
            set {
                this.field2Field = value;
            }
        }
        
        /// <remarks/>
        public string Field3 {
            get {
                return this.field3Field;
            }
            set {
                this.field3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Field4 {
            get {
                return this.field4Field;
            }
            set {
                this.field4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Field5 {
            get {
                return this.field5Field;
            }
            set {
                this.field5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Field6 {
            get {
                return this.field6Field;
            }
            set {
                this.field6Field = value;
            }
        }
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PunchTypeEnum {
        
        /// <remarks/>
        _NOTDEFINDED,
        
        /// <remarks/>
        _IN,
        
        /// <remarks/>
        _OUT,
        
        /// <remarks/>
        _AUTO,
        
        /// <remarks/>
        _TASK,
        
        /// <remarks/>
        _AV,
        
        /// <remarks/>
        _AI,
        
        /// <remarks/>
        _L,
        
        /// <remarks/>
        _INI,
        
        /// <remarks/>
        _OUTI,
        
        /// <remarks/>
        _DR,
        
        /// <remarks/>
        _AEV,
        
        /// <remarks/>
        _AEI,
        
        /// <remarks/>
        _CENTER,
        
        /// <remarks/>
        _RPTIN,
        
        /// <remarks/>
        _RPTOUT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandardPunchResponse {
        
        private int resultCodeField;
        
        private roDatalinkStandardPunch[] punchesField;
        
        private roDatalinkStandardPunch[] punchesListErrorField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public roDatalinkStandardPunch[] Punches {
            get {
                return this.punchesField;
            }
            set {
                this.punchesField = value;
            }
        }
        
        /// <remarks/>
        public roDatalinkStandardPunch[] PunchesListError {
            get {
                return this.punchesListErrorField;
            }
            set {
                this.punchesListErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandarAbsenceResponse {
        
        private int resultCodeField;
        
        private roDatalinkStandarAbsence[] absencesField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public roDatalinkStandarAbsence[] Absences {
            get {
                return this.absencesField;
            }
            set {
                this.absencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandarAbsence {
        
        private string actionField;
        
        private string uniqueEmployeeIDField;
        
        private string nifEmpleadoField;
        
        private string nifLetterField;
        
        private string causeShortNameField;
        
        private System.DateTime startAbsenceDateField;
        
        private System.Nullable<System.DateTime> endAbsenceDateField;
        
        private System.Nullable<int> maxDaysField;
        
        private System.Nullable<System.DateTime> beginHourField;
        
        private System.Nullable<System.DateTime> endHourField;
        
        private System.Nullable<System.DateTime> durationField;
        
        private string causeExportKeyField;
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueEmployeeID {
            get {
                return this.uniqueEmployeeIDField;
            }
            set {
                this.uniqueEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NifEmpleado {
            get {
                return this.nifEmpleadoField;
            }
            set {
                this.nifEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        public string NifLetter {
            get {
                return this.nifLetterField;
            }
            set {
                this.nifLetterField = value;
            }
        }
        
        /// <remarks/>
        public string CauseShortName {
            get {
                return this.causeShortNameField;
            }
            set {
                this.causeShortNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartAbsenceDate {
            get {
                return this.startAbsenceDateField;
            }
            set {
                this.startAbsenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndAbsenceDate {
            get {
                return this.endAbsenceDateField;
            }
            set {
                this.endAbsenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaxDays {
            get {
                return this.maxDaysField;
            }
            set {
                this.maxDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BeginHour {
            get {
                return this.beginHourField;
            }
            set {
                this.beginHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndHour {
            get {
                return this.endHourField;
            }
            set {
                this.endHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public string CauseExportKey {
            get {
                return this.causeExportKeyField;
            }
            set {
                this.causeExportKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandarAbsenceCriteria {
        
        private string uniqueEmployeeIDField;
        
        private string nifEmpleadoField;
        
        private string nifLetterField;
        
        private System.DateTime startAbsencePeriodField;
        
        private System.DateTime endAbsencePeriodField;
        
        /// <remarks/>
        public string UniqueEmployeeID {
            get {
                return this.uniqueEmployeeIDField;
            }
            set {
                this.uniqueEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NifEmpleado {
            get {
                return this.nifEmpleadoField;
            }
            set {
                this.nifEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        public string NifLetter {
            get {
                return this.nifLetterField;
            }
            set {
                this.nifLetterField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartAbsencePeriod {
            get {
                return this.startAbsencePeriodField;
            }
            set {
                this.startAbsencePeriodField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndAbsencePeriod {
            get {
                return this.endAbsencePeriodField;
            }
            set {
                this.endAbsencePeriodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandarCalendar {
        
        private string uniqueEmployeeIDField;
        
        private string nifEmpleadoField;
        
        private string nifLetterField;
        
        private string shiftKeyField;
        
        private System.DateTime planDateField;
        
        /// <remarks/>
        public string UniqueEmployeeID {
            get {
                return this.uniqueEmployeeIDField;
            }
            set {
                this.uniqueEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NifEmpleado {
            get {
                return this.nifEmpleadoField;
            }
            set {
                this.nifEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        public string NifLetter {
            get {
                return this.nifLetterField;
            }
            set {
                this.nifLetterField = value;
            }
        }
        
        /// <remarks/>
        public string ShiftKey {
            get {
                return this.shiftKeyField;
            }
            set {
                this.shiftKeyField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PlanDate {
            get {
                return this.planDateField;
            }
            set {
                this.planDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class roDatalinkStandarHolidays {
        
        private string actionField;
        
        private string uniqueEmployeeIDField;
        
        private string nifEmpleadoField;
        
        private string nifLetterField;
        
        private string shiftKeyField;
        
        private System.DateTime planDateField;
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueEmployeeID {
            get {
                return this.uniqueEmployeeIDField;
            }
            set {
                this.uniqueEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NifEmpleado {
            get {
                return this.nifEmpleadoField;
            }
            set {
                this.nifEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        public string NifLetter {
            get {
                return this.nifLetterField;
            }
            set {
                this.nifLetterField = value;
            }
        }
        
        /// <remarks/>
        public string ShiftKey {
            get {
                return this.shiftKeyField;
            }
            set {
                this.shiftKeyField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PlanDate {
            get {
                return this.planDateField;
            }
            set {
                this.planDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateOrUpdateEmployeeCompletedEventHandler(object sender, CreateOrUpdateEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateOrUpdateAbsenceCompletedEventHandler(object sender, CreateOrUpdateAbsenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateAbsenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateAbsenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateOrUpdateHolidaysCompletedEventHandler(object sender, CreateOrUpdateHolidaysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateHolidaysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateHolidaysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateOrUpdateCalendarCompletedEventHandler(object sender, CreateOrUpdateCalendarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateCalendarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateCalendarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAbsencesCompletedEventHandler(object sender, GetAbsencesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAbsencesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAbsencesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public roDatalinkStandarAbsenceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((roDatalinkStandarAbsenceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetPunchesCompletedEventHandler(object sender, GetPunchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPunchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPunchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public roDatalinkStandardPunchResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((roDatalinkStandardPunchResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetPunchesBetweenDatesCompletedEventHandler(object sender, GetPunchesBetweenDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPunchesBetweenDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPunchesBetweenDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public roDatalinkStandardPunchResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((roDatalinkStandardPunchResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddPunchesCompletedEventHandler(object sender, AddPunchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPunchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPunchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public roDatalinkStandardPunchResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((roDatalinkStandardPunchResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAccrualsCompletedEventHandler(object sender, GetAccrualsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccrualsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccrualsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public roDatalinkStandarAccrualResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((roDatalinkStandarAccrualResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateOrUpdateDocumentCompletedEventHandler(object sender, CreateOrUpdateDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public roDatalinkStandarDocumentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((roDatalinkStandarDocumentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateOrUpdateEmployeeSAGE200cCompletedEventHandler(object sender, CreateOrUpdateEmployeeSAGE200cCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrUpdateEmployeeSAGE200cCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrUpdateEmployeeSAGE200cCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591