namespace Emplyx.Shared.Contracts.Tenants;

public record TenantResponse(
    Guid Id,
    string InternalId,
    string CompanyType,
    string LegalName,
    string? TradeName,
    string TaxId,
    string? CountryOfConstitution,
    DateTime? DateOfConstitution,
    string? CommercialRegister,
    string? ProvinceOfRegister,
    string? RegisterDetails,
    AddressDto LegalAddress,
    AddressDto? FiscalAddress,
    ContactPersonDto MainContact,
    string? GeneralPhone,
    string? GeneralEmail,
    string? BillingEmail,
    string? Website,
    string? SocialMedia,
    string? VATRegime,
    string? IntraCommunityVAT,
    string? IRPFRegime,
    string? Currency,
    string? PaymentMethod,
    string? PaymentTerm,
    decimal? CreditLimit,
    bool PORequired,
    string? InvoiceDeliveryMethod,
    string? BillingNotes,
    BankAccountDto? BankAccount,
    int? EmployeeCount,
    string? CollectiveAgreement,
    string? CNAE,
    string? WorkDayType,
    bool HasShifts,
    string? RelationType,
    string? Segment,
    string? Sector,
    string? CompanySize,
    decimal? AnnualRevenue,
    string? Source,
    string? InternalAccountManager,
    string? Status,
    bool PortalAccess,
    AdminUserDto? AdminUser,
    string? Language,
    string? TimeZone,
    bool CommercialComms,
    bool OperationalComms,
    string? PreferredChannel,
    bool GDPRConsent,
    bool TermsAccepted,
    bool PrivacyAccepted,
    DateTime? AcceptanceDate,
    string? AcceptanceIP,
    DateTime CreatedAtUtc,
    string? CreatedBy,
    string? InternalNotes,
    string? Tags
);

public record AddressDto(string Street, string ZipCode, string City, string Province, string Country);
public record ContactPersonDto(string Name, string JobTitle, string Phone, string Mobile, string Email);
public record BankAccountDto(string AccountHolder, string IBAN, string BIC, string BankName, bool SEPAAuth, DateTime? SEPAAuthDate, string? SEPAReference);
public record AdminUserDto(string Name, string Email, string Phone);
