'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Wizards_NewMultiEmployeeWizard

    '''<summary>
    '''frmNewMultiEmployeeWizard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmNewMultiEmployeeWizard As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''hdnIdGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIdGroup As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnDisableBiometric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDisableBiometric As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnStepTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStepTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnStepTitle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStepTitle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updStep0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStep0 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divStep0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep0 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgNewMultiEmployeeWizard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewMultiEmployeeWizard As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblWelcome1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcome1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWelcome2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcome2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWelcome3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcome3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStep1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStep1Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep1Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSetp2Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSetp2Info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep1Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep1Error As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep1Info2a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep1Info2a As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep1Info2b control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep1Info2b As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep1Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep1Info2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumberEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberEmployees As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNumberEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumberEmployees As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''updStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStep2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStep2Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep2Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSetp3Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSetp3Info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep2Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep2Info2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep2Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep2Error As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBeginContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBeginContract As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBeginContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBeginContract As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''updStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStep3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStep3Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep3Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep3Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep3Info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep3Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep3Error As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep3Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep3Info2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optNumberContractLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNumberContractLast As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblNumberContractLastTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberContractLastTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumberContractLastDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberContractLastDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optNumberContractNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNumberContractNew As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblNumberContractNewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberContractNewTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumberContractNewDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberContractNewDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumberContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberContract As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNumberContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumberContract As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''gBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gBox1 As Global.VTLive40.base_WebUserControls_roGroupBox

    '''<summary>
    '''lblLabAgree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabAgree As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbLabAgree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLabAgree As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''optNumberContractGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNumberContractGroup As Global.VTLive40.base_WebUserControls_roOptPanelClientGroup

    '''<summary>
    '''updStep4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStep4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divStep4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStep4Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep4Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSetp4Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSetp4Info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep4Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep4Error As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep4Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep4Info2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cnIdentifyMethods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnIdentifyMethods As Global.VTLive40.Base_WebUserControls_IdentifyMethods

    '''<summary>
    '''updStep5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStep5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divStep5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStep5Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep5Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSetp5Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSetp5Info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep5Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep5Error As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep5Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep5Info2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optCardsFromLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optCardsFromLast As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblCardsFromLastTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCardsFromLastTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCardsFromLastDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCardsFromLastDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optCardsContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optCardsContract As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblCardsContractTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCardsContractTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCardsContractDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCardsContractDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optCardsFromNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optCardsFromNumber As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblCardsFromNumberTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCardsFromNumberTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCardsFromNumberDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCardsFromNumberDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCardsFromNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCardsFromNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCardsFromNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCardsFromNumber As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''updStep6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStep6 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divStep6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStep6Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep6Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep6Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep6Info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep6Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep6Error As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep6Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep6Info2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridEmployeesWizard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridEmployeesWizard As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''updStep7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStep7 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divStep7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStep7Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep7Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSetp7Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSetp7Info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep7Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep7Info2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep7Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep7Error As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cnEmployeeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnEmployeeType As Global.VTLive40.WebUserControls_EmployeeType

    '''<summary>
    '''updStep8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStep8 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divStep8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStep8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStep8Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep8Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSetp8Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSetp8Info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStep8Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep8Error As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkParentGroupNull control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkParentGroupNull As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hdnPassportSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPassportSelected As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ifPassportSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifPassportSelector As Global.System.Web.UI.HtmlControls.HtmlIframe

    '''<summary>
    '''updButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updButtons As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btPrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btPrev As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btNext As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btEnd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnCanClose_PageBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCanClose_PageBase As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnMustRefresh_PageBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMustRefresh_PageBase As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnActiveFrame control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnActiveFrame As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''MessageForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageForm As Global.VTLive40.Base_WebUserControls_MessageModalV2
End Class
