UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'ITA') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 ore su 24 tutto l''anno' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 ore Totale' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'Vacanze a strascico' WHERE LanguageTag = 'arrastredevacaciones'
UPDATE accrualsrules SET description = 'Le ferie dell''anno precedente possono essere godute fino al 31/1 dell''anno in corso. Se non sono state godute, si perdono (scadono).' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE accrualsrules SET name = 'Scadenza del congedo dell''anno precedente' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE causelimitvalues SET name = 'Limite di 80 ore di retribuzione per lavoro straordinario' WHERE LanguageTag = 'limitede80horasextrasapagar'
UPDATE causes SET description = 'Basso ATEP' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET name = 'Basso ATEP' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET description = 'Basso CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET name = 'Basso CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET description = 'Doveri non scusabili, di natura pubblica e/o personale' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET name = 'Doveri non scusabili, di natura pubblica e/o personale' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET description = 'Esami ufficiali' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET name = 'Esami ufficiali' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET description = 'Esami prenatali e tecniche di preparazione al parto' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET name = 'Esami prenatali e tecniche di preparazione al parto' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET description = 'Quelli che eccedono l''orario ordinario della giornata lavorativa, ma la cui prestazione è stata concordata e stabilita in un contratto part-time. Possono essere di 2 tipi: -Orario concordato: contratti a tempo parziale con una giornata lavorativa non inferiore a dieci ore settimanali su base annua. -Orario volontario: contratti part-time a tempo indeterminato con una giornata lavorativa non inferiore a 10 ore settimanali su base annua.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'ore complementari' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Ore di lavoro svolte oltre la durata massima della giornata lavorativa ordinaria stabilita per legge o per accordo.  Questo tipo di lavoro può essere svolto per un massimo di 80 ore all''anno.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = 'Lavoro straordinario' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Ore lavorate nell''ambito dell''orario di lavoro previsto dal dipendente.' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET name = 'Orario ordinario' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET description = 'Tempo pianificato che non è stato lavorato e che deve essere recuperato in un altro momento.' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET name = 'Ore da recuperare' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET description = 'Ore positive che vengono effettuate per compensare le ore negative che possono essere effettuate, adatte alle aziende con flessibilità.' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET name = 'Ore recuperate' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET description = 'Allattamento al seno' WHERE LanguageTag = 'lactancia'
UPDATE causes SET name = 'Allattamento al seno' WHERE LanguageTag = 'lactancia'
UPDATE causes SET description = 'Maternità/Paternità' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET name = 'Maternità/Paternità' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET description = 'Matrimonio in famiglia' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET name = 'Matrimonio in famiglia' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET description = 'Il proprio matrimonio' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET name = 'Il proprio matrimonio' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET description = 'Il medico' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Il medico' WHERE LanguageTag = 'medico'
UPDATE causes SET description = 'Nascita del bambino' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET name = 'Nascita del bambino' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET description = 'Congedo per cause di forza maggiore' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET name = 'Congedo per cause di forza maggiore' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET description = '8 settimane di congedo parentale' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET name = '8 settimane di congedo parentale' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET description = 'Congedo per assistenza a parenti di 2° grado o conviventi' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET name = 'Congedo per assistenza a parenti di 2° grado o conviventi' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET description = 'Si tratta di un congedo che può essere preso per qualsiasi motivo, a meno che il contratto applicabile non specifichi diversamente e vi sia un accordo tra datore di lavoro e dipendente. Sospende l''obbligo di lavorare e di pagare la retribuzione corrispondente al periodo di assenza del dipendente. Non sono regolati dalla legge (tranne che in alcuni contratti collettivi). Le condizioni di utilizzo e di godimento di questi permessi/permessi sono regolate da accordi tra datore di lavoro e dipendente.' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = 'Congedo obbligatorio non retribuito' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'Il congedo retribuito è un tipo di assenza durante la quale il lavoratore continuerà a essere compensato economicamente. I permessi retribuiti sono disciplinati dall''articolo 37 dello Statuto dei lavoratori e dai contratti collettivi.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Congedo legale retribuito' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'Trasferimento della residenza abituale' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET name = 'Trasferimento della residenza abituale' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET description = 'Assenza dovuta a ferie annuali retribuite. Non è sostituibile da una compensazione economica; sarà l''importo concordato nel Contratto Collettivo o nel contratto individuale. Nel rispetto di questo accordo il minimo legale è di 30 giorni di calendario all''anno.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Vacanza' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Vacanze dell''anno precedente.' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET name = 'Vacanze dell''anno precedente' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET description = 'VT. Vacanze a strascico' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET name = 'VT. Vacanze a strascico' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET description = 'VT. Scadenza vacanze' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET name = 'VT. Scadenza vacanze' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET description = 'Le ore che sono state pianificate per il dipendente e che devono essere svolte da quest''ultimo. Giustificazione interna di VisualTime, da non cancellare o modificare.' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET name = 'VT. Ore teoriche' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET description = 'Assenza ingiustificata che genera un avviso. L''obiettivo è che non ci sia un orario giustificato per questo motivo. Giustificazione interna di VisualTime, da non cancellare o modificare.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. NON GIUSTIFICATO' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET description = 'VT. Tempo in eccesso non autorizzato' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE causes SET name = 'VT. Tempo in eccesso non autorizzato' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE concepts SET description = 'Assenze dal lavoro giustificate ma non retribuite.' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET name = 'Assenteismo non retribuito' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET description = 'Assenze retribuite e giustificate dal lavoro.' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET name = 'Assenze retribuite' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET description = 'Questo saldo sottrae tutte le "ore da recuperare" e aggiunge tutte le "ore recuperate". Se il totale di questo saldo è negativo, il dipendente deve delle ore all''azienda.  Se il totale di questo saldo è positivo, l''azienda deve delle ore al dipendente.' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET name = 'Saldo delle ore' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET description = 'Straordinari. Massimo 80 ore all''anno.' WHERE LanguageTag = 'extras'
UPDATE concepts SET name = 'Extra' WHERE LanguageTag = 'extras'
UPDATE concepts SET description = 'Ore aggiuntive per contratti part-time.' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET name = 'Ore complementari' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET description = 'Tempo pianificato, questo è il tempo che devo dedicare agli orari' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET name = 'Tempo pianificato' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET description = 'Tutto il tempo che viene considerato lavoro effettivo, esclusi gli straordinari.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Lavoro efficace' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'Vacanze dell''anno precedente' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET name = 'Vacanze dell''anno precedente' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET description = 'Questo saldo indica le ferie ancora da prendere.   Saldo iniziale delle ferie - ferie godute = ferie arretrate' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Vacanze in attesa' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'La mia azienda' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'Regole generali' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'Periodo di ferie anno precedente' WHERE LanguageTag = 'periododisfrutevacacionesañoanterior'
UPDATE requestsrules SET name = 'Saldo ferie negativo' WHERE LanguageTag = 'saldonegativovacaciones'
UPDATE shifts SET description = 'Ricordate che potete adattare questo orario quando lo pianificate: vi permette di assegnare un orario di entrata, un numero di ore sia ordinarie che complementari.  In questo esempio solo una fascia oraria.  ' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET name = 'Joker 1 striscia' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET description = 'Ricordate che potete adattare questo orario quando lo pianificate: vi permette di assegnare un orario di entrata, un numero di ore sia ordinarie che complementari.  In questo esempio due fasce orarie.  ' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET name = 'Joker 2 strisce' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET description = 'Questo orario è utile solo nel caso in cui si voglia registrare solo la giornata lavorativa (per rispettare le normative) e non si voglia effettuare alcun tipo di gestione del tempo.  ' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET name = 'Contatore orario' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET description = 'Questo orario ha 0 ore pianificate. Deve essere pianificato solo nei giorni in cui il dipendente ha un''intera giornata libera e quindi non timbra il cartellino.  ' WHERE LanguageTag = 'descanso'
UPDATE shifts SET name = 'riposo' WHERE LanguageTag = 'descanso'
UPDATE shifts SET description = 'Questo orario ha 0 ore pianificate. Sarà pianificato solo per i giorni in cui il dipendente ha un giorno festivo e quindi non timbra il cartellino.' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Festivo' WHERE LanguageTag = 'festivo'
UPDATE shifts SET description = 'Si tratta di un orario totalmente flessibile. Il dipendente può timbrare liberamente l''entrata e l''uscita tra le 6:00 e le 23:00 e sarà monitorato solo se fa più o meno delle 8 ore previste.  ' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET name = 'Flessibile 8h' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET description = 'Esempio di orario d''ufficio rigido (orario obbligatorio), con inizio alle 8:00 e fine alle 14:00 e inizio alle 15:00 e fine alle 17:00, senza dimenticare di timbrare l''entrata e l''uscita per le pause.  ' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET name = 'Festa in ufficio' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET description = 'Esempio di orario intensivo (ore obbligatorie), con inizio alle ore 6:00 e partenza alle ore 14:00.  ' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET name = 'Turno di produzione da 6 a 14' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET description = 'Ferie nei giorni lavorativi.  ' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Vacanza' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET description = 'Vacanze dell''anno precedente.  ' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE shifts SET name = 'Vacanze dell''anno precedente' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE startupvalues SET name = 'Vacanze iniziali' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = 'Giorni di ferie annuali' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'Ore' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Misto (ore+occorrenze)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Occorrenze' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Accertarsi di quanto sia rimasto del ricalcolo di VisualTime e di quanti dipendenti siano interessati' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Accertarsi di quanto sia rimasto del ricalcolo di VisualTime e di quanti dipendenti siano interessati' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Controllare il gruppo di appartenenza dei dipendenti. Percorso breve e completo' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Controllare il gruppo di appartenenza dei dipendenti. Percorso breve e completo' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Verificare se c''è un''attività che non può essere eseguita normalmente' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Verificare se c''è un''attività che non può essere eseguita normalmente' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Controllare se il ricalcolo dopo le modifiche apportate in VisualTime funziona correttamente' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Controllare se il ricalcolo dopo le modifiche apportate in VisualTime funziona correttamente' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Mostra le autorizzazioni dei diversi supervisori sulle richieste in sospeso, compreso se il supervisore è diretto o meno per ogni richiesta' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET name = 'Permessi su domande pendenti' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET description = 'Per sapere se il file di correlazione è stato inserito correttamente nel database' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'Per sapere se il file di correlazione è stato inserito correttamente nel database' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'Vedere le firme che hanno avuto luogo in una data specifica (è possibile scegliere la data)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'Vedere le firme che hanno avuto luogo in una data specifica (è possibile scegliere la data)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'Visualizzazione dei compiti in sospeso appesi ai terminali dopo la trasmissione' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'Visualizzazione dei compiti in sospeso appesi ai terminali dopo la trasmissione' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Rapporto sulle assenze' WHERE LanguageTag = 'informedeabsentismo'
UPDATE sysroreportgroups SET name = 'Rapporto di bilancio' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Eccezionale relazione sulle vacanze' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysroreportgroups SET name = 'Relazione generale' WHERE LanguageTag = 'informegeneral'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Categoria professionale' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Assistenti amministrativi~Assistenti non laureati~Ingegneri tecnici, periti e assistenti laureati~Ingegneri e laureati~Responsabili amministrativi e di officina~Ufficiali amministrativi~Ufficiali di prima e seconda classe~Ufficiali di terza classe e specialisti~Peoni~Subalterni~Lavoratori di età inferiore ai 18 anni' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Codice postale' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Complementi salariali annuali' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'E-mail' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'Costo delle risorse umane' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Costo all´ora' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET fieldname = 'Giorni di ferie annuali' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET category = 'Personale' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Data di nascita' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Genere' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Maschio~Femmina' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Gruppo contributivo' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET fieldname = 'Identificatore dell''utente' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'ID importazione' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET fieldname = 'Motivo della partenza' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Congedo volontario~Licenziamento~Licenziamento~Temporanea risoluzione del contratto~Inabilità~Invalidità~Pensionamento~Per motivi concordati nel contratto' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Cellulare' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Personale' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Nazionalità' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Personale' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'CF' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Numero di emergenza' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Osservazioni' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Riscossioni extrasalariali' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Riscossioni per straordinari e complementari' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Comune' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Prezzo per ora' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Provincia' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'Posta' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Punto d''incontro' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Salario base annuale' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Salario totale annuale' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Telefono' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Tipo di contratto' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'Apprendista~Indefinito~Temporaneo' WHERE LanguageTag = 'tipodecontrato'
UPDATE timezones SET name = 'Ore con retribuzione speciale' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Orario notturno' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Orario normale' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Assenti' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Presente' WHERE LanguageTag = 'presentes'
GO