UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'SLK') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 hodín po celý rok' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 h Spolu' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'Vlečná sieť na dovolenke' WHERE LanguageTag = 'arrastredevacaciones'
UPDATE accrualsrules SET description = 'Dovolenku z predchádzajúceho roka si môžete vybrať do 31. 1. bežného roka. Ak sa nevyčerpajú, prepadajú (strácajú platnosť).' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE accrualsrules SET name = 'Uplynutie dovolenky za predchádzajúci rok' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE causelimitvalues SET name = 'Limit 80 hodín nadčasov' WHERE LanguageTag = 'limitede80horasextrasapagar'
UPDATE causes SET description = 'Dovolenka ATEP' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET name = 'Dovolenka ATEP' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET description = 'Nízka CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET name = 'Nízka CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET description = 'Neospravedlniteľné povinnosti verejného a/alebo osobného charakteru' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET name = 'Neospravedlniteľné povinnosti verejného a/alebo osobného charakteru' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET description = 'Úradné skúšky' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET name = 'Úradné skúšky' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET description = 'Prenatálne vyšetrenia a techniky prípravy na pôrod' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET name = 'Prenatálne vyšetrenia a techniky prípravy na pôrod' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET description = 'Tí, ktorí prekračujú bežný pracovný čas, ale ktorých výkon bol dohodnutý a schválený v zmluve na čiastočný úväzok. Môžu byť 2 typy: -Dohodnutý pracovný čas: Zmluvy na čiastočný úväzok s pracovným dňom v rozsahu najmenej desať hodín týždenne na ročnom základe. -Dobrovoľné hodiny: Zmluvy na čiastočný úväzok na dobu neurčitú s pracovným dňom nie kratším ako 10 hodín týždenne na ročnom základe.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'doplnkové hodiny' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Hodiny práce vykonávanej v rámci maximálneho trvania bežného pracovného dňa stanoveného zákonom alebo dohodou.  Za rok sa môže odpracovať maximálne 80 hodín tohto druhu práce.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = 'Nadčasy' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Odpracované hodiny v rámci plánovaného pracovného času zamestnanca.' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET name = 'Bežné hodiny' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET description = 'Plánovaný čas, ktorý nebol odpracovaný a musí byť nahradený v inom čase.' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET name = 'Hodiny, ktoré sa majú doplniť' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET description = 'Kladné hodiny, ktoré sú vytvorené na kompenzáciu záporných hodín, ktoré môžu byť vytvorené, vhodné pre spoločnosti s flexibilitou.' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET name = 'Získané hodiny' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET description = 'Dojčenie' WHERE LanguageTag = 'lactancia'
UPDATE causes SET name = 'Dojčenie' WHERE LanguageTag = 'lactancia'
UPDATE causes SET description = 'Materstvo/otcovstvo' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET name = 'Materstvo/otcovstvo' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET description = 'Rodinné manželstvo' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET name = 'Rodinné manželstvo' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET description = 'Vlastné manželstvo' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET name = 'Vlastné manželstvo' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET description = 'Doktor' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Doktor' WHERE LanguageTag = 'medico'
UPDATE causes SET description = 'Narodenie dieťaťa' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET name = 'Narodenie dieťaťa' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET description = 'Dovolenka z dôvodu vyššej moci' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET name = 'Dovolenka z dôvodu vyššej moci' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET description = '8 týždňov rodičovskej dovolenky' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET name = '8 týždňov rodičovskej dovolenky' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET description = 'Dovolenka na starostlivosť o príbuzných druhého stupňa alebo partnerov žijúcich v spoločnej domácnosti' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET name = 'Dovolenka na starostlivosť o príbuzných druhého stupňa alebo partnerov žijúcich v spoločnej domácnosti' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET description = 'Ide o dovolenku, ktorú si možno vziať z akéhokoľvek dôvodu, pokiaľ platná dohoda nestanovuje inak a pokiaľ neexistuje dohoda medzi zamestnávateľom a zamestnancom. Pozastavuje povinnosť pracovať a vyplácať mzdu zodpovedajúcu času, počas ktorého bol zamestnanec neprítomný. Nie sú upravené zákonom (s výnimkou niektorých kolektívnych zmlúv). Podmienky čerpania a využívania týchto dovoleniek/odpočinku upravujú dohody medzi zamestnávateľom a zamestnancom.' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = 'Neplatená zákonná dovolenka' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'Platené voľno je druh neprítomnosti, počas ktorej pracovník naďalej dostáva finančnú náhradu. Platené voľno je upravené v článku 37 Štatútu zamestnancov a v kolektívnych zmluvách.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Platená zákonná dovolenka' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'Presun obvyklého bydliska' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET name = 'Presun obvyklého bydliska' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET description = 'Neprítomnosť z dôvodu platenej dovolenky. Nenahrádza sa finančnou náhradou; jej výška je dohodnutá v kolektívnej zmluve alebo v individuálnej zmluve. Pri rešpektovaní tejto dohody je zákonné minimum 30 kalendárnych dní ročne.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Dovolenka' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Dovolenka v predchádzajúcom roku.' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET name = 'Dovolenka v predchádzajúcom roku' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET description = 'VT. Dovolenka s vlečnými sieťami' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET name = 'VT. Dovolenka s vlečnými sieťami' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET description = 'VT. Uplynutie platnosti dovolenky' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET name = 'VT. Uplynutie platnosti dovolenky' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET description = 'Hodiny, ktoré boli pre zamestnanca naplánované a ktoré by mal vykonať. Interné zdôvodnenie VisualTime, ktoré sa nesmie vymazať ani zmeniť.' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET name = 'VT. Teoretické hodiny' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET description = 'Neospravedlnená neprítomnosť, ktorá generuje upozornenie. Cieľom je, aby z tohto dôvodu nebol ospravedlnený čas. Interné ospravedlnenie VisualTime, ktoré sa nesmie vymazať ani upraviť.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. NIE JE OSPRAVODLNENÝ' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET description = 'VT. Neoprávnené prekročenie času' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE causes SET name = 'VT. Neoprávnené prekročenie času' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE concepts SET description = 'Ospravedlnené, ale neplatené pracovné voľno.' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET name = 'Neplatené absencie' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET description = 'Platené a ospravedlnené pracovné voľno.' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET name = 'Platené absencie' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET description = 'Týmto zostatkom sa odpočítajú všetky "hodiny, ktoré sa majú obnoviť" a pripočítajú sa všetky "obnovené hodiny". Ak je súčet tohto zostatku záporný, zamestnanec dlhuje spoločnosti hodiny.  Ak je súčet tohto zostatku kladný, spoločnosť dlhuje zamestnancovi hodiny.' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET name = 'Zostatok hodín' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET description = 'Nadčasy. Maximálne 80 hodín ročne.' WHERE LanguageTag = 'extras'
UPDATE concepts SET name = 'Dodatky' WHERE LanguageTag = 'extras'
UPDATE concepts SET description = 'Ďalšie hodiny pre zmluvy na čiastočný úväzok.' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET name = 'Doplnkové hodiny' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET description = 'Plánovaný čas, to je čas, ktorý musím venovať rozvrhom' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET name = 'Plánovaný čas' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET description = 'Celý čas, ktorý sa považuje za efektívnu prácu, okrem nadčasov.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Efektívna práca' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'Dovolenka v predchádzajúcom roku' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET name = 'Dovolenka v predchádzajúcom roku' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET description = 'Tento zostatok zobrazuje nevyčerpanú dovolenku, ktorá sa má vyčerpať.   Počiatočný zostatok dovolenky - vyčerpaná dovolenka = nevyčerpaná dovolenka' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Dovolenka v očakávaní' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'Moja spoločnosť' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'Všeobecné pravidlá' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'Dovolenka za predchádzajúci rok' WHERE LanguageTag = 'periododisfrutevacacionesañoanterior'
UPDATE requestsrules SET name = 'Záporný zostatok dovolenky' WHERE LanguageTag = 'saldonegativovacaciones'
UPDATE shifts SET description = 'Nezabudnite, že tento rozvrh si môžete pri plánovaní prispôsobiť, umožňuje vám priradiť čas vstupu, počet bežných aj doplnkových hodín.  V tomto príklade len jeden časový interval.  ' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET name = 'Joker 1 pruh' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET description = 'Nezabudnite, že tento rozvrh si môžete pri plánovaní prispôsobiť, umožňuje vám priradiť čas vstupu, počet bežných aj doplnkových hodín.  V tomto príklade dva časové intervaly.  ' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET name = 'Joker 2 pruhy' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET description = 'Tento rozvrh je užitočný len v prípadoch, keď chcete len zaznamenať pracovný deň (aby ste vyhoveli predpisom) a nechcete vykonávať žiadny druh riadenia času.  ' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET name = 'Hodinomer' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET description = 'Tento rozvrh má 0 plánovaných hodín. Plánuje sa len v dňoch, keď má zamestnanec celý voľný deň, a preto nebude mať hodiny.  ' WHERE LanguageTag = 'descanso'
UPDATE shifts SET name = 'zvyšok' WHERE LanguageTag = 'descanso'
UPDATE shifts SET description = 'Tento rozvrh má 0 plánovaných hodín. Plánuje sa len na dni, v ktorých má zamestnanec sviatok, a preto nebude mať hodiny.' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Slávnostné' WHERE LanguageTag = 'festivo'
UPDATE shifts SET description = 'Ide o úplne flexibilný rozvrh. Zamestnanec môže voľne prichádzať a odchádzať v čase od 6:00 do 23:00 a bude sledovaný len vtedy, ak odpracuje viac alebo menej ako plánovaných 8 hodín.  ' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET name = 'Flexibilný 8h' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET description = 'Príklad pevných úradných hodín (povinné hodiny), so začiatkom o 8:00 a koncom o 14:00 a so začiatkom o 15:00 a koncom o 17:00, nezabudnite si na prestávky zapísať a vypísať hodiny.  ' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET name = 'Kancelárska párty' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET description = 'Príklad intenzívneho rozvrhu (povinné hodiny) so začiatkom o 6:00 a odchodom o 14:00.  ' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET name = 'Výrobná zmena 6 až 14' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET description = 'Sviatky v pracovných dňoch.  ' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Dovolenka' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET description = 'Dovolenka v predchádzajúcom roku.  ' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE shifts SET name = 'Dovolenka v predchádzajúcom roku' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE startupvalues SET name = 'Počiatočné prázdniny' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = 'Dni ročnej dovolenky' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'Hodiny' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Zmiešané (hodiny+výskyt)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Výskyt' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Uistite sa, koľko zostáva z prepočtu VisualTime a koľkých zamestnancov sa to týka' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Uistite sa, koľko zostáva z prepočtu VisualTime a koľkých zamestnancov sa to týka' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Skontrolujte skupinu, do ktorej zamestnanci patria. Krátka a úplná trasa' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Skontrolujte skupinu, do ktorej zamestnanci patria. Krátka a úplná trasa' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Skontrolujte, či existuje úloha, ktorú nebolo možné normálne vykonať' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Skontrolujte, či existuje úloha, ktorú nebolo možné normálne vykonať' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Skontrolujte, či prepočet po zmenách vykonaných v aplikácii VisualTime funguje správne' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Skontrolujte, či prepočet po zmenách vykonaných v aplikácii VisualTime funguje správne' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Zobrazuje oprávnenia rôznych nadriadených na čakajúce žiadosti vrátane toho, či je nadriadený pre každú žiadosť priamy alebo nie' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET name = 'Povolenia v rámci nevybavených žiadostí' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET description = 'Ak chcete zistiť, či je korelačný súbor správne vložený do databázy' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'Ak chcete zistiť, či je korelačný súbor správne vložený do databázy' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'Pozrite si podpisy, ktoré sa uskutočnili v určitý deň (dátum si môžete vybrať)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'Pozrite si podpisy, ktoré sa uskutočnili v určitý deň (dátum si môžete vybrať)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'Zobrazenie čakajúcich úloh zavesených na termináloch po vysielaní' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'Zobrazenie čakajúcich úloh zavesených na termináloch po vysielaní' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Správa o absencii' WHERE LanguageTag = 'informedeabsentismo'
UPDATE sysroreportgroups SET name = 'Bilančná správa' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Vynikajúca správa o dovolenke' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysroreportgroups SET name = 'Všeobecná správa' WHERE LanguageTag = 'informegeneral'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Profesionálna kategória' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Administratívni asistenti~asistenti s vysokoškolským vzdelaním~technickí inžinieri, experti a asistenti s vysokoškolským vzdelaním~inžinieri a absolventi~administratívni pracovníci a vedúci dielní~administratívni úradníci~úradníci prvej a druhej triedy~úradníci tretej triedy a špecialisti~pionieri~podpôradní pracovníci~pracovníci mladší ako 18 rokov' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Poštové smerovacie číslo' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Ročné príplatky k platu' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'E-mailová adresa' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'Náklady na ľudské zdroje' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Náklady na hodinu' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET fieldname = 'Dni ročnej dovolenky' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET category = 'Zamestnanci' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Dátum narodenia' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Pohlavie' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Muž~Žena' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Skupina príspevkov' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET fieldname = 'ID používateľa' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Import Id' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET fieldname = 'Dôvod odchodu' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Dobrovoľná dovolenka~Dobrovoľné prepustenie~Dočasné ukončenie zmluvy~Invalidita~Invalidita~Dôchodok~Z dôvodov dohodnutých v zmluve' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Mobilný portál' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Zamestnanci' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Štátna príslušnosť' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Zamestnanci' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'NIF' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Núdzové číslo' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Poznámky' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Platby mimo mzdy' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Mimoriadne a dodatočné platby' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Obyvateľstvo' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Hodinová sadzba' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Provincia' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'pošta' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Miesto stretnutia' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Základný ročný plat' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Celkový ročný plat' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Telefón' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Typ zmluvy' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'Stážista~Na dobu neurčitú~Dočasne' WHERE LanguageTag = 'tipodecontrato'
UPDATE timezones SET name = 'Hodiny s osobitnou odmenou' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Nočné hodiny' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Bežné hodiny' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Neprítomný' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Súčasnosť' WHERE LanguageTag = 'presentes'
GO
