UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'FRA') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 heures sur 24 toute l''année' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 h Total' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'La chasse au trésor pendant les vacances' WHERE LanguageTag = 'arrastrevacaciones'
UPDATE causes SET name = 'Congé de maladie accident du travail' WHERE LanguageTag = 'bajaaccidentelaboral'
UPDATE causes SET name = 'Congé de maladie maladie ordinaire/action non professionnelle' WHERE LanguageTag = 'bajaenfermedadcomunaccnolaboral'
UPDATE causes SET description = 'Ceux qui dépassent les heures normales de la journée de travail mais dont l''exécution a été convenue dans le cadre d''un contrat à temps partiel. Ils peuvent être de deux types : -Heures convenues : contrats à temps partiel dont la journée de travail n''est pas inférieure à dix heures par semaine sur une base annuelle. -Heures volontaires : contrats à temps partiel à durée indéterminée dont la durée de travail n''est pas inférieure à 10 heures par semaine sur une base annuelle.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'heures complémentaires' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Heures de travail effectuées au-delà de la durée maximale de la journée de travail ordinaire fixée par la loi ou par convention.  Un maximum de 80 heures de ce type peut être effectué par an.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = 'Heures supplémentaires' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Visite chez le médecin' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Médecin' WHERE LanguageTag = 'medico'
UPDATE causes SET description = 'Il s''agit d''un congé qui peut être pris pour n''importe quelle raison, sauf si la convention applicable en dispose autrement et s''il existe un accord entre l''employeur et le salarié. Il suspend l''obligation de travailler et de verser le salaire correspondant à la durée de l''absence. Elles ne sont pas réglementées par la loi (sauf dans certaines conventions collectives). Les conditions d''utilisation et de jouissance de ces congés sont régies par des accords entre l''employeur et l''employé.' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = 'Congé légal non rémunéré' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'Le congé payé est un type d''absence pendant lequel le travailleur continue d''être rémunéré. Les congés payés sont régis par l''article 37 du statut des travailleurs et par les conventions collectives.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Congé légal payé' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'Le temps pendant lequel le travail est effectué principalement au domicile du travailleur ou à un endroit librement choisi par le travailleur, au lieu d''être effectué en personne sur le lieu de travail de l''entreprise.' WHERE LanguageTag = 'teletrabajo'
UPDATE causes SET name = 'Télétravail' WHERE LanguageTag = 'teletrabajo'
UPDATE causes SET description = 'Il s''agit de moments qui ne sont pas autorisés par l''entreprise ou qui ne veulent pas être traités de manière positive ou négative.' WHERE LanguageTag = 'tiempodeexcesonojustificado'
UPDATE causes SET name = 'Temps excédentaire non excusé' WHERE LanguageTag = 'tiempodeexcesonojustificado'
UPDATE causes SET description = 'Temps planifié qui n''a pas été travaillé et qui doit être rattrapé à un autre moment.' WHERE LanguageTag = 'tiempoporrecuperar'
UPDATE causes SET name = 'Temps de récupération' WHERE LanguageTag = 'tiempoporrecuperar'
UPDATE causes SET description = 'Les heures positives qui sont effectuées pour compenser les heures négatives qui peuvent être effectuées.' WHERE LanguageTag = 'tiemporecuperado'
UPDATE causes SET name = 'Temps récupéré' WHERE LanguageTag = 'tiemporecuperado'
UPDATE causes SET description = 'Les heures qui ont été planifiées pour l''employé et qui doivent être effectuées par lui. Justification VisualTime interne, à ne pas supprimer ou modifier.' WHERE LanguageTag = 'tiempoteorico'
UPDATE causes SET name = 'Durée théorique' WHERE LanguageTag = 'tiempoteorico'
UPDATE causes SET description = 'Heures travaillées dans le cadre de l''horaire prévu de l''utilisateur' WHERE LanguageTag = 'trabajoefectivo'
UPDATE causes SET name = 'Un travail efficace' WHERE LanguageTag = 'trabajoefectivo'
UPDATE causes SET description = 'Absence due au congé annuel payé. Elle n''est pas remplaçable par une compensation financière ; elle correspondra au montant convenu dans la convention collective ou le contrat individuel. Dans le respect de cet accord, le minimum légal est de 30 jours calendaires par an.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Des vacances' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Absence non excusée qui génère une alerte. L''objectif est qu''il n''y ait pas de temps justifié pour cette raison. Justification VisualTime interne, à ne pas supprimer ou modifier.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. NON JUSTIFIÉ' WHERE LanguageTag = 'vtnojustificado'
UPDATE concepts SET description = 'Ce solde soustrait toutes les "heures à récupérer" et ajoute toutes les "heures récupérées". Si le total de ce solde est négatif, le salarié doit des heures à l''entreprise.  Si le total de ce solde est positif, l''entreprise doit des heures au salarié.' WHERE LanguageTag = 'horas'
UPDATE concepts SET name = 'Heures+/-' WHERE LanguageTag = 'horas'
UPDATE concepts SET description = 'Le temps planifié, c''est le temps que je dois consacrer aux horaires' WHERE LanguageTag = 'tiempoplanificadoteoria'
UPDATE concepts SET name = 'Temps planifié (théorie)' WHERE LanguageTag = 'tiempoplanificadoteoria'
UPDATE concepts SET description = 'Temps d''absence' WHERE LanguageTag = 'totalabsentismo'
UPDATE concepts SET name = 'Absentéisme total' WHERE LanguageTag = 'totalabsentismo'
UPDATE concepts SET description = 'Heures supplémentaires pour les contrats à temps partiel.' WHERE LanguageTag = 'totalhorascomplementarias'
UPDATE concepts SET name = 'Total des heures supplémentaires' WHERE LanguageTag = 'totalhorascomplementarias'
UPDATE concepts SET description = 'Heures supplémentaires.' WHERE LanguageTag = 'totalhorasextras'
UPDATE concepts SET name = 'Total des heures supplémentaires' WHERE LanguageTag = 'totalhorasextras'
UPDATE concepts SET description = 'Tout le temps considéré comme du travail effectif, à l''exclusion des heures supplémentaires.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Un travail efficace' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'Ce solde indique les congés restant à prendre.   Solde initial des congés - congés pris = congés restant à prendre' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Vacances en suspens' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'Mon entreprise' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'Règles générales' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'Ne pas demander de congés s''il n''y a pas de solde positif' WHERE LanguageTag = 'nopedirvacacionessinohaysaldopositivo'
UPDATE shifts SET description = 'Jours fériés, jours chômés.' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'De fête' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Fonctionnement' WHERE LanguageTag = 'laborable'
UPDATE shifts SET description = 'Cet horaire comporte 0 heure planifiée. Il ne doit être planifié que les jours où le salarié a un jour de congé complet et ne pointera donc pas.  ' WHERE LanguageTag = 'nolaboral'
UPDATE shifts SET name = 'Non professionnel' WHERE LanguageTag = 'nolaboral'
UPDATE shifts SET description = 'Jours fériés pendant les jours ouvrables.  ' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Des vacances' WHERE LanguageTag = 'vacaciones'
UPDATE startupvalues SET name = 'Des vacances' WHERE LanguageTag = 'vacaciones'
UPDATE startupvalues SET name = 'Vacances initiales' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = '0' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'Heures' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Mixte (heures+occurrences)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Occurrences' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Assurez-vous de la durée restante du recalcul de VisualTime et du nombre d''employés concernés' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Assurez-vous de la durée restante du recalcul de VisualTime' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Vérifier le groupe auquel appartiennent les employés. Itinéraire court et complet' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Vérifier le groupe auquel appartiennent les employés. Itinéraire court et complet' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Vérifier qu''une tâche n''a pas pu être exécutée normalement' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Vérifier qu''une tâche n''a pas pu être exécutée normalement' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Vérifier si le client a l''AMP' WHERE LanguageTag = 'comprobarsiclientetienegpa'
UPDATE sysroqueries SET name = 'Vérifier si le client a l''AMP' WHERE LanguageTag = 'comprobarsiclientetienegpa'
UPDATE sysroqueries SET description = 'Vérifier si le recalcul après les changements effectués dans VisualTime fonctionne correctement' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Vérifier si le recalcul après les changements effectués dans VisualTime fonctionne correctement' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Mustra les permissions des superviseurs dans V2' WHERE LanguageTag = 'permisosefectivos'
UPDATE sysroqueries SET name = 'Congé effectif' WHERE LanguageTag = 'permisosefectivos'
UPDATE sysroqueries SET description = 'Affiche les permissions sur les fonctionnalités de l''employé et du calendrier des superviseurs dans la V2 sur les employés' WHERE LanguageTag = 'permisosefectivossobrefuncionalidadesconcretas'
UPDATE sysroqueries SET name = 'Permissions effectives sur des fonctionnalités spécifiques' WHERE LanguageTag = 'permisosefectivossobrefuncionalidadesconcretas'
UPDATE sysroqueries SET description = 'Pour savoir si le fichier de corrélation est correctement introduit dans la base de données' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'Pour savoir si le fichier de corrélation est correctement introduit dans la base de données' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'Savoir si des rapports planifiés sont en cours d''exécution' WHERE LanguageTag = 'sabersihayalguninformeplanificadoejecutandose'
UPDATE sysroqueries SET name = 'Savoir si des rapports planifiés sont en cours d''exécution' WHERE LanguageTag = 'sabersihayalguninformeplanificadoejecutandose'
UPDATE sysroqueries SET description = 'Voir les signatures qui ont eu lieu à une date précise (vous pouvez choisir la date)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'Voir les signatures qui ont eu lieu à une date précise (vous pouvez choisir la date)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'Affichage des tâches en suspens sur les terminaux après la diffusion' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'Affichage des tâches en suspens sur les terminaux après la diffusion' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Rapport d''équilibre' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Un rapport de vacances exceptionnel' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Catégorie professionnelle' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Assistants administratifs~Assistants diplômés~Ingénieurs techniques, experts et assistants diplômés~Ingénieurs et diplômés~Chefs d''administration et d''atelier~Officiers administratifs~Officiers de première et de deuxième classe~Officiers de troisième classe et spécialistes~Peons~Subalternes~Travailleurs de moins de 18 ans' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Code postal' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Primes annuelles' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'Courrier électronique' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'Coût RH' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Coût par heure' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'Personnel' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Date de naissance' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Sexe' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Homme~Femme' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Groupe de cotisation' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'identifiant d''importation' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Raison du départ' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Congé volontaire~Licenciement~Licenciement~Rupture temporaire du contrat~Invalidité~Retraite~Pour des raisons convenues dans le contrat' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Portable' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Personnel' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Nationalité' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Personnel' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'NIF' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Numéro d´urgence' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Remarques' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Revenus non-salariaux' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Revenus d’heures supplémentaires' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Ville' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Prix par heure' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Région' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'Poste' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Point de REUNION' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Salaire, base annuelle' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Salaire total annuel' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Téléphone' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Type de contrat' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'Stagiaire~Indefini~Temporaire' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'valorinicialdevacaciones'
UPDATE sysrouserfields SET fieldname = 'Valeur initiale des vacances' WHERE LanguageTag = 'valorinicialdevacaciones'
UPDATE timezones SET name = 'Heures avec rémunération spéciale' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Heures de nuit' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Heures normales' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Absents' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Présent' WHERE LanguageTag = 'presentes'
GO