UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'FRA') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 heures sur 24 toute l''année' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 h Total' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'La chasse au trésor des vacances' WHERE LanguageTag = 'arrastredevacaciones'
UPDATE accrualsrules SET description = 'Les congés de l''année précédente peuvent être pris jusqu''au 31/1 de l''année en cours. S''ils n''ont pas été pris, ils sont perdus (ils expirent).' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE accrualsrules SET name = 'Expiration des congés de l''année précédente' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE causelimitvalues SET name = 'Limite de 80 heures pour le paiement des heures supplémentaires' WHERE LanguageTag = 'limitede80horasextrasapagar'
UPDATE causes SET description = 'Congé ATEP' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET name = 'Congé ATEP' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET description = 'Faible CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET name = 'Faible CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET description = 'Fonctions inexcusables, de nature publique et/ou personnelle' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET name = 'Fonctions inexcusables, de nature publique et/ou personnelle' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET description = 'Examens officiels' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET name = 'Examens officiels' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET description = 'Examens prénataux et techniques de préparation à l''accouchement' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET name = 'Examens prénataux et techniques de préparation à l''accouchement' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET description = 'Ceux qui dépassent les heures normales de la journée de travail mais dont l''exécution a été convenue dans le cadre d''un contrat à temps partiel. Ils peuvent être de deux types : -Heures convenues : contrats à temps partiel dont la journée de travail n''est pas inférieure à dix heures par semaine sur une base annuelle. -Heures volontaires : contrats à temps partiel à durée indéterminée dont la durée de travail n''est pas inférieure à 10 heures par semaine sur une base annuelle.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'heures complémentaires' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Heures de travail effectuées au-delà de la durée maximale de la journée de travail ordinaire fixée par la loi ou par convention.  Un maximum de 80 heures de ce type peut être effectué par an.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = 'Heures supplémentaires' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Les heures travaillées dans les limites de l''horaire de travail prévu du salarié.' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET name = 'Heures normales' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET description = 'Temps planifié qui n''a pas été travaillé et qui doit être rattrapé à un autre moment.' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET name = 'Heures à rattraper' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET description = 'Les heures positives qui sont faites pour compenser les heures négatives qui peuvent être faites, conviennent aux entreprises qui font preuve de flexibilité.' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET name = 'Heures récupérées' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET description = 'L''allaitement' WHERE LanguageTag = 'lactancia'
UPDATE causes SET name = 'L''allaitement' WHERE LanguageTag = 'lactancia'
UPDATE causes SET description = 'Maternité/Paternité' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET name = 'Maternité/Paternité' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET description = 'Mariage familial' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET name = 'Mariage familial' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET description = 'Propre mariage' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET name = 'Propre mariage' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET description = 'Médecin' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Médecin' WHERE LanguageTag = 'medico'
UPDATE causes SET description = 'Naissance de l''enfant' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET name = 'Naissance de l''enfant' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET description = 'Congé de force majeure' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET name = 'Congé de force majeure' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET description = '8 semaines de congé parental' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET name = '8 semaines de congé parental' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET description = 'Congé pour s''occuper d''un parent au deuxième degré ou d''un partenaire cohabitant' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET name = 'Congé pour s''occuper d''un parent au deuxième degré ou d''un partenaire cohabitant' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET description = 'Il s''agit d''un congé qui peut être pris pour n''importe quelle raison, sauf si la convention applicable en dispose autrement et s''il existe un accord entre l''employeur et le salarié. Il suspend l''obligation de travailler et de verser le salaire correspondant à la durée de l''absence. Elles ne sont pas réglementées par la loi (sauf dans certaines conventions collectives). Les conditions d''utilisation et de jouissance de ces congés sont régies par des accords entre l''employeur et l''employé.' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = 'Congé légal non rémunéré' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'Le congé payé est un type d''absence pendant lequel le travailleur continue d''être rémunéré. Les congés payés sont régis par l''article 37 du statut des travailleurs et par les conventions collectives.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Congé légal payé' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'Déménagement du lieu de résidence habituelle' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET name = 'Déménagement du lieu de résidence habituelle' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET description = 'Absence due au congé annuel payé. Elle n''est pas remplaçable par une compensation financière ; elle correspondra au montant convenu dans la convention collective ou le contrat individuel. Dans le respect de cet accord, le minimum légal est de 30 jours calendaires par an.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Des vacances' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Vacances de l''année précédente.' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET name = 'Vacances de l''année précédente' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET description = 'VT. Vacances au chalut' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET name = 'VT. Vacances au chalut' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET description = 'VT. Expiration des vacances' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET name = 'VT. Expiration des vacances' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET description = 'Les heures qui ont été planifiées pour l''employé et qui doivent être effectuées par lui. Justification VisualTime interne, à ne pas supprimer ou modifier.' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET name = 'VT. Heures théoriques' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET description = 'Absence non excusée qui génère une alerte. L''objectif est qu''il n''y ait pas de temps justifié pour cette raison. Justification VisualTime interne, à ne pas supprimer ou modifier.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. NON JUSTIFIÉ' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET description = 'VT. Dépassement de temps non autorisé' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE causes SET name = 'VT. Dépassement de temps non autorisé' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE concepts SET description = 'Temps d''absence excusé mais non rémunéré.' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET name = 'Absentéisme non rémunéré' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET description = 'Des congés payés et excusés.' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET name = 'Absentéisme rémunéré' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET description = 'Ce solde soustrait toutes les "heures à récupérer" et ajoute toutes les "heures récupérées". Si le total de ce solde est négatif, le salarié doit des heures à l''entreprise.  Si le total de ce solde est positif, l''entreprise doit des heures au salarié.' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET name = 'Solde d''heures' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET description = 'Heures supplémentaires. Maximum 80 heures par an.' WHERE LanguageTag = 'extras'
UPDATE concepts SET name = 'Extras' WHERE LanguageTag = 'extras'
UPDATE concepts SET description = 'Heures supplémentaires pour les contrats à temps partiel.' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET name = 'Heures complémentaires' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET description = 'Le temps planifié, c''est le temps que je dois consacrer aux horaires' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET name = 'Temps prévu' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET description = 'Tout le temps considéré comme du travail effectif, à l''exclusion des heures supplémentaires.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Un travail efficace' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'Vacances de l''année précédente' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET name = 'Vacances de l''année précédente' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET description = 'Ce solde indique les congés restant à prendre.   Solde initial des congés - congés pris = congés restant à prendre' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Vacances en suspens' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'Mon entreprise' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'Règles générales' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'Période de congés de l''année précédente' WHERE LanguageTag = 'periododisfrutevacacionesañoanterior'
UPDATE requestsrules SET name = 'Solde négatif des congés' WHERE LanguageTag = 'saldonegativovacaciones'
UPDATE shifts SET description = 'N''oubliez pas que vous pouvez adapter cet horaire lorsque vous le planifiez, il vous permet d''attribuer une heure d''entrée, un nombre d''heures ordinaires et complémentaires.  Dans cet exemple, une seule plage horaire.  ' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET name = 'Joker 1 bande' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET description = 'N''oubliez pas que vous pouvez adapter cet horaire lorsque vous le planifiez, il vous permet d''attribuer une heure d''entrée, un nombre d''heures ordinaires et complémentaires.  Dans cet exemple, deux créneaux horaires.  ' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET name = 'Joker 2 bandes' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET description = 'Cet horaire n''est utile que dans les cas où l''on souhaite uniquement enregistrer la journée de travail (pour se conformer à la réglementation) et où l''on ne souhaite pas procéder à une quelconque gestion du temps.  ' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET name = 'Compteur horaire' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET description = 'Cet horaire comporte 0 heure planifiée. Il ne doit être planifié que les jours où le salarié a un jour de congé complet et ne pointera donc pas.  ' WHERE LanguageTag = 'descanso'
UPDATE shifts SET name = 'pause' WHERE LanguageTag = 'descanso'
UPDATE shifts SET description = 'Cet horaire comporte 0 heure planifiée. Il ne sera planifié que pour les jours où le salarié a un jour férié et ne pointera donc pas.' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'De fête' WHERE LanguageTag = 'festivo'
UPDATE shifts SET description = 'Il s''agit d''un horaire totalement flexible. L''employé peut librement pointer entre 6h00 et 23h00 et ne sera contrôlé que s''il fait plus ou moins que les 8 heures prévues.  ' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET name = 'Flexible 8h' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET description = 'Exemple d''horaires de bureau rigides (heures obligatoires), avec une heure de début de 8h00 et une heure de fin de 14h00 et une heure de début de 15h00 et une heure de fin de 17h00, n''oubliez pas de pointer pour vos pauses.  ' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET name = 'Fête de bureau' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET description = 'Exemple d''horaire intensif (heures obligatoires), avec une heure de début à 6h00 et une heure de départ à 14h00.  ' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET name = 'Équipe de production 6 à 14' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET description = 'Jours fériés pendant les jours ouvrables.  ' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Des vacances' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET description = 'Vacances de l''année précédente.  ' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE shifts SET name = 'Vacances de l''année précédente' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE startupvalues SET name = 'Vacances initiales' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = 'Jours de congé annuel' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'Heures' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Mixte (heures+occurrences)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Occurrences' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Assurez-vous de la durée restante du recalcul de VisualTime et du nombre d''employés concernés' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Assurez-vous de la durée restante du recalcul de VisualTime et du nombre d''employés concernés' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Vérifier le groupe auquel appartiennent les employés. Itinéraire court et complet' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Vérifier le groupe auquel appartiennent les employés. Itinéraire court et complet' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Vérifier qu''une tâche n''a pas pu être exécutée normalement' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Vérifier qu''une tâche n''a pas pu être exécutée normalement' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Vérifier si le recalcul après les changements effectués dans VisualTime fonctionne correctement' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Vérifier si le recalcul après les changements effectués dans VisualTime fonctionne correctement' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Affiche les autorisations des différents superviseurs sur les demandes en attente, y compris si le superviseur est direct ou non pour chaque demande' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET name = 'Permis pour les demandes en cours d''examen' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET description = 'Pour savoir si le fichier de corrélation est correctement introduit dans la base de données' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'Pour savoir si le fichier de corrélation est correctement introduit dans la base de données' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'Voir les signatures qui ont eu lieu à une date précise (vous pouvez choisir la date)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'Voir les signatures qui ont eu lieu à une date précise (vous pouvez choisir la date)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'Affichage des tâches en suspens sur les terminaux après la diffusion' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'Affichage des tâches en suspens sur les terminaux après la diffusion' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Rapport sur l''absentéisme' WHERE LanguageTag = 'informedeabsentismo'
UPDATE sysroreportgroups SET name = 'Rapport d''équilibre' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Un rapport de vacances exceptionnel' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysroreportgroups SET name = 'Rapport général' WHERE LanguageTag = 'informegeneral'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Catégorie professionnelle' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Assistants administratifs~Assistants diplômés~Ingénieurs techniques, experts et assistants diplômés~Ingénieurs et diplômés~Chefs d''administration et d''atelier~Officiers administratifs~Officiers de première et de deuxième classe~Officiers de troisième classe et spécialistes~Peons~Subalternes~Travailleurs de moins de 18 ans' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Code postal' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Primes annuelles' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'Courrier électronique' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'Coût RH' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Coût par heure' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET fieldname = 'Jours de congé annuel' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET category = 'Personnel' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Date de naissance' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Sexe' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Homme~Femme' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Groupe de cotisation' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET fieldname = 'Identifiant de l''utilisateur' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'identifiant d''importation' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET fieldname = 'Raison du départ' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Congé volontaire~Licenciement~Licenciement~Rupture temporaire du contrat~Invalidité~Retraite~Pour des raisons convenues dans le contrat' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Portable' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Personnel' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Nationalité' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Personnel' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'NIF' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Numéro d´urgence' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Remarques' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Revenus non-salariaux' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Revenus d’heures supplémentaires' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Ville' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Prix par heure' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Région' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'Poste' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Point de REUNION' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Salaire, base annuelle' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Salaire total annuel' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Téléphone' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Professionnel' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Type de contrat' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'Stagiaire~Indefini~Temporaire' WHERE LanguageTag = 'tipodecontrato'
UPDATE timezones SET name = 'Heures avec rémunération spéciale' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Heures de nuit' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Heures normales' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Absents' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Présent' WHERE LanguageTag = 'presentes'
GO