UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'ITA') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 ore su 24 tutto l''anno' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 ore Totale' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'Vacanze a strascico' WHERE LanguageTag = 'arrastrevacaciones'
UPDATE causes SET name = 'Congedo di malattia per infortunio sul lavoro' WHERE LanguageTag = 'bajaaccidentelaboral'
UPDATE causes SET name = 'Congedo per malattia comune/azione non professionale' WHERE LanguageTag = 'bajaenfermedadcomunaccnolaboral'
UPDATE causes SET description = 'Quelli che eccedono l''orario ordinario della giornata lavorativa, ma la cui prestazione è stata concordata e stabilita in un contratto part-time. Possono essere di 2 tipi: -Orario concordato: contratti a tempo parziale con una giornata lavorativa non inferiore a dieci ore settimanali su base annua. -Orario volontario: contratti part-time a tempo indeterminato con una giornata lavorativa non inferiore a 10 ore settimanali su base annua.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'ore complementari' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Ore di lavoro svolte oltre la durata massima della giornata lavorativa ordinaria stabilita per legge o per accordo.  Questo tipo di lavoro può essere svolto per un massimo di 80 ore all''anno.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = 'Lavoro straordinario' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Visita medica' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Il medico' WHERE LanguageTag = 'medico'
UPDATE causes SET description = 'Si tratta di un congedo che può essere preso per qualsiasi motivo, a meno che il contratto applicabile non specifichi diversamente e vi sia un accordo tra datore di lavoro e dipendente. Sospende l''obbligo di lavorare e di pagare la retribuzione corrispondente al periodo di assenza del dipendente. Non sono regolati dalla legge (tranne che in alcuni contratti collettivi). Le condizioni di utilizzo e di godimento di questi permessi/permessi sono regolate da accordi tra datore di lavoro e dipendente.' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = 'Congedo obbligatorio non retribuito' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'Il congedo retribuito è un tipo di assenza durante la quale il lavoratore continuerà a essere compensato economicamente. I permessi retribuiti sono disciplinati dall''articolo 37 dello Statuto dei lavoratori e dai contratti collettivi.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Congedo legale retribuito' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'Il tempo durante il quale il lavoro viene svolto prevalentemente al domicilio del lavoratore o in un luogo da lui liberamente scelto, in alternativa allo svolgimento di persona sul luogo di lavoro dell''azienda.' WHERE LanguageTag = 'teletrabajo'
UPDATE causes SET name = 'Telelavoro' WHERE LanguageTag = 'teletrabajo'
UPDATE causes SET description = 'Si tratta di momenti non autorizzati dall''azienda o che non vogliono essere trattati né positivamente né negativamente.' WHERE LanguageTag = 'tiempodeexcesonojustificado'
UPDATE causes SET name = 'Tempo in eccesso non giustificato' WHERE LanguageTag = 'tiempodeexcesonojustificado'
UPDATE causes SET description = 'Tempo pianificato che non è stato lavorato e che deve essere recuperato in un altro momento.' WHERE LanguageTag = 'tiempoporrecuperar'
UPDATE causes SET name = 'Tempo di recupero' WHERE LanguageTag = 'tiempoporrecuperar'
UPDATE causes SET description = 'Ore positive che vengono effettuate per compensare le ore negative che possono essere effettuate.' WHERE LanguageTag = 'tiemporecuperado'
UPDATE causes SET name = 'Tempo recuperato' WHERE LanguageTag = 'tiemporecuperado'
UPDATE causes SET description = 'Le ore che sono state pianificate per il dipendente e che devono essere svolte da quest''ultimo. Giustificazione interna di VisualTime, da non cancellare o modificare.' WHERE LanguageTag = 'tiempoteorico'
UPDATE causes SET name = 'Tempo teorico' WHERE LanguageTag = 'tiempoteorico'
UPDATE causes SET description = 'Ore lavorate nell''ambito dell''orario programmato dall''utente' WHERE LanguageTag = 'trabajoefectivo'
UPDATE causes SET name = 'Lavoro efficace' WHERE LanguageTag = 'trabajoefectivo'
UPDATE causes SET description = 'Assenza dovuta a ferie annuali retribuite. Non è sostituibile da una compensazione economica; sarà l''importo concordato nel Contratto Collettivo o nel contratto individuale. Nel rispetto di questo accordo il minimo legale è di 30 giorni di calendario all''anno.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Vacanza' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Assenza ingiustificata che genera un avviso. L''obiettivo è che non ci sia un orario giustificato per questo motivo. Giustificazione interna di VisualTime, da non cancellare o modificare.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. NON GIUSTIFICATO' WHERE LanguageTag = 'vtnojustificado'
UPDATE concepts SET description = 'Questo saldo sottrae tutte le "ore da recuperare" e aggiunge tutte le "ore recuperate". Se il totale di questo saldo è negativo, il dipendente deve delle ore all''azienda.  Se il totale di questo saldo è positivo, l''azienda deve delle ore al dipendente.' WHERE LanguageTag = 'horas'
UPDATE concepts SET name = 'Ore+/-' WHERE LanguageTag = 'horas'
UPDATE concepts SET description = 'Tempo pianificato, questo è il tempo che devo dedicare agli orari' WHERE LanguageTag = 'tiempoplanificadoteoria'
UPDATE concepts SET name = 'Tempo pianificato (teoria)' WHERE LanguageTag = 'tiempoplanificadoteoria'
UPDATE concepts SET description = 'Tempo libero' WHERE LanguageTag = 'totalabsentismo'
UPDATE concepts SET name = 'Assenteismo totale' WHERE LanguageTag = 'totalabsentismo'
UPDATE concepts SET description = 'Ore aggiuntive per contratti part-time.' WHERE LanguageTag = 'totalhorascomplementarias'
UPDATE concepts SET name = 'Totale ore aggiuntive' WHERE LanguageTag = 'totalhorascomplementarias'
UPDATE concepts SET description = 'Straordinari.' WHERE LanguageTag = 'totalhorasextras'
UPDATE concepts SET name = 'Totale ore di lavoro straordinario' WHERE LanguageTag = 'totalhorasextras'
UPDATE concepts SET description = 'Tutto il tempo che viene considerato lavoro effettivo, esclusi gli straordinari.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Lavoro efficace' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'Questo saldo indica le ferie ancora da prendere.   Saldo iniziale delle ferie - ferie godute = ferie arretrate' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Vacanze in attesa' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'La mia azienda' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'Regole generali' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'Non chiedete ferie se non c''è un saldo attivo' WHERE LanguageTag = 'nopedirvacacionessinohaysaldopositivo'
UPDATE shifts SET description = 'Ferie, giorni non lavorativi.' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Festivo' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Lavorando' WHERE LanguageTag = 'laborable'
UPDATE shifts SET description = 'Questo orario ha 0 ore pianificate. Deve essere pianificato solo nei giorni in cui il dipendente ha un''intera giornata libera e quindi non timbra il cartellino.  ' WHERE LanguageTag = 'nolaboral'
UPDATE shifts SET name = 'Non professionale' WHERE LanguageTag = 'nolaboral'
UPDATE shifts SET description = 'Ferie nei giorni lavorativi.  ' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Vacanza' WHERE LanguageTag = 'vacaciones'
UPDATE startupvalues SET name = 'Vacanza' WHERE LanguageTag = 'vacaciones'
UPDATE startupvalues SET name = 'Vacanze iniziali' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = '0' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'ore' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Misto (ore+occorrenze)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Occorrenze' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Accertarsi di quanto sia rimasto del ricalcolo di VisualTime e di quanti dipendenti siano interessati' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Accertarsi di quanto sia rimasto del ricalcolo di VisualTime' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Controllare il gruppo di appartenenza dei dipendenti. Percorso breve e completo' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Controllare il gruppo di appartenenza dei dipendenti. Percorso breve e completo' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Verificare se c''è un''attività che non può essere eseguita normalmente' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Verificare se c''è un''attività che non può essere eseguita normalmente' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Controllare se il cliente ha l''AAP' WHERE LanguageTag = 'comprobarsiclientetienegpa'
UPDATE sysroqueries SET name = 'Controllare se il cliente ha l''AAP' WHERE LanguageTag = 'comprobarsiclientetienegpa'
UPDATE sysroqueries SET description = 'Controllare se il ricalcolo dopo le modifiche apportate in VisualTime funziona correttamente' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Controllare se il ricalcolo dopo le modifiche apportate in VisualTime funziona correttamente' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Mustra le autorizzazioni dei supervisori in V2' WHERE LanguageTag = 'permisosefectivos'
UPDATE sysroqueries SET name = 'Congedo effettivo' WHERE LanguageTag = 'permisosefectivos'
UPDATE sysroqueries SET description = 'Visualizza le autorizzazioni per i dipendenti e le funzionalità del calendario dei supervisori in V2 sui dipendenti' WHERE LanguageTag = 'permisosefectivossobrefuncionalidadesconcretas'
UPDATE sysroqueries SET name = 'Autorizzazioni efficaci su funzionalità specifiche' WHERE LanguageTag = 'permisosefectivossobrefuncionalidadesconcretas'
UPDATE sysroqueries SET description = 'Per sapere se il file di correlazione è stato inserito correttamente nel database' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'Per sapere se il file di correlazione è stato inserito correttamente nel database' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'Sapere se sono in corso di esecuzione rapporti pianificati' WHERE LanguageTag = 'sabersihayalguninformeplanificadoejecutandose'
UPDATE sysroqueries SET name = 'Sapere se sono in corso di esecuzione rapporti pianificati' WHERE LanguageTag = 'sabersihayalguninformeplanificadoejecutandose'
UPDATE sysroqueries SET description = 'Vedere le firme che hanno avuto luogo in una data specifica (è possibile scegliere la data)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'Vedere le firme che hanno avuto luogo in una data specifica (è possibile scegliere la data)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'Visualizzazione dei compiti in sospeso appesi ai terminali dopo la trasmissione' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'Visualizzazione dei compiti in sospeso appesi ai terminali dopo la trasmissione' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Rapporto di bilancio' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Eccezionale relazione sulle vacanze' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Categoria professionale' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Assistenti amministrativi~Assistenti non laureati~Ingegneri tecnici, periti e assistenti laureati~Ingegneri e laureati~Responsabili amministrativi e di officina~Ufficiali amministrativi~Ufficiali di prima e seconda classe~Ufficiali di terza classe e specialisti~Peoni~Subalterni~Lavoratori di età inferiore ai 18 anni' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Codice postale' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Complementi salariali annuali' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'E-mail' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'Costo delle risorse umane' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Costo all´ora' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'Personale' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Data di nascita' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Genere' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Maschio~Femmina' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Gruppo contributivo' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'ID importazione' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Motivo della partenza' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Congedo volontario~Licenziamento~Licenziamento~Temporanea risoluzione del contratto~Inabilità~Invalidità~Pensionamento~Per motivi concordati nel contratto' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Cellulare' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Personale' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Nazionalità' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Personale' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'CF' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Numero di emergenza' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Osservazioni' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Riscossioni extrasalariali' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Riscossioni per straordinari e complementari' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Comune' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Prezzo per ora' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Provincia' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'Post' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Punto d''incontro' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Salario base annuale' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Salario totale annuale' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Telefono' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Tipo di contratto' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'Apprendista~Indefinito~Temporaneo' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET category = 'Lavorativo' WHERE LanguageTag = 'valorinicialdevacaciones'
UPDATE sysrouserfields SET fieldname = 'Valore iniziale della vacanza' WHERE LanguageTag = 'valorinicialdevacaciones'
UPDATE timezones SET name = 'Ore con retribuzione speciale' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Orario notturno' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Orario normale' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Assenti' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Presente' WHERE LanguageTag = 'presentes'
GO