UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'POR') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 horas durante todo o ano' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 h Total' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'Transferência de férias' WHERE LanguageTag = 'arrastredevacaciones'
UPDATE accrualsrules SET description = 'As férias do ano anterior podem ser gozadas até 31/1 do ano em curso. Se não forem gozadas, perdem-se (caducam). ' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE accrualsrules SET name = 'Caducidade das férias do ano anterior' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE causelimitvalues SET name = 'Limite de 80 horas de trabalho suplementar a pagar' WHERE LanguageTag = 'limitede80horasextrasapagar'
UPDATE causes SET description = 'Férias ATEP' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET name = 'Férias ATEP' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET description = 'Férias CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET name = 'Férias CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET description = 'Funções inescusáveis, de carácter público e/ou pessoal' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET name = 'Deveres inescusáveis, de carácter público e/ou pessoal' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET description = 'Exames oficiais' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET name = 'Exames oficiais' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET description = 'Exames pré-natais e técnicas de preparação para o parto' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET name = 'Exames pré-natais e técnicas de preparação para o parto' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET description = 'Aqueles que excedem as horas normais do dia de trabalho, mas cuja prestação foi acordada e convencionada num contrato a tempo parcial. Podem ser de 2 tipos: -Horas acordadas: Contratos a tempo parcial com uma jornada de trabalho não inferior a dez horas por semana, numa base anual. Horas voluntárias: Contratos a tempo parcial de duração indeterminada com um horário de trabalho não inferior a 10 horas por semana numa base anual.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'Horas suplementares ' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Horas trabalhadas para além da duração máxima do dia de trabalho normal estabelecida por lei ou por acordo.  Este tipo de horas pode ser efectuado, no máximo, 80 horas por ano.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = 'Horas extraordinárias ' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Horas prestadas dentro do horário de trabalho do trabalhador.' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET name = 'Horas normais' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET description = 'Tempo previsto que não foi trabalhado e que deve ser compensado noutra altura.' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET name = 'Horas a compensar' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET description = 'Horas positivas que são compensadas para compensar as horas negativas que podem ser trabalhadas, adequadas para empresas com flexibilidade.' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET name = 'Horas de compensação ' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET description = 'Amamentação' WHERE LanguageTag = 'lactancia'
UPDATE causes SET name = 'Aleitamento materno' WHERE LanguageTag = 'lactancia'
UPDATE causes SET description = 'Maternidade/Paternidade' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET name = 'Maternidade/Paternidade' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET description = 'Casamento familiar' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET name = 'Casamento familiar' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET description = 'Casamento próprio' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET name = 'Casamento próprio' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET description = 'Médico' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Médico' WHERE LanguageTag = 'medico'
UPDATE causes SET description = 'Nascimento da criança' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET name = 'Nascimento de um filho' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET description = 'Licença de força maior' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET name = 'Licença de força maior' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET description = '8 semanas de licença parental' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET name = '8 semanas de licença parental' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET description = 'Licença para assistência a familiares do 2.º grau ou a pessoas que vivam em união de facto' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET name = 'Licença para assistência a familiares de 2.º grau ou a pessoas que vivam em união de facto' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET description = 'Esta licença pode ser gozada por qualquer motivo, exceto se a convenção aplicável dispuser em contrário e se existir um acordo entre a entidade patronal e o trabalhador. Suspende a obrigação de trabalhar e de pagar o salário correspondente ao tempo em que o trabalhador está ausente. Não são reguladas por lei (exceto em algumas convenções colectivas). As condições de utilização e gozo destas licenças/licenças são reguladas por acordos entre a entidade patronal e o trabalhador. ' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = 'Licença legal não remunerada ' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'A licença remunerada é um tipo de ausência durante a qual o trabalhador continua a ser compensado financeiramente. As férias remuneradas são reguladas no artigo 37.º do Estatuto dos Trabalhadores e nas convenções colectivas.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Licença legal remunerada' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'Transferência do local de residência habitual' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET name = 'Transferência do local de residência habitual' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET description = 'Ausência devido a férias anuais remuneradas. Não é substituível por uma compensação financeira, será a acordada na Convenção Colectiva ou no contrato individual. Respeitando este acordo, o mínimo legal de 30 dias de calendário por ano.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Férias' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Feriados do ano anterior. ' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET name = 'Feriados do ano anterior' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET description = 'VT. Feriados de reporte' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET name = 'VT. Feriados de reporte' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET description = 'VT. Transporte de férias' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET name = 'VT. Expiração de férias' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET description = 'As horas que foram planeadas para o trabalhador e que este deve gozar. Justificação interna do VisualTime, que não deve ser eliminada ou modificada.' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET name = 'VT. Horas planeadas' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET description = 'Ausência sem motivo justificado que gera um alerta. O objetivo é que não haja tempo justificado para este motivo. Justificação VisualTime interna, a não apagar ou modificar.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. INEXCUSADO' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET description = 'VT. Excesso de tempo não autorizado' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE causes SET name = 'VT. Excesso de tempo não autorizado' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE concepts SET description = 'Tempo de ausência justificada não remunerada.' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET name = 'Ausência não remunerada' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET description = 'Tempo de ausência justificada e remunerada.' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET name = 'Ausência remunerada' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET description = 'Este saldo deve subtrair todas as “horas a compensar” e adicionar todas as “horas compensadas”. Se o total deste saldo for negativo, o trabalhador deve horas à empresa.  Se o total deste saldo for positivo, a empresa deve horas ao empregado. ' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET name = 'Saldo de horas' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET description = 'Horas extraordinárias. Máximo de 80h por ano.' WHERE LanguageTag = 'extras'
UPDATE concepts SET name = 'Horas extraordinárias ' WHERE LanguageTag = 'extras'
UPDATE concepts SET description = 'Horas suplementares para os contratos a tempo parcial.' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET name = 'Horas complementares' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET description = 'Tempo planeado, é o tempo que tenho de trabalhar de acordo com o horário.' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET name = 'Tempo planeado' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET description = 'Todo o tempo que é considerado como trabalho efetivo, sem contar com as horas extraordinárias.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Trabalho efetivo' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'Férias do ano anterior' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET name = 'Férias do ano anterior' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET description = 'Este saldo mostra as férias pendentes a gozar.   Saldo inicial de férias - férias gozadas = férias a gozar' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Férias pendentes' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'A minha empresa' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'Regras gerais' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'Férias gozadas no ano anterior' WHERE LanguageTag = 'periododisfrutevacacionesañoanterior'
UPDATE requestsrules SET name = 'Saldo negativo de férias' WHERE LanguageTag = 'saldonegativovacaciones'
UPDATE shifts SET description = 'Lembre-se que pode adaptar este horário quando o planear, pois permite-lhe atribuir uma hora de início, o número de horas ordinárias e complementares.  Neste exemplo, apenas uma faixa horária.  ' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET name = 'Faixa horária de 1 curinga' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET description = 'Lembre-se de que pode adaptar este horário quando o planear, pois permite-lhe atribuir uma hora de entrada, número de horas normais e complementares.  Neste exemplo, duas faixas horárias.  ' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET name = 'Faixas horárias curinga 2' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET description = 'Este horário é apenas para os casos em que apenas se pretende registar o dia de trabalho (para cumprir os regulamentos) e não se vai realizar qualquer tipo de gestão de tempo.  ' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET name = 'Contador de horas' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET description = 'Este horário tem 0 horas teóricas. Só está planeado para dias em que o funcionário tem um dia inteiro de folga e, por isso, não é necessário efetuar qualquer marcação de ponto.  ' WHERE LanguageTag = 'descanso'
UPDATE shifts SET name = 'Intervalo' WHERE LanguageTag = 'descanso'
UPDATE shifts SET description = 'Este horário tem 0 horas planeadas. Só deve ser programado para os dias em que o trabalhador tem um feriado e, por isso, não vai marcar o ponto. ' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Férias' WHERE LanguageTag = 'festivo'
UPDATE shifts SET description = 'Este é um horário totalmente flexível. O trabalhador pode entrar e sair livremente entre as 6:00h e as 23:00h e só será monitorizado se trabalhar mais ou menos do que as 8 horas previstas.  ' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET name = '8 horas flexíveis' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET description = 'Exemplo de um horário de escritório rígido (horas obrigatórias), com entrada às 8:00 e saída às 14:00 e entrada às 15:00 e saída às 17:00, não se esqueça de registar as suas pausas.  ' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET name = 'Combinação de escritórios' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET description = 'Exemplo de um horário intensivo (horas obrigatórias), com uma hora de início às 6:00 e uma hora de fim às 14:00.  ' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET name = 'Turno de produção das 6:00 às 14:00' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET description = 'Feriados em dias úteis.  ' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Feriados' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET description = 'Feriados no ano anterior.  ' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE shifts SET name = 'Férias do ano anterior' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE startupvalues SET name = 'Férias iniciais' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = 'Dias de férias anuais' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'Horas' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Misto (horas+ocorrências)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Ocorrências' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Verificar quanto resta do recálculo do VisualTime e quantos trabalhadores são afectados.' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Verifique quanto resta do recálculo do VisualTime e quantos empregados são afectados.' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Verificar o grupo a que pertencem os empregados. Percurso curto e completo' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Verificar o grupo a que pertencem os empregados. Percurso curto e completo' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Verificar se existe alguma tarefa que não tenha podido ser executada normalmente.' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Verificar se existem tarefas que não puderam ser executadas normalmente.' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Verificar se o recálculo após as alterações efectuadas no VisualTime está a funcionar corretamente.' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Verificar se o recálculo após as alterações efectuadas no VisualTime está a funcionar corretamente.' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Mostra as permissões dos diferentes supervisores nos pedidos pendentes, incluindo se o supervisor é ou não direto para cada pedido.' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET name = 'Permissões nos pedidos pendentes' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET description = 'Saber se o ficheiro de correlação está corretamente introduzido na base de dados.' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'Saber se o ficheiro de correlação está corretamente introduzido na base de dados.' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'Ver as marcações de ponto efectuadas numa data específica (pode escolher a data)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'Ver as marcações de ponto que tiveram lugar numa data específica (pode escolher a data)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'Visualizar as tarefas pendentes penduradas nos terminais após a difusão' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'Visualizar as tarefas pendentes penduradas nos terminais após a difusão' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Relatório de ausências' WHERE LanguageTag = 'informedeabsentismo'
UPDATE sysroreportgroups SET name = 'Relatório de saldo' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Relatório de feriados pendentes' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysroreportgroups SET name = 'Relatório geral' WHERE LanguageTag = 'informegeneral'
UPDATE sysrouserfields SET category = 'Trabalho' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Categoria profissional' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Assistentes administrativos~Assistentes não diplomados~Engenheiros técnicos, especialistas e assistentes diplomados~Engenheiros e diplomados~Gestores administrativos e de oficina~Funcionários administrativos~Funcionários de primeira e segunda classe~Funcionários de terceira classe e especialistas~Peões~Subordinados~Trabalhadores com menos de 18 anos' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Código Postal' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Trabalho' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Suplementos ao salário anual' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'Endereço de correio eletrónico' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'Custo RH' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Custo por hora' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET fieldname = 'Dias de férias anuais' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET category = 'Pessoal' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Data de nascimento' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Trabalho' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Género' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Masculino~Feminino' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Trabalhador' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Grupo de contribuição' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET fieldname = 'Identificador do utilizador' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Identificação da importação' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET category = 'Trabalho' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET fieldname = 'Motivo da saída' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Licença voluntária~Despedimento~Despedimento~Termo do contrato temporário~Incapacidade~Invalidez~Reforma~Por motivos acordados no contrato' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Móvel' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Pessoal' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Nacionalidade' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Pessoal' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'NIF' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Número de emergência' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Trabalho' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Observações' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Trabalho' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Pagamentos não salariais' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Trabalho' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Pagamentos extraordinários e complementares' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'População' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'VisualTempo' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Taxa horária' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Província' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Trabalho' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'Correio' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Ponto de encontro' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Emprego' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Salário de base anual' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Trabalho' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Salário anual total' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Telefone' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Trabalho' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Tipo de contrato' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'Estagiário~Indeterminado~Temporário~Temporário' WHERE LanguageTag = 'tipodecontrato'
UPDATE timezones SET name = 'Horário com remuneração especial' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Horário noturno' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Horário normal' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Ausente' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Presente' WHERE LanguageTag = 'presentes'
UPDATE [dbo].[ReportLayouts] SET [Visible] = 1 WHERE LayoutName = N'Mapa de ferias'
GO
