UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'ESP') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 horas todo el año' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 h Total' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'Arrastre de vacaciones' WHERE LanguageTag = 'arrastredevacaciones'
UPDATE accrualsrules SET description = 'Las vacaciones del año anterior se pueden disfrutar hasta el 31/1 del presente año. Si no las han disfrutado , dichas vacaciones se pierden ( caducan). ' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE accrualsrules SET name = 'Caducidad de vacaciones año anterior' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE causelimitvalues SET name = 'Límite de 80 horas extras a pagar' WHERE LanguageTag = 'limitede80horasextrasapagar'
UPDATE causes SET description = 'Baja ATEP' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET name = 'Baja ATEP' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET description = 'Baja CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET name = 'Baja CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET description = 'Deberes inexcusables, de carácter público y/o personal' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET name = 'Deberes inexcusables, de carácter público y/o personal' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET description = 'Exámenes oficiales' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET name = 'Exámenes oficiales' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET description = 'Exámenes prenatales y técnicas de preparación al parto' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET name = 'Exámenes prenatales y técnicas de preparación al parto' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET description = 'Aquéllas que superan las horas ordinarias de la jornada laboral pero cuya realización ha sido pactada y acordada en un contrato a tiempo parcial. Pueden ser de 2 tipos: -Horas pactadas: Contratos a tiempo parcial con una jornada de trabajo no inferior a diez horas semanales en cómputo anual. -Horas voluntarias: Contratos a tiempo parcial de duración indefinida con una jornada de trabajo no inferior a 10 horas semanales en cómputo anual.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'Horas complementarias ' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Horas de trabajo que se realicen sobre la duración máxima de la jornada ordinaria de trabajo fijada, legal o convencionalmente.  Como máximo, se podrán realizar 80h de este tipo al año.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = 'Horas extraordinarias ' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Horas trabajadas dentro del horario planificado al empleado.' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET name = 'Horas ordinarias' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET description = 'El tiempo planificado que no se ha trabajado y debe recuperarse en otro momento.' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET name = 'Horas por recuperar' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET description = 'Horas positivas  que se realizan para compensar horas negativas que puedan realizarse, indicado para empresas con flexibilidad.' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET name = 'Horas recuperadas ' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET description = 'Lactancia' WHERE LanguageTag = 'lactancia'
UPDATE causes SET name = 'Lactancia' WHERE LanguageTag = 'lactancia'
UPDATE causes SET description = 'Maternidad/Paternidad' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET name = 'Maternidad/Paternidad' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET description = 'Matrimonio familiar' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET name = 'Matrimonio familiar' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET description = 'Matrimonio propio' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET name = 'Matrimonio propio' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET description = 'Médico' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Médico' WHERE LanguageTag = 'medico'
UPDATE causes SET description = 'Nacimiento hijo' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET name = 'Nacimiento hijo' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET description = 'Permiso fuerza mayor' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET name = 'Permiso fuerza mayor' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET description = 'Permiso parental de 8 semanas' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET name = 'Permiso parental de 8 semanas' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET description = 'Permiso por cuidado de familiares de 2o grado o convivientes' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET name = 'Permiso por cuidado de familiares de 2o grado o convivientes' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET description = 'Es un permiso que se podría disfrutar por cualquier motivo, salvo que el convenio aplicable especificase otra cosa, existiendo acuerdo empresario-trabajador. En este se suspende la obligación de trabajar y de abonar el salario correspondiente al tiempo que el empleado se haya ausentado. No se encuentran regulados normativamente (salvo en algunos convenios colectivos). Las condiciones de uso y disfrute de estos permisos/licencia se regulan por acuerdos entre empresario y trabajador. ' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = 'Permisos legales no retribuidos ' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'El permiso retribuido es un tipo de ausencia durante la cual el trabajador seguirá siendo compensado económicamente. Los permisos remunerados están regulados en el artículo 37 del Estatuto de los Trabajadores y en los convenios colectivos.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Permisos legales retribuidos' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'Traslado domicilio habitual' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET name = 'Traslado domicilio habitual' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET description = 'Ausencia por vacaciones anuales retribuidas. No es sustituible por compensación económica, será el pactado en Convenio Colectivo o contrato individual. Respetando este pacto los mínimos legales de 30 días naturales por año.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Vacaciones' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Vacaciones año anterior. ' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET name = 'Vacaciones año anterior' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET description = 'VT. Arrastre Vacaciones' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET name = 'VT. Arrastre Vacaciones' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET description = 'VT. Caducidad vacaciones' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET name = 'VT. Caducidad vacaciones' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET description = 'Las horas que se han planificado al empleado y éste debería realizar. Justificación interna de VisualTime, no se debe borrar ni modificar.' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET name = 'VT. Horas teóricas' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET description = 'Ausencia sin motivo justificado que genera una alerta. El objetivo es que no haya ningún tiempo justificado con este motivo. Justificación interna de VisualTime, no se debe borrar ni modificar.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. NO JUSTIFICADO' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET description = 'VT. Tiempo de exceso no autorizado' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE causes SET name = 'VT. Tiempo de exceso no autorizado' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE concepts SET description = 'Tiempo de ausencia justificado pero no retribuido.' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET name = 'Absentismo no retribuido' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET description = 'Tiempo de ausencia justificado y retribuido.' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET name = 'Absentismo retribuido' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET description = 'Este saldo restará todas las "horas a recuperar" y sumará todas las "horas recuperadas". Si el total de este saldo es negativo, el empleado debe horas a la empresa.  Si el total de este saldo es positivo, la empresa debe horas al trabajador. ' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET name = 'Balance de horas' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET description = 'Horas extraordinarias. Máximo 80h anuales.' WHERE LanguageTag = 'extras'
UPDATE concepts SET name = 'Extras ' WHERE LanguageTag = 'extras'
UPDATE concepts SET description = 'Horas complementarias para contratos a tiempo parcial.' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET name = 'Horas complementarias' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET description = 'Tiempo planificado, es el tiempo que por horarios tengo que realizar' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET name = 'Tiempo planificado' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET description = 'Todo el tiempo que se considera trabajo efectivo, sin contar excesos.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Trabajo efectivo' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'Vacaciones año anterior' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET name = 'Vacaciones año anterior' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET description = 'Este saldo muestra las vacaciones pendientes de disfrutar.   Saldo inicial de vacaciones - vacaciones disfrutadas = vacaciones pendientes' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Vacaciones pendientes' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'Mi empresa' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'Reglas generales' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'Periodo disfrute vacaciones año anterior' WHERE LanguageTag = 'periododisfrutevacacionesañoanterior'
UPDATE requestsrules SET name = 'Saldo negativo vacaciones' WHERE LanguageTag = 'saldonegativovacaciones'
UPDATE shifts SET description = 'Recuerda que este horario lo puedes adaptar cuando lo planificas, permite asignar hora de entrada, número de hora tanto ordinarias como complementarias.  En este ejemplo solo una franja.  ' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET name = 'Comodín 1 franja' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET description = 'Recuerda que este horario lo puedes adaptar cuando lo planificas, permite asignar hora de entrada, número de hora tanto ordinarias como complementarias.  En este ejemplo dos franjas.  ' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET name = 'Comodín 2 franjas' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET description = 'Este horario solo sirve para los casos en los que únicamente se quiera registrar la jornada (para cumplir la normativa)y no se vaya a realizar ningún tipo de gestión del tiempo.  ' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET name = 'Contador de horas' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET description = 'Este horario tiene 0 horas teóricas. Se planificará únicamente los días en los que el empleado disfrute de un día completo de descanso y, por lo tanto, no vaya a realizar ningún fichaje.  ' WHERE LanguageTag = 'descanso'
UPDATE shifts SET name = 'Descanso' WHERE LanguageTag = 'descanso'
UPDATE shifts SET description = 'Este horario tiene 0 horas teóricas. Se planificará únicamente los días en los que el empleado disfrute de un día festivo y, por lo tanto, no vaya a realizar ningún fichaje. ' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Festivo' WHERE LanguageTag = 'festivo'
UPDATE shifts SET description = 'Es un horario totalmente flexible. El empleado podrá realizar libremente entradas y salidas entre las 6:00h y las 23:00h y sólo se controlarán si hace más o menos de las 8 horas teóricas que tiene planificadas.  ' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET name = 'Flexible 8h' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET description = 'Ejemplo de horario rígido oficina ( horas de obligado cumplimiento), con una entrada a las 8:00 y salida a las  14:00 y entrada a las 15:00 y salida a las 17:00, no olvides fichar tus descansos.  ' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET name = 'Partido oficina' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET description = 'Ejemplo de horario intensivo ( horas de obligado cumplimiento), con una entrada a las 6:00 y salida a las  14:00.  ' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET name = 'Producción turno 6 a 14' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET description = 'Vacaciones en días laborables.  ' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Vacaciones' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET description = 'Vacaciones año anterior.  ' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE shifts SET name = 'Vacaciones año anterior' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE startupvalues SET name = 'Vacaciones iniciales' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = 'Días de vacaciones anuales' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'Horas' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Mixto (horas+ocurrencias)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Ocurrencias' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Cerciorarnos de cuánto le queda al recalculo que realiza VisualTime y a cuántos empleados afecta' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Cerciorarnos de cuánto le queda al recalculo que realiza VisualTime y a cuántos empleados afecta' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Comprobar el grupo al que pertenecen los empleados. Ruta corta y completa' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Comprobar el grupo al que pertenecen los empleados. Ruta corta y completa' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Comprobar que hay alguna tarea que no ha podido ejecutarse con normalidad' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Comprobar que hay alguna tarea que no ha podido ejecutarse con normalidad' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Comprobar si el recálculo tras los cambios realizados en VisualTime está funcionando correctamente' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Comprobar si el recálculo tras los cambios realizados en VisualTime está funcionando correctamente' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Muestra los permisos de los distintos supervisores sobre las solicitudes pendientes, incluyendo si el supervisor es o no directo para cada solicitud' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET name = 'Permisos sobre solicitudes pendientes' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET description = 'Saber si el fichero de correlación está correctamente introducido en base de datos' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'Saber si el fichero de correlación está correctamente introducido en base de datos' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'Ver los fichajes que ha habido en una fecha en concreto (poder escoger fecha)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'Ver los fichajes que ha habido en una fecha en concreto (poder escoger fecha)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'Visualizar tareas pendientes colgadas de los terminales tras realizar broadcast' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'Visualizar tareas pendientes colgadas de los terminales tras realizar broadcast' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Informe de absentismo' WHERE LanguageTag = 'informedeabsentismo'
UPDATE sysroreportgroups SET name = 'Informe de saldos' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Informe de vacaciones pendientes' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysroreportgroups SET name = 'Informe general' WHERE LanguageTag = 'informegeneral'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Categoría profesional' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Auxiliares Administrativos~Ayudantes no Titulados~Ingenieros Técnicos, Peritos y Ayudantes Titulados~Ingenieros y Licenciados~Jefes Administrativos y de Taller~Oficiales Administrativos~Oficiales de primera y segunda~Oficiales de tercera y Especialistas~Peones~Subalternos~Trabajadores menores de 18 años' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Código Postal' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Complementos salariales anuales' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'Correo electrónico' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'Coste HR' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Coste por hora' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET fieldname = 'Días de vacaciones anuales' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET category = 'Personal' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Fecha de nacimiento' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Género' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Hombre~Mujer' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Grupo de cotización' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET fieldname = 'Identificador usuario' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Id importación' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET fieldname = 'Motivo de baja' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Baja voluntaria~Defunción~Despido~Finalización del contrato temporal~Incapacidad~Invalidez~Jubilación~Por causas convenidas en el contrato' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Móvil' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Personal' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Nacionalidad' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Personal' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'NIF' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Número de emergencia' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Observaciones' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Percepciones extrasalariales' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Percepciones por extraordinarias y complementarias' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Población' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Precio por hora' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Provincia' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'Puesto' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Punto de reunión' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Salario base anual' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Salario total anual' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Teléfono' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Tipo de contrato' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'En prácticas~Indefinido~Temporal' WHERE LanguageTag = 'tipodecontrato'
UPDATE timezones SET name = 'Horas con remuneración especial' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Horas nocturnas' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Horas normales' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Ausentes' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Presentes' WHERE LanguageTag = 'presentes'
GO
