UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'ENG') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 hours a year' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 hours Total' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'Vacation Dragging' WHERE LanguageTag = 'arrastrevacaciones'
UPDATE causes SET name = 'Industrial accident leave' WHERE LanguageTag = 'bajaaccidentelaboral'
UPDATE causes SET name = 'Sick leave common illness/non-occupational accident' WHERE LanguageTag = 'bajaenfermedadcomunaccnolaboral'
UPDATE causes SET description = 'Those that exceed the ordinary hours of the working day but whose performance has been agreed and agreed upon in a part-time contract. They can be of 2 types: - Agreed hours: Part-time contracts with a working day of no less than ten hours per week on an annual basis. - Voluntary hours: Part-time contracts of indefinite duration with a working day of no less than 10 hours per week on an annual basis.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'Supplementary hours' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Hours of work carried out over and above the maximum duration of the ordinary working day established by law or convention. A maximum of 80 hours of this type may be carried out per year.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = ' Overtime' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Doctor''s visit' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Doctor' WHERE LanguageTag = 'medico'
UPDATE causes SET description = ' This is a leave that can be taken for any reason, unless the applicable agreement specifies otherwise, and there is an agreement between the employer and the employee. This suspends the obligation to work and pay the salary corresponding to the time that the employee has been absent. They are not regulated by law (except in some collective agreements). The conditions of use and enjoyment of these permits/licenses are regulated by agreements between the employer and the employee.' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = ' Unpaid legal leave' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'Paid leave is a type of absence during which the worker will continue to receive financial compensation. Paid leave is regulated in article 37 of the Workers statute and in collective agreements.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Paid legal leave' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'The time during which the work activity is carried out mainly at the employee''s home or at a place freely chosen by the employee, as an alternative to being carried out in person at the company''s work center.' WHERE LanguageTag = 'teletrabajo'
UPDATE causes SET name = 'Telework' WHERE LanguageTag = 'teletrabajo'
UPDATE causes SET description = 'These are times that are not authorized by the company or that do not want to be treated either positively or negatively.' WHERE LanguageTag = 'tiempodeexcesonojustificado'
UPDATE causes SET name = 'Unexcused excess time' WHERE LanguageTag = 'tiempodeexcesonojustificado'
UPDATE causes SET description = 'Planned time that has not been worked and must be made up at another time.' WHERE LanguageTag = 'tiempoporrecuperar'
UPDATE causes SET name = 'Time to recover' WHERE LanguageTag = 'tiempoporrecuperar'
UPDATE causes SET description = 'Positive hours performed to compensate for negative hours that may be performed.' WHERE LanguageTag = 'tiemporecuperado'
UPDATE causes SET name = 'Time recovered' WHERE LanguageTag = 'tiemporecuperado'
UPDATE causes SET description = 'The hours that have been planned for the employee and that he/she should work. Internal justification of VisualTime, should not be deleted or modified.' WHERE LanguageTag = 'tiempoteorico'
UPDATE causes SET name = 'Theoretical time' WHERE LanguageTag = 'tiempoteorico'
UPDATE causes SET description = 'Hours worked within the user''s planned schedule' WHERE LanguageTag = 'trabajoefectivo'
UPDATE causes SET name = 'Effective work' WHERE LanguageTag = 'trabajoefectivo'
UPDATE causes SET description = 'Absence due to paid annual leave. It cannot be replaced by financial compensation, it will be as agreed in the Collective Agreement or individual contract. This agreement respects the legal minimum of 30 calendar days per year.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Vacation' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Absence without a justified reason that generates an alert. The objective is that there is no time justified with this reason. Internal VisualTime justification, it should not be deleted or modified.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. NOT JUSTIFIED' WHERE LanguageTag = 'vtnojustificado'
UPDATE concepts SET description = ' This balance will subtract all the "hours to recover" and add all the "hours recovered". If the total of this balance is negative, the employee owes hours to the company. If the total of this balance is positive, the company owes hours to the worker.' WHERE LanguageTag = 'horas'
UPDATE concepts SET name = 'Hours+/-' WHERE LanguageTag = 'horas'
UPDATE concepts SET description = 'Planned time is the time that I have to do according to schedules.' WHERE LanguageTag = 'tiempoplanificadoteoria'
UPDATE concepts SET name = 'Planned time (theory)' WHERE LanguageTag = 'tiempoplanificadoteoria'
UPDATE concepts SET description = 'Time of absence' WHERE LanguageTag = 'totalabsentismo'
UPDATE concepts SET name = 'Total absenteeism' WHERE LanguageTag = 'totalabsentismo'
UPDATE concepts SET description = 'Additional hours for part-time contracts.' WHERE LanguageTag = 'totalhorascomplementarias'
UPDATE concepts SET name = 'Total supplementary hours' WHERE LanguageTag = 'totalhorascomplementarias'
UPDATE concepts SET description = 'Overtime.' WHERE LanguageTag = 'totalhorasextras'
UPDATE concepts SET name = 'Total overtime' WHERE LanguageTag = 'totalhorasextras'
UPDATE concepts SET description = 'All the time that is considered effective work, not counting overtime.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Effective work' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'This balance shows the vacations pending to be taken. Initial vacation balance - vacations taken = pending vacations' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Pending holidays' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'My company' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'General rules' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'Do not ask for vacation if there is no positive balance' WHERE LanguageTag = 'nopedirvacacionessinohaysaldopositivo'
UPDATE shifts SET description = 'Holidays, non-working days.' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Festive' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Working day' WHERE LanguageTag = 'laborable'
UPDATE shifts SET description = ' This schedule has 0 theoretical hours. It will only be planned on days when the employee has a full day off and therefore will not be clocking in.' WHERE LanguageTag = 'nolaboral'
UPDATE shifts SET name = 'Non-labor' WHERE LanguageTag = 'nolaboral'
UPDATE shifts SET description = ' Holidays on working days.' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Vacation' WHERE LanguageTag = 'vacaciones'
UPDATE startupvalues SET name = 'Vacation' WHERE LanguageTag = 'vacaciones'
UPDATE startupvalues SET name = 'Initial vacation' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = '0' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'hours' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Mixed (hours+occurrences)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Occurrences' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Make sure how much is left for the recalculation performed by VisualTime and how many employees it affects' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Make sure how much is left for the recalculation performed by VisualTime' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Check the group to which the employees belong. Short and complete route' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Check the group to which the employees belong. Short and complete route' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Check if there is a task that could not be executed normally' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Check if there is a task that could not be executed normally' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Check if customer has GPA' WHERE LanguageTag = 'comprobarsiclientetienegpa'
UPDATE sysroqueries SET name = 'Check if customer has GPA' WHERE LanguageTag = 'comprobarsiclientetienegpa'
UPDATE sysroqueries SET description = 'Check if recalculation after changes made in VisualTime is working correctly' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Check if recalculation after changes made in VisualTime is working correctly' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Mustra the permissions of the supervisors in V2' WHERE LanguageTag = 'permisosefectivos'
UPDATE sysroqueries SET name = 'Effective leaves of absence' WHERE LanguageTag = 'permisosefectivos'
UPDATE sysroqueries SET description = 'Displays permissions on the Employee and Calendar functionalities of supervisors in V2 on employees' WHERE LanguageTag = 'permisosefectivossobrefuncionalidadesconcretas'
UPDATE sysroqueries SET name = 'Effective permissions on specific functionalities' WHERE LanguageTag = 'permisosefectivossobrefuncionalidadesconcretas'
UPDATE sysroqueries SET description = 'Check if the correlation file is correctly entered into the database' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'Check if the correlation file is correctly entered into the database' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'To know if there are any planned reports being executed' WHERE LanguageTag = 'sabersihayalguninformeplanificadoejecutandose'
UPDATE sysroqueries SET name = 'To know if there are any planned reports being executed' WHERE LanguageTag = 'sabersihayalguninformeplanificadoejecutandose'
UPDATE sysroqueries SET description = 'View the signings that have taken place on a specific date (you can choose the date)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'View the signings that have taken place on a specific date (you can choose the date)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'View pending tasks hanging on terminals after broadcasting' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'View pending tasks hanging on terminals after broadcasting' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Balance Report' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Report of pending vacations' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Professional category' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Administrative Assistants~Non-Qualified Assistants~Technical Engineers, Experts and Qualified Assistants~Engineers and Graduates~Administrative and Workshop Managers~Administrative Officers~First and Second Class Officers~Third Class Officers and Specialists~Laborers~Subordinates~Workers under 18 years of age' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Zip code' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Annual salary supplements' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'Email' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'HR cost' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Cost per hour' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'Staff' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Birthdate' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Gender' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Man~Woman' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Contribution group' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Import ID' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Reason for absence' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Voluntary resignation~Death~Dismissal~Termination of temporary contract~Incapacity~Disability~Retirement~For reasons agreed in the contract' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Mobile' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Staff' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Nationality' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Staff' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'NIF' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Emergency number' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Observations' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Extra-salary perceptions' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Extraordinary and complementary perceptions' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Population' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Price per hour' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Province' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'Position' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Meeting point' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Annual base salary' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Total annual salary' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Phone' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Type of contract' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'Internship~Indefinite~Temporary' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET category = 'Labor' WHERE LanguageTag = 'valorinicialdevacaciones'
UPDATE sysrouserfields SET fieldname = 'Initial vacation value' WHERE LanguageTag = 'valorinicialdevacaciones'
UPDATE timezones SET name = 'Hours with special remuneration' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Night hours' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Normal hours' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Missing' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Presents' WHERE LanguageTag = 'presentes'
GO