UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'SLK') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 hodín po celý rok' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 h Spolu' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'Vlečná sieť na dovolenke' WHERE LanguageTag = 'arrastrevacaciones'
UPDATE causes SET name = 'Nemocenská dovolenka pre pracovné úrazy' WHERE LanguageTag = 'bajaaccidentelaboral'
UPDATE causes SET name = 'Nemocenská dovolenka pri bežnej chorobe/nepráci' WHERE LanguageTag = 'bajaenfermedadcomunaccnolaboral'
UPDATE causes SET description = 'Tí, ktorí prekračujú bežný pracovný čas, ale ktorých výkon bol dohodnutý a schválený v zmluve na čiastočný úväzok. Môžu byť 2 typy: -Dohodnutý pracovný čas: Zmluvy na čiastočný úväzok s pracovným dňom v rozsahu najmenej desať hodín týždenne na ročnom základe. -Dobrovoľné hodiny: Zmluvy na čiastočný úväzok na dobu neurčitú s pracovným dňom nie kratším ako 10 hodín týždenne na ročnom základe.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'doplnkové hodiny' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Hodiny práce vykonávanej v rámci maximálneho trvania bežného pracovného dňa stanoveného zákonom alebo dohodou.  Za rok sa môže odpracovať maximálne 80 hodín tohto druhu práce.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = 'Nadčasy' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Návšteva lekára' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Doktor' WHERE LanguageTag = 'medico'
UPDATE causes SET description = 'Ide o dovolenku, ktorú si možno vziať z akéhokoľvek dôvodu, pokiaľ platná dohoda nestanovuje inak a pokiaľ neexistuje dohoda medzi zamestnávateľom a zamestnancom. Pozastavuje povinnosť pracovať a vyplácať mzdu zodpovedajúcu času, počas ktorého bol zamestnanec neprítomný. Nie sú upravené zákonom (s výnimkou niektorých kolektívnych zmlúv). Podmienky čerpania a využívania týchto dovoleniek/odpočinku upravujú dohody medzi zamestnávateľom a zamestnancom.' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = 'Neplatená zákonná dovolenka' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'Platené voľno je druh neprítomnosti, počas ktorej pracovník naďalej dostáva finančnú náhradu. Platené voľno je upravené v článku 37 Štatútu zamestnancov a v kolektívnych zmluvách.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Platená zákonná dovolenka' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'Čas, počas ktorého sa práca vykonáva najmä doma alebo na mieste, ktoré si pracovník slobodne zvolí, ako alternatíva k osobnému výkonu práce na pracovisku spoločnosti.' WHERE LanguageTag = 'teletrabajo'
UPDATE causes SET name = 'Telework' WHERE LanguageTag = 'teletrabajo'
UPDATE causes SET description = 'Ide o časy, ktoré spoločnosť nepovoľuje alebo ktoré nechcú byť považované za pozitívne alebo negatívne.' WHERE LanguageTag = 'tiempodeexcesonojustificado'
UPDATE causes SET name = 'Neospravedlnený nadčas' WHERE LanguageTag = 'tiempodeexcesonojustificado'
UPDATE causes SET description = 'Plánovaný čas, ktorý nebol odpracovaný a musí byť nahradený v inom čase.' WHERE LanguageTag = 'tiempoporrecuperar'
UPDATE causes SET name = 'Čas na zotavenie' WHERE LanguageTag = 'tiempoporrecuperar'
UPDATE causes SET description = 'Kladné hodiny, ktoré sa odpracujú na kompenzáciu záporných hodín, ktoré sa môžu odpracovať.' WHERE LanguageTag = 'tiemporecuperado'
UPDATE causes SET name = 'Obnovený čas' WHERE LanguageTag = 'tiemporecuperado'
UPDATE causes SET description = 'Hodiny, ktoré boli pre zamestnanca naplánované a ktoré by mal vykonať. Interné zdôvodnenie VisualTime, ktoré sa nesmie vymazať ani zmeniť.' WHERE LanguageTag = 'tiempoteorico'
UPDATE causes SET name = 'Teoretický čas' WHERE LanguageTag = 'tiempoteorico'
UPDATE causes SET description = 'Odpracované hodiny v rámci plánovaného rozvrhu používateľa' WHERE LanguageTag = 'trabajoefectivo'
UPDATE causes SET name = 'Efektívna práca' WHERE LanguageTag = 'trabajoefectivo'
UPDATE causes SET description = 'Neprítomnosť z dôvodu platenej dovolenky. Nenahrádza sa finančnou náhradou; jej výška je dohodnutá v kolektívnej zmluve alebo v individuálnej zmluve. Pri rešpektovaní tejto dohody je zákonné minimum 30 kalendárnych dní ročne.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Dovolenka' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Neospravedlnená neprítomnosť, ktorá generuje upozornenie. Cieľom je, aby z tohto dôvodu nebol ospravedlnený čas. Interné ospravedlnenie VisualTime, ktoré sa nesmie vymazať ani upraviť.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. NIE JE OSPRAVODLNENÝ' WHERE LanguageTag = 'vtnojustificado'
UPDATE concepts SET description = 'Týmto zostatkom sa odpočítajú všetky "hodiny, ktoré sa majú obnoviť" a pripočítajú sa všetky "obnovené hodiny". Ak je súčet tohto zostatku záporný, zamestnanec dlhuje spoločnosti hodiny.  Ak je súčet tohto zostatku kladný, spoločnosť dlhuje zamestnancovi hodiny.' WHERE LanguageTag = 'horas'
UPDATE concepts SET name = 'Hodiny+/-' WHERE LanguageTag = 'horas'
UPDATE concepts SET description = 'Plánovaný čas, to je čas, ktorý musím venovať rozvrhom' WHERE LanguageTag = 'tiempoplanificadoteoria'
UPDATE concepts SET name = 'Plánovaný čas (teória)' WHERE LanguageTag = 'tiempoplanificadoteoria'
UPDATE concepts SET description = 'Čas mimo domova' WHERE LanguageTag = 'totalabsentismo'
UPDATE concepts SET name = 'Celková absencia' WHERE LanguageTag = 'totalabsentismo'
UPDATE concepts SET description = 'Ďalšie hodiny pre zmluvy na čiastočný úväzok.' WHERE LanguageTag = 'totalhorascomplementarias'
UPDATE concepts SET name = 'Celkový počet hodín navyše' WHERE LanguageTag = 'totalhorascomplementarias'
UPDATE concepts SET description = 'Nadčasy.' WHERE LanguageTag = 'totalhorasextras'
UPDATE concepts SET name = 'Nadčasy spolu' WHERE LanguageTag = 'totalhorasextras'
UPDATE concepts SET description = 'Celý čas, ktorý sa považuje za efektívnu prácu, okrem nadčasov.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Efektívna práca' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'Tento zostatok zobrazuje nevyčerpanú dovolenku, ktorá sa má vyčerpať.   Počiatočný zostatok dovolenky - vyčerpaná dovolenka = nevyčerpaná dovolenka' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Dovolenka v očakávaní' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'Moja spoločnosť' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'Všeobecné pravidlá' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'Nežiadajte o dovolenku, ak nie je kladný zostatok' WHERE LanguageTag = 'nopedirvacacionessinohaysaldopositivo'
UPDATE shifts SET description = 'Sviatky, dni pracovného pokoja.' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Slávnostné' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Pracovná stránka' WHERE LanguageTag = 'laborable'
UPDATE shifts SET description = 'Tento rozvrh má 0 plánovaných hodín. Plánuje sa len v dňoch, keď má zamestnanec celý voľný deň, a preto nebude mať hodiny.  ' WHERE LanguageTag = 'nolaboral'
UPDATE shifts SET name = 'Neprofesionálne' WHERE LanguageTag = 'nolaboral'
UPDATE shifts SET description = 'Sviatky v pracovných dňoch.  ' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Dovolenka' WHERE LanguageTag = 'vacaciones'
UPDATE startupvalues SET name = 'Dovolenka' WHERE LanguageTag = 'vacaciones'
UPDATE startupvalues SET name = 'Počiatočné prázdniny' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = '0' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'hodiny' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Zmiešané (hodiny+výskyt)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Výskyt' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Uistite sa, koľko zostáva z prepočtu VisualTime a koľkých zamestnancov sa to týka' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Uistite sa, koľko zostáva z prepočtu VisualTime a koľkých zamestnancov sa to týka' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Skontrolujte skupinu, do ktorej zamestnanci patria. Krátka a úplná trasa' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Skontrolujte skupinu, do ktorej zamestnanci patria. Krátka a úplná trasa' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Skontrolujte, či existuje úloha, ktorú nebolo možné normálne vykonať' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Skontrolujte, či existuje úloha, ktorú nebolo možné normálne vykonať' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Skontrolujte, či má klient GPA' WHERE LanguageTag = 'comprobarsiclientetienegpa'
UPDATE sysroqueries SET name = 'Skontrolujte, či má klient GPA' WHERE LanguageTag = 'comprobarsiclientetienegpa'
UPDATE sysroqueries SET description = 'Skontrolujte, či prepočet po zmenách vykonaných v aplikácii VisualTime funguje správne' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Skontrolujte, či prepočet po zmenách vykonaných v aplikácii VisualTime funguje správne' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Oprávnenia nadriadených v systéme V2' WHERE LanguageTag = 'permisosefectivos'
UPDATE sysroqueries SET name = 'Skutočná dovolenka' WHERE LanguageTag = 'permisosefectivos'
UPDATE sysroqueries SET description = 'Zobrazuje oprávnenia na funkcie Zamestnanec a Kalendár nadriadených vo V2 na zamestnancoch' WHERE LanguageTag = 'permisosefectivossobrefuncionalidadesconcretas'
UPDATE sysroqueries SET name = 'Účinné oprávnenia na konkrétne funkcie' WHERE LanguageTag = 'permisosefectivossobrefuncionalidadesconcretas'
UPDATE sysroqueries SET description = 'Ak chcete zistiť, či je korelačný súbor správne vložený do databázy' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'Ak chcete zistiť, či je korelačný súbor správne vložený do databázy' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'Zistite, či sa vykonávajú nejaké plánované správy' WHERE LanguageTag = 'sabersihayalguninformeplanificadoejecutandose'
UPDATE sysroqueries SET name = 'Zistite, či sa vykonávajú nejaké plánované správy' WHERE LanguageTag = 'sabersihayalguninformeplanificadoejecutandose'
UPDATE sysroqueries SET description = 'Pozrite si podpisy, ktoré sa uskutočnili v určitý deň (dátum si môžete vybrať)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'Pozrite si podpisy, ktoré sa uskutočnili v určitý deň (dátum si môžete vybrať)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'Zobrazenie čakajúcich úloh zavesených na termináloch po vysielaní' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'Zobrazenie čakajúcich úloh zavesených na termináloch po vysielaní' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Bilančná správa' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Vynikajúca správa o dovolenke' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Profesionálna kategória' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Administratívni asistenti~asistenti s vysokoškolským vzdelaním~technickí inžinieri, experti a asistenti s vysokoškolským vzdelaním~inžinieri a absolventi~administratívni pracovníci a vedúci dielní~administratívni úradníci~úradníci prvej a druhej triedy~úradníci tretej triedy a špecialisti~pionieri~podpôradní pracovníci~pracovníci mladší ako 18 rokov' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Poštové smerovacie číslo' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Ročné príplatky k platu' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'E-mailová adresa' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'Náklady na ľudské zdroje' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Náklady na hodinu' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'Zamestnanci' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Dátum narodenia' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Pohlavie' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Muž~Žena' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Skupina príspevkov' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Import Id' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Dôvod odchodu' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Dobrovoľná dovolenka~Dobrovoľné prepustenie~Dočasné ukončenie zmluvy~Invalidita~Invalidita~Dôchodok~Z dôvodov dohodnutých v zmluve' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Mobilný portál' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Zamestnanci' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Štátna príslušnosť' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Zamestnanci' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'NIF' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Núdzové číslo' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Poznámky' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Platby mimo mzdy' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Mimoriadne a dodatočné platby' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Obyvateľstvo' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Hodinová sadzba' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Provincia' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'pošta' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Miesto stretnutia' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Základný ročný plat' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Celkový ročný plat' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Telefón' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Typ zmluvy' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'Stážista~Na dobu neurčitú~Dočasne' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET category = 'Práca' WHERE LanguageTag = 'valorinicialdevacaciones'
UPDATE sysrouserfields SET fieldname = 'Počiatočná hodnota dovolenky' WHERE LanguageTag = 'valorinicialdevacaciones'
UPDATE timezones SET name = 'Hodiny s osobitnou odmenou' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Nočné hodiny' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Bežné hodiny' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Neprítomný' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Súčasnosť' WHERE LanguageTag = 'presentes'
GO