UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'ENG') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 hours all year round' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 h Total' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'Vacation carryforward' WHERE LanguageTag = 'arrastredevacaciones'
UPDATE accrualsrules SET description = 'Vacations from the previous year can be taken until 1/31 of the current year. If they have not been taken, such vacations are lost (they expire).' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE accrualsrules SET name = 'Expiration of vacation leave for the previous year' WHERE LanguageTag = 'caducidaddevacacionesañoanterior'
UPDATE causelimitvalues SET name = 'Limit of 80 hours of overtime pay' WHERE LanguageTag = 'limitede80horasextrasapagar'
UPDATE causes SET description = 'ATEP discharge' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET name = 'ATEP discharge' WHERE LanguageTag = 'bajaatep'
UPDATE causes SET description = 'Low CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET name = 'Low CC' WHERE LanguageTag = 'bajacc'
UPDATE causes SET description = 'Inexcusable duties, of a public and/or personal nature' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET name = 'Inexcusable duties, of a public and/or personal nature' WHERE LanguageTag = 'deberesinexcusablesdecaracterpublicoyopersonal'
UPDATE causes SET description = 'Official examinations' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET name = 'Official examinations' WHERE LanguageTag = 'examenesoficiales'
UPDATE causes SET description = 'Prenatal examinations and childbirth preparation techniques' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET name = 'Prenatal examinations and childbirth preparation techniques' WHERE LanguageTag = 'examenesprenatalesytecnicasdepreparacionalparto'
UPDATE causes SET description = 'Those that exceed the ordinary hours of the working day but whose performance has been agreed and agreed in a part-time contract. They can be of 2 types: -Agreed hours: Part-time contracts with a working day of not less than ten hours per week on an annual basis. -Voluntary hours: Part-time contracts of indefinite duration with a working day of not less than 10 hours per week on an annual basis.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'additional hours' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Hours of work performed over the maximum duration of the ordinary working day established by law or by agreement.  A maximum of 80 hours of this type may be worked per year.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = 'Overtime' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Hours worked within the employee''s scheduled hours.' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET name = 'Ordinary hours' WHERE LanguageTag = 'horasordinarias'
UPDATE causes SET description = 'Planned time that has not been worked and must be made up at another time.' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET name = 'Hours to be recovered' WHERE LanguageTag = 'horasporrecuperar'
UPDATE causes SET description = 'Positive hours that are performed to compensate for negative hours that may be performed, indicated for companies with flexibility.' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET name = 'Hours recovered' WHERE LanguageTag = 'horasrecuperadas'
UPDATE causes SET description = 'Breastfeeding' WHERE LanguageTag = 'lactancia'
UPDATE causes SET name = 'Breastfeeding' WHERE LanguageTag = 'lactancia'
UPDATE causes SET description = 'Maternity/Paternity' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET name = 'Maternity/Paternity' WHERE LanguageTag = 'maternidadpaternidad'
UPDATE causes SET description = 'Family marriage' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET name = 'Family marriage' WHERE LanguageTag = 'matrimoniofamiliar'
UPDATE causes SET description = 'Own marriage' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET name = 'Own marriage' WHERE LanguageTag = 'matrimoniopropio'
UPDATE causes SET description = 'Physician' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Physician' WHERE LanguageTag = 'medico'
UPDATE causes SET description = 'Birth of child' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET name = 'Birth of child' WHERE LanguageTag = 'nacimientohijo'
UPDATE causes SET description = 'Force majeure leave' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET name = 'Force majeure leave' WHERE LanguageTag = 'permisofuerzamayor'
UPDATE causes SET description = '8 weeks parental leave' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET name = '8 weeks parental leave' WHERE LanguageTag = 'permisoparentalde8semanas'
UPDATE causes SET description = 'Leave of absence for care of 2nd degree relatives or domestic partners' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET name = 'Leave of absence for care of 2nd degree relatives or domestic partners' WHERE LanguageTag = 'permisoporcuidadodefamiliaresde2ogradooconvivientes'
UPDATE causes SET description = 'It is a leave of absence that may be taken for any reason, unless the applicable agreement specifies otherwise, and there is an employer-employee agreement. It suspends the obligation to work and to pay the salary corresponding to the time the employee has been absent. They are not regulated by law (except in some collective bargaining agreements). The conditions of use and enjoyment of these leaves/leave are regulated by agreements between employer and employee.' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = 'Unpaid legal leave' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'Paid leave is a type of absence during which the employee will continue to be financially compensated. Paid leave is regulated in Article 37 of the Workers Statute and in collective bargaining agreements.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Paid statutory leave' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'Relocation of usual place of residence' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET name = 'Relocation of usual place of residence' WHERE LanguageTag = 'trasladodomiciliohabitual'
UPDATE causes SET description = 'Absence due to paid annual leave. It is not replaceable by economic compensation, it will be the one agreed in the Collective Bargaining Agreement or individual contract. Respecting this agreement the legal minimum of 30 calendar days per year.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Vacation' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Vacations previous year.' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET name = 'Vacations previous year' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE causes SET description = 'VT. Vacation Trawl' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET name = 'VT. Vacation Trawl' WHERE LanguageTag = 'vtarrastrevacaciones'
UPDATE causes SET description = 'VT. Vacation expiration' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET name = 'VT. Vacation expiration' WHERE LanguageTag = 'vtcaducidadvacaciones'
UPDATE causes SET description = 'The hours that have been planned for the employee and that he/she should perform. Internal VisualTime justification, not to be deleted or modified.' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET name = 'VT. Theoretical hours' WHERE LanguageTag = 'vthorasteoricas'
UPDATE causes SET description = 'Unexcused absence that generates an alert. The objective is that there is no justified time with this reason. Internal VisualTime justification, not to be deleted or modified.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. NOT SUPPORTED' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET description = 'VT. Unauthorized excess time' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE causes SET name = 'VT. Unauthorized excess time' WHERE LanguageTag = 'vttiempodeexcesonoautorizado'
UPDATE concepts SET description = 'Excused but unpaid time off.' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET name = 'Unpaid absenteeism' WHERE LanguageTag = 'absentismonoretribuido'
UPDATE concepts SET description = 'Paid and excused absence time.' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET name = 'Paid absenteeism' WHERE LanguageTag = 'absentismoretribuido'
UPDATE concepts SET description = 'This balance will subtract all "hours to be recovered" and add all "hours recovered". If the total of this balance is negative, the employee owes hours to the company.  If the total of this balance is positive, the company owes hours to the employee.' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET name = 'Balance of hours' WHERE LanguageTag = 'balancedehoras'
UPDATE concepts SET description = 'Overtime. Maximum 80 hours per year.' WHERE LanguageTag = 'extras'
UPDATE concepts SET name = 'Extras' WHERE LanguageTag = 'extras'
UPDATE concepts SET description = 'Supplementary hours for part-time contracts.' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET name = 'Additional hours' WHERE LanguageTag = 'horascomplementarias'
UPDATE concepts SET description = 'Planned time, is the time I have to perform according to my schedule' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET name = 'Planned time' WHERE LanguageTag = 'tiempoplanificado'
UPDATE concepts SET description = 'All the time that is considered effective work, not counting overtime.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Effective work' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'Vacations previous year' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET name = 'Vacations previous year' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE concepts SET description = 'This balance shows the outstanding leave to be taken.   Vacation starting balance - Vacation taken = vacation outstanding' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Vacation pending' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'My company' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'General rules' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'Vacation leave period previous year' WHERE LanguageTag = 'periododisfrutevacacionesañoanterior'
UPDATE requestsrules SET name = 'Negative balance vacations' WHERE LanguageTag = 'saldonegativovacaciones'
UPDATE shifts SET description = 'Remember that you can adapt this schedule when you plan it, it allows you to assign an entry time, number of hours both ordinary and complementary.  In this example only one time slot.  ' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET name = 'Wild card 1 stripe' WHERE LanguageTag = 'comodin1franja'
UPDATE shifts SET description = 'Remember that you can adapt this schedule when you plan it, it allows you to assign an entry time, number of hours both ordinary and complementary.  In this example two time slots.  ' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET name = 'Joker 2 stripes' WHERE LanguageTag = 'comodin2franjas'
UPDATE shifts SET description = 'This timetable is only useful in cases where you only want to record the working day (to comply with the regulations) and you are not going to perform any type of time management.  ' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET name = 'Hour meter' WHERE LanguageTag = 'contadordehoras'
UPDATE shifts SET description = 'This schedule has 0 planned hours. It will only be scheduled on days when the employee has a full day off and therefore will not be clocking in.  ' WHERE LanguageTag = 'descanso'
UPDATE shifts SET name = 'break' WHERE LanguageTag = 'descanso'
UPDATE shifts SET description = 'This schedule has 0 planned hours. It will only be scheduled on days when the employee has a holiday and therefore will not be clocking in.' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Festive' WHERE LanguageTag = 'festivo'
UPDATE shifts SET description = 'It is a totally flexible schedule. The employee can freely clock in and out between 6:00 a.m. and 11:00 p.m. and will only be monitored if he/she works more or less than the theoretical 8 hours planned.  ' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET name = 'Flexible 8h' WHERE LanguageTag = 'flexible8h'
UPDATE shifts SET description = 'Example of a rigid office schedule (mandatory hours), with an entry at 8:00 and exit at 14:00 and entry at 15:00 and exit at 17:00, do not forget to clock your breaks.  ' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET name = 'Party office' WHERE LanguageTag = 'partidooficina'
UPDATE shifts SET description = 'Example of an intensive schedule (mandatory hours), with a 6:00 a.m. start time and a 2:00 p.m. departure time.  ' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET name = 'Production shift 6 to 14' WHERE LanguageTag = 'produccionturno6a14'
UPDATE shifts SET description = 'Vacations on working days.  ' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Vacation' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET description = 'Vacations previous year.  ' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE shifts SET name = 'Vacations previous year' WHERE LanguageTag = 'vacacionesañoanterior'
UPDATE startupvalues SET name = 'Initial vacations' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = 'Annual leave days' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'Hours' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Mixed (hours+occurrences)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Occurrences' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Check how much of the recalculation performed by VisualTime is left and how many employees are affected' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Check how much of the recalculation performed by VisualTime is left and how many employees are affected' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Check the group to which the employees belong. Short and complete route' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Check the group to which the employees belong. Short and complete route' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Check that there is a task that could not be executed normally' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Check that there is a task that could not be executed normally' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Check if the recalculation after changes made in VisualTime is working properly' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Check if the recalculation after changes made in VisualTime is working properly' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Displays the permissions of the various supervisors on pending requests, including whether or not the supervisor is direct for each request' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET name = 'Permits on pending applications' WHERE LanguageTag = 'permisossobresolicitudespendientes'
UPDATE sysroqueries SET description = 'To know if the correlation file is correctly entered in the database' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'To know if the correlation file is correctly entered in the database' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'View the transfers that have taken place on a specific date (choose date)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'View the transfers that have taken place on a specific date (choose date)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'Display pending tasks hung on terminals after broadcasting' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'Display pending tasks hung on terminals after broadcasting' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Absenteeism report' WHERE LanguageTag = 'informedeabsentismo'
UPDATE sysroreportgroups SET name = 'Balance report' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Outstanding vacation report' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysroreportgroups SET name = 'General Report' WHERE LanguageTag = 'informegeneral'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Professional category' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Administrative Assistants~Undergraduate Assistants~Technical Engineers, Experts and Graduate Assistants~Engineers and Graduates~Administrative and Workshop Managers~Administrative Officers~First and Second Class Officers~Third Class Officers and Specialists~Peons~Underclassmen~Workers under 18 years of age~Workers under 18 years of age' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Zip Code' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Annual salary supplements' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'Email' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'HR Cost' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Cost per hour' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET fieldname = 'Annual leave days' WHERE LanguageTag = 'diasdevacacionesanuales'
UPDATE sysrouserfields SET category = 'Personnel' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Date of birth' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Gender' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Male~Female' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Social security contribution group' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET fieldname = 'User identifier' WHERE LanguageTag = 'identificadorusuario'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'import id' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET fieldname = 'Reason for leaving' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Voluntary leave~Dismissal~Dismissal~Temporary contract termination~Disability~Disability~Retirement~For causes agreed in the contract' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Mobile' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Personnel' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Nationality' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Personnel' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'NIF (tax identification code):' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Emergency number' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Observations' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Non-salary remuneration' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Extraordinary and supplementary remuneration' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'City' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Price per hour' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Province' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'Position' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'Visualtime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Meeting point' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Base annual salary' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Total annual salary' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Phone' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Working' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Type of contract' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'Intern~Indefinite~Temporary~Temporary' WHERE LanguageTag = 'tipodecontrato'
UPDATE timezones SET name = 'Hours with special remuneration' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Night hours' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Normal hours' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Absent' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Present' WHERE LanguageTag = 'presentes'
GO