UPDATE sysroPassports SET IDLanguage = (SELECT ID FROM sysroLanguages WHERE LanguageKey = 'ESP') WHERE Description LIKE '@@ROBOTICS@@%'
GO
UPDATE accessgroups SET name = '24 horas todo el año' WHERE LanguageTag = '24horastodoelaño'
UPDATE accessperiods SET name = '24 h Total' WHERE LanguageTag = '24htotal'
UPDATE accrualsrules SET name = 'Arrastre vacaciones' WHERE LanguageTag = 'arrastrevacaciones'
UPDATE causes SET name = 'Baja accidente laboral ' WHERE LanguageTag = 'bajaaccidentelaboral'
UPDATE causes SET name = 'Baja enfermedad común/acc no laboral' WHERE LanguageTag = 'bajaenfermedadcomunaccnolaboral'
UPDATE causes SET description = 'Aquéllas que superan las horas ordinarias de la jornada laboral pero cuya realización ha sido pactada y acordada en un contrato a tiempo parcial. Pueden ser de 2 tipos: -Horas pactadas: Contratos a tiempo parcial con una jornada de trabajo no inferior a diez horas semanales en cómputo anual. -Horas voluntarias: Contratos a tiempo parcial de duración indefinida con una jornada de trabajo no inferior a 10 horas semanales en cómputo anual.' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET name = 'Horas complementarias ' WHERE LanguageTag = 'horascomplementarias'
UPDATE causes SET description = 'Horas de trabajo que se realicen sobre la duración máxima de la jornada ordinaria de trabajo fijada, legal o convencionalmente.  Como máximo, se podrán realizar 80h de este tipo al año.' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET name = 'Horas extraordinarias ' WHERE LanguageTag = 'horasextraordinarias'
UPDATE causes SET description = 'Visita médico' WHERE LanguageTag = 'medico'
UPDATE causes SET name = 'Médico' WHERE LanguageTag = 'medico'
UPDATE causes SET description = 'Es un permiso que se podría disfrutar por cualquier motivo, salvo que el convenio aplicable especificase otra cosa, existiendo acuerdo empresario-trabajador. En este se suspende la obligación de trabajar y de abonar el salario correspondiente al tiempo que el empleado se haya ausentado. No se encuentran regulados normativamente (salvo en algunos convenios colectivos). Las condiciones de uso y disfrute de estos permisos/licencia se regulan por acuerdos entre empresario y trabajador. ' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET name = 'Permisos legales no retribuidos ' WHERE LanguageTag = 'permisoslegalesnoretribuidos'
UPDATE causes SET description = 'El permiso retribuido es un tipo de ausencia durante la cual el trabajador seguirá siendo compensado económicamente. Los permisos remunerados están regulados en el artículo 37 del Estatuto de los Trabajadores y en los convenios colectivos.' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET name = 'Permisos legales retribuidos' WHERE LanguageTag = 'permisoslegalesretribuidos'
UPDATE causes SET description = 'Aquel tiempo en que la prestación de la actividad laboral se realice de manera preponderante en el domicilio del trabajador o en el lugar libremente elegido por este, de modo alternativo a su desarrollo presencial en el centro de trabajo de la empresa.' WHERE LanguageTag = 'teletrabajo'
UPDATE causes SET name = 'Teletrabajo' WHERE LanguageTag = 'teletrabajo'
UPDATE causes SET description = 'Son tiempos no autorizados por la empresa o que no se quieren dar ningún tratamiento ya sea positivo o negativo.' WHERE LanguageTag = 'tiempodeexcesonojustificado'
UPDATE causes SET name = 'Tiempo de exceso no justificado' WHERE LanguageTag = 'tiempodeexcesonojustificado'
UPDATE causes SET description = 'El tiempo planificado que no se ha trabajado y debe recuperarse en otro momento.' WHERE LanguageTag = 'tiempoporrecuperar'
UPDATE causes SET name = 'Tiempo por recuperar' WHERE LanguageTag = 'tiempoporrecuperar'
UPDATE causes SET description = 'Horas positivas  que se realizan para compensar horas negativas que puedan realizarse.' WHERE LanguageTag = 'tiemporecuperado'
UPDATE causes SET name = 'Tiempo recuperado ' WHERE LanguageTag = 'tiemporecuperado'
UPDATE causes SET description = 'Las horas que se han planificado al empleado y éste debería realizar. Justificación interna de VisualTime, no se debe borrar ni modificar.' WHERE LanguageTag = 'tiempoteorico'
UPDATE causes SET name = 'Tiempo teórico' WHERE LanguageTag = 'tiempoteorico'
UPDATE causes SET description = 'Horas trabajadas dentro del horario planificado al usuario' WHERE LanguageTag = 'trabajoefectivo'
UPDATE causes SET name = 'Trabajo efectivo' WHERE LanguageTag = 'trabajoefectivo'
UPDATE causes SET description = 'Ausencia por vacaciones anuales retribuidas. No es sustituible por compensación económica, será el pactado en Convenio Colectivo o contrato individual. Respetando este pacto los mínimos legales de 30 días naturales por año.' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET name = 'Vacaciones' WHERE LanguageTag = 'vacaciones'
UPDATE causes SET description = 'Ausencia sin motivo justificado que genera una alerta. El objetivo es que no haya ningún tiempo justificado con este motivo. Justificación interna de VisualTime, no se debe borrar ni modificar.' WHERE LanguageTag = 'vtnojustificado'
UPDATE causes SET name = 'VT. NO JUSTIFICADO' WHERE LanguageTag = 'vtnojustificado'
UPDATE concepts SET description = 'Este saldo restará todas las "horas a recuperar" y sumará todas las "horas recuperadas". Si el total de este saldo es negativo, el empleado debe horas a la empresa.  Si el total de este saldo es positivo, la empresa debe horas al trabajador. ' WHERE LanguageTag = 'horas'
UPDATE concepts SET name = 'Horas+/-' WHERE LanguageTag = 'horas'
UPDATE concepts SET description = 'Tiempo planificado, es el tiempo que por horarios tengo que realizar' WHERE LanguageTag = 'tiempoplanificadoteoria'
UPDATE concepts SET name = 'Tiempo planificado(teoría)' WHERE LanguageTag = 'tiempoplanificadoteoria'
UPDATE concepts SET description = 'Tiempo de ausencia ' WHERE LanguageTag = 'totalabsentismo'
UPDATE concepts SET name = 'Total absentismo' WHERE LanguageTag = 'totalabsentismo'
UPDATE concepts SET description = 'Horas complementarias para contratos a tiempo parcial.' WHERE LanguageTag = 'totalhorascomplementarias'
UPDATE concepts SET name = 'Total horas complementarias' WHERE LanguageTag = 'totalhorascomplementarias'
UPDATE concepts SET description = 'Horas extraordinarias. ' WHERE LanguageTag = 'totalhorasextras'
UPDATE concepts SET name = 'Total horas extras ' WHERE LanguageTag = 'totalhorasextras'
UPDATE concepts SET description = 'Todo el tiempo que se considera trabajo efectivo, sin contar excesos.' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET name = 'Trabajo efectivo' WHERE LanguageTag = 'trabajoefectivo'
UPDATE concepts SET description = 'Este saldo muestra las vacaciones pendientes de disfrutar.   Saldo inicial de vacaciones - vacaciones disfrutadas = vacaciones pendientes' WHERE LanguageTag = 'vacacionespendientes'
UPDATE concepts SET name = 'Vacaciones pendientes' WHERE LanguageTag = 'vacacionespendientes'
UPDATE groups SET name = 'Mi empresa' WHERE LanguageTag = 'miempresa'
UPDATE labagree SET name = 'Reglas generales' WHERE LanguageTag = 'reglasgenerales'
UPDATE requestsrules SET name = 'No pedir vacaciones si no hay saldo positivo' WHERE LanguageTag = 'nopedirvacacionessinohaysaldopositivo'
UPDATE shifts SET description = 'Festivos, no laborables.' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Festivo' WHERE LanguageTag = 'festivo'
UPDATE shifts SET name = 'Laborable' WHERE LanguageTag = 'laborable'
UPDATE shifts SET description = 'Este horario tiene 0 horas teóricas. Se planificará únicamente los días en los que el empleado disfrute de un día completo de descanso y, por lo tanto, no vaya a realizar ningún fichaje.' WHERE LanguageTag = 'nolaboral'
UPDATE shifts SET name = 'No laboral' WHERE LanguageTag = 'nolaboral'
UPDATE shifts SET description = 'Vacaciones en días laborables.' WHERE LanguageTag = 'vacaciones'
UPDATE shifts SET name = 'Vacaciones' WHERE LanguageTag = 'vacaciones'
UPDATE startupvalues SET name = 'Vacaciones' WHERE LanguageTag = 'vacaciones'
UPDATE startupvalues SET name = 'Vacaciones iniciales' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE startupvalues SET startvaluebase = '0' WHERE LanguageTag = 'vacacionesiniciales'
UPDATE sysroconcepttypes SET name = 'Horas' WHERE LanguageTag = 'horas'
UPDATE sysroconcepttypes SET name = 'Mixto (horas+ocurrencias)' WHERE LanguageTag = 'mixtohorasocurrencias'
UPDATE sysroconcepttypes SET name = 'Ocurrencias' WHERE LanguageTag = 'ocurrencias'
UPDATE sysroqueries SET description = 'Cerciorarnos de cuánto le queda al recalculo que realiza VisualTime y a cuántos empleados afecta' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET name = 'Cerciorarnos de cuánto le queda al recalculo que realiza VisualTime y a cuántos empleados afecta' WHERE LanguageTag = 'cerciorarnosdecuantolequedaalrecalculoquerealizavisualtimeyacuantosempleadosafecta'
UPDATE sysroqueries SET description = 'Comprobar el grupo al que pertenecen los empleados. Ruta corta y completa' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET name = 'Comprobar el grupo al que pertenecen los empleados. Ruta corta y completa' WHERE LanguageTag = 'comprobarelgrupoalquepertenecenlosempleadosrutacortaycompleta'
UPDATE sysroqueries SET description = 'Comprobar que hay alguna tarea que no ha podido ejecutarse con normalidad' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET name = 'Comprobar que hay alguna tarea que no ha podido ejecutarse con normalidad' WHERE LanguageTag = 'comprobarquehayalgunatareaquenohapodidoejecutarseconnormalidad'
UPDATE sysroqueries SET description = 'Comprobar si cliente tiene GPA' WHERE LanguageTag = 'comprobarsiclientetienegpa'
UPDATE sysroqueries SET name = 'Comprobar si cliente tiene GPA' WHERE LanguageTag = 'comprobarsiclientetienegpa'
UPDATE sysroqueries SET description = 'Comprobar si el recálculo tras los cambios realizados en VisualTime está funcionando correctamente' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET name = 'Comprobar si el recálculo tras los cambios realizados en VisualTime está funcionando correctamente' WHERE LanguageTag = 'comprobarsielrecalculotrasloscambiosrealizadosenvisualtimeestafuncionandocorrectamente'
UPDATE sysroqueries SET description = 'Mustra los permisos de los supervisores en V2' WHERE LanguageTag = 'permisosefectivos'
UPDATE sysroqueries SET name = 'Permisos efectivos' WHERE LanguageTag = 'permisosefectivos'
UPDATE sysroqueries SET description = 'Muestra los permisos sobre las funcionalidades de Empleados y Calendario de los supervisores en V2 sobre empleados' WHERE LanguageTag = 'permisosefectivossobrefuncionalidadesconcretas'
UPDATE sysroqueries SET name = 'Permisos efectivos sobre funcionalidades concretas' WHERE LanguageTag = 'permisosefectivossobrefuncionalidadesconcretas'
UPDATE sysroqueries SET description = 'Saber si el fichero de correlación está correctamente introducido en base de datos' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET name = 'Saber si el fichero de correlación está correctamente introducido en base de datos' WHERE LanguageTag = 'sabersielficherodecorrelacionestacorrectamenteintroducidoenbasededatos'
UPDATE sysroqueries SET description = 'Saber si hay algún informe planificado ejecutándose' WHERE LanguageTag = 'sabersihayalguninformeplanificadoejecutandose'
UPDATE sysroqueries SET name = 'Saber si hay algún informe planificado ejecutándose' WHERE LanguageTag = 'sabersihayalguninformeplanificadoejecutandose'
UPDATE sysroqueries SET description = 'Ver los fichajes que ha habido en una fecha en concreto (poder escoger fecha)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET name = 'Ver los fichajes que ha habido en una fecha en concreto (poder escoger fecha)' WHERE LanguageTag = 'verlosfichajesquehahabidoenunafechaenconcretopoderescogerfecha'
UPDATE sysroqueries SET description = 'Visualizar tareas pendientes colgadas de los terminales tras realizar broadcast' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroqueries SET name = 'Visualizar tareas pendientes colgadas de los terminales tras realizar broadcast' WHERE LanguageTag = 'visualizartareaspendientescolgadasdelosterminalestrasrealizarbroadcast'
UPDATE sysroreportgroups SET name = 'Informe de saldos' WHERE LanguageTag = 'informedesaldos'
UPDATE sysroreportgroups SET name = 'Informe de vacaciones pendientes' WHERE LanguageTag = 'informedevacacionespendientes'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Categoría profesional' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET listvalues = 'Auxiliares Administrativos~Ayudantes no Titulados~Ingenieros Técnicos, Peritos y Ayudantes Titulados~Ingenieros y Licenciados~Jefes Administrativos y de Taller~Oficiales Administrativos~Oficiales de primera y segunda~Oficiales de tercera y Especialistas~Peones~Subalternos~Trabajadores menores de 18 años' WHERE LanguageTag = 'categoriaprofesional'
UPDATE sysrouserfields SET fieldname = 'Código Postal' WHERE LanguageTag = 'codigopostal'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET fieldname = 'Complementos salariales anuales' WHERE LanguageTag = 'complementossalarialesanuales'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET fieldname = 'Correo electrónico' WHERE LanguageTag = 'correoelectronico'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET fieldname = 'Coste HR' WHERE LanguageTag = 'costehr'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET fieldname = 'Coste por hora' WHERE LanguageTag = 'costeporhora'
UPDATE sysrouserfields SET category = 'Personal' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET fieldname = 'Fecha de nacimiento' WHERE LanguageTag = 'fechadenacimiento'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET fieldname = 'Género' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET listvalues = 'Hombre~Mujer' WHERE LanguageTag = 'genero'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET fieldname = 'Grupo de cotización' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET listvalues = '1~11~19~2~3~4~5~6~7~8~9' WHERE LanguageTag = 'grupodecotizacion'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Id importación' WHERE LanguageTag = 'idimportacion'
UPDATE sysrouserfields SET fieldname = 'Motivo de baja' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET listvalues = 'Baja voluntaria~Defunción~Despido~Finalización del contrato temporal~Incapacidad~Invalidez~Jubilación~Por causas convenidas en el contrato' WHERE LanguageTag = 'motivodebaja'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET fieldname = 'Móvil' WHERE LanguageTag = 'movil'
UPDATE sysrouserfields SET category = 'Personal' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET fieldname = 'Nacionalidad' WHERE LanguageTag = 'nacionalidad'
UPDATE sysrouserfields SET category = 'Personal' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET fieldname = 'NIF' WHERE LanguageTag = 'nif'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET fieldname = 'Número de emergencia' WHERE LanguageTag = 'numerodeemergencia'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET fieldname = 'Observaciones' WHERE LanguageTag = 'observaciones'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET fieldname = 'Percepciones extrasalariales' WHERE LanguageTag = 'percepcionesextrasalariales'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Percepciones por extraordinarias y complementarias' WHERE LanguageTag = 'percepcionesporextraordinariasycomplementarias'
UPDATE sysrouserfields SET fieldname = 'Población' WHERE LanguageTag = 'poblacion'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Precio por hora' WHERE LanguageTag = 'precioporhora'
UPDATE sysrouserfields SET fieldname = 'Provincia' WHERE LanguageTag = 'provincia'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET fieldname = 'Puesto' WHERE LanguageTag = 'puesto'
UPDATE sysrouserfields SET category = 'VisualTime' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET fieldname = 'Punto de reunión' WHERE LanguageTag = 'puntodereunion'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET fieldname = 'Salario base anual' WHERE LanguageTag = 'salariobaseanual'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Salario total anual' WHERE LanguageTag = 'salariototalanual'
UPDATE sysrouserfields SET fieldname = 'Teléfono' WHERE LanguageTag = 'telefono'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET fieldname = 'Tipo de contrato' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET listvalues = 'En prácticas~Indefinido~Temporal' WHERE LanguageTag = 'tipodecontrato'
UPDATE sysrouserfields SET category = 'Laboral' WHERE LanguageTag = 'valorinicialdevacaciones'
UPDATE sysrouserfields SET fieldname = 'Valor inicial de vacaciones ' WHERE LanguageTag = 'valorinicialdevacaciones'
UPDATE timezones SET name = 'Horas con remuneración especial' WHERE LanguageTag = 'horasconremuneracionespecial'
UPDATE timezones SET name = 'Horas nocturnas' WHERE LanguageTag = 'horasnocturnas'
UPDATE timezones SET name = 'Horas normales' WHERE LanguageTag = 'horasnormales'
UPDATE zones SET name = 'Ausentes' WHERE LanguageTag = 'ausentes'
UPDATE zones SET name = 'Presentes' WHERE LanguageTag = 'presentes'
GO