'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SecurityOptions

    '''<summary>
    '''hdnValueGridName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnValueGridName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''msgHasChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgHasChanges As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''msgHasErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgHasErrors As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''imgSecurityOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSecurityOptions As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rowTabButtons3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTabButtons3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TABBUTTON_PasswordOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TABBUTTON_PasswordOptions As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblPasswordOptionsTabButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPasswordOptionsTabButton As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TABBUTTON_RestrictionsOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TABBUTTON_RestrictionsOptions As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblRestrictionsOptionsTabButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRestrictionsOptionsTabButton As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upBody As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Img1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblSaveChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveChanges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUndoChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndoChanges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbPasswordOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPasswordOptions As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblPasswordConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPasswordConfiguration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPasswordConfigurationDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPasswordConfigurationDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''groupPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupPassword As Global.VTLive40.base_WebUserControls_roGroupBox

    '''<summary>
    '''lblHistoricPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHistoricPassword As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtHistoricPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHistoricPassword As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblHistoricPasswor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHistoricPasswor2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHistoricPasswordDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHistoricPasswordDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOutdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOutdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPasswordOutdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPasswordOutdated As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblOutdateDef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOutdateDef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPasswordOutDateDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPasswordOutDateDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBlockAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlockAccount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBlockAccountDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlockAccountDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''groupBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupBlock As Global.VTLive40.base_WebUserControls_roGroupBox

    '''<summary>
    '''lblBlockTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlockTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlock1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBlock1Attempts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBlock1Attempts As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblBlock1Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlock1Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBlock2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlock2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBlock2Attempts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBlock2Attempts As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblBlock2Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlock2Desc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbRestrictionsOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbRestrictionsOptions As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblGlobalAccessRestriction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGlobalAccessRestriction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGlobalAccesRestrictionDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGlobalAccesRestrictionDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''groupAccessRestrictions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupAccessRestrictions As Global.VTLive40.base_WebUserControls_roGroupBox

    '''<summary>
    '''ckRequiereKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckRequiereKey As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblRequiereKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequiereKey As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequiereKeyDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequiereKeyDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbRequiereKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbRequiereKey As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblSaveIp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveIp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblElapsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblElapsed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSaveKeyTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSaveKeyTime As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDays As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTimes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAccessDiferentIps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessDiferentIps As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblDifferentIps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDifferentIps As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVersion As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblAppCheckVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppCheckVersion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAppCheckVersionDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppCheckVersionDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChkRestrictedIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkRestrictedIP As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblOnlyIps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnlyIps As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnlyIpsDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnlyIpsDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAddIPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddIPs As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblAddIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddIP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAllowedIPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowedIPs As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''gridAllowedIPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridAllowedIPs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''frmIPs1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmIPs1 As Global.VTLive40.Security_WebUserForms_frmIPs

    '''<summary>
    '''lblAccessBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccessBlock As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAccessBlockDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccessBlockDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''groupAccessBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupAccessBlock As Global.VTLive40.base_WebUserControls_roGroupBox

    '''<summary>
    '''ckBlockPortal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckBlockPortal As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''lblBlockPortal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlockPortal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ckBlockDesktop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckBlockDesktop As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''lblBlockDesktop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlockDesktop As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRemoteAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemoteAccess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRemoteAccessDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemoteAccessDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''groupRemote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupRemote As Global.VTLive40.base_WebUserControls_roGroupBox

    '''<summary>
    '''ckRemoteAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckRemoteAccess As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''lblRemoteAccessSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemoteAccessSection As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Img2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img2 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblSaveChangesBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveChangesBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUndoChangesBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndoChangesBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdnChanged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnChanged As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnIsPostBack_PageBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIsPostBack_PageBase As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SecurityOptions_TabVisibleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecurityOptions_TabVisibleName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''MessageFrame1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageFrame1 As Global.VTLive40.Base_WebUserControls_MessageModalV2
End Class
