'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SupervisorsContent

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''hdnValueGridName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnValueGridName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''msgHasChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgHasChanges As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''msgHasErrors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgHasErrors As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnStrEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStrEmpName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnStrCategoryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStrCategoryName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnStrLevelName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStrLevelName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnStrNextLevelName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStrNextLevelName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnGroupsConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnGroupsConfig As Global.DevExpress.Web.ASPxHiddenField

    '''<summary>
    '''ASPxCallbackPanelContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallbackPanelContenido As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''PanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent1 As Global.DevExpress.Web.PanelContent

    '''<summary>
    '''hdnTreeGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTreeGroups As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Img1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblSaveChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveChanges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUndoChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndoChanges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGeneral As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDefTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDefTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''trSecurityFunction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSecurityFunction As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblSecurityFunction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecurityFunction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbSecurityFunctions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSecurityFunctions As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''trLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLanguage As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLanguage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLanguage As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''trDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDate As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartDate As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''lblExpirationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpirationDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFinishDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFinishDate As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''trState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trState As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkState As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''trMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trMail As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmailAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailAddress As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblUsersSecurityTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsersSecurityTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUsersSecurityDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsersSecurityDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUserExceptionDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserExceptionDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGroupAndUsersTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroupAndUsersTree As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGroupTreeDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroupTreeDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''objContainerTreeV3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objContainerTreeV3 As Global.VTLive40.Base_WebUserControls_roTreeV3b

    '''<summary>
    '''lblExceptionsHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExceptionsHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExceptionsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExceptionsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExceptionsDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExceptionsDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAddException control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddException As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblAddException control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddException As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divExceptionsSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divExceptionsSelector As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRequestCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestCategories As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequestCategoriesDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestCategoriesDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''requestCategoryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requestCategoryTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''A1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''addNewRequestCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addNewRequestCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divRequestCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRequestCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''frmNewUserException1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmNewUserException1 As Global.VTLive40.frmNewUserException

    '''<summary>
    '''frmNewRequestCategory1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmNewRequestCategory1 As Global.VTLive40.frmNewRequestCategory

    '''<summary>
    '''divActiveNotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divActiveNotifications As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNotificationsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotificationsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActiveNotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveNotifications As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''activeNotificationsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents activeNotificationsTable As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divAllowedApplications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAllowedApplications As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAllowedApplications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowedApplications As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cnAllowedApplications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnAllowedApplications As Global.VTLive40.Base_WebUserControls_AllowedApplications

    '''<summary>
    '''divRestricciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRestricciones As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRestrictions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRestrictions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGlobalAccesRestrictionDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGlobalAccesRestrictionDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''groupAccessRestrictions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupAccessRestrictions As Global.VTLive40.base_WebUserControls_roGroupBox

    '''<summary>
    '''ckRequiereKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckRequiereKey As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblRequiereKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequiereKey As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequiereKeyDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequiereKeyDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbRequiereKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbRequiereKey As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblSaveIp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveIp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblElapsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblElapsed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSaveKeyTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSaveKeyTime As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDays As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTimes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAccessDiferentIps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessDiferentIps As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblDifferentIps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDifferentIps As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVersion As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblAppCheckVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppCheckVersion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAppCheckVersionDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppCheckVersionDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChkRestrictedIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkRestrictedIP As Global.VTLive40.WebUserControls_roOptionPanelClient

    '''<summary>
    '''lblOnlyIps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnlyIps As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnlyIpsDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnlyIpsDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tableAddIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableAddIP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnAddIPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddIPs As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblAddIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddIP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAllowedIPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowedIPs As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''gridAllowedIPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridAllowedIPs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''frmIPs1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmIPs1 As Global.VTLive40.Security_WebUserForms_frmIPs

    '''<summary>
    '''lblLockCalendarDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLockCalendarDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLockCalendarDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLockCalendarDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RoGroupBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoGroupBox1 As Global.VTLive40.base_WebUserControls_roGroupBox

    '''<summary>
    '''ckCalendarLock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckCalendarLock As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''lblLockCalendarCK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLockCalendarCK As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divIdentifyMethods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divIdentifyMethods As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblIdentifyMethodsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdentifyMethodsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIdentifyMethodsInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdentifyMethodsInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cnIdentifyMethods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnIdentifyMethods As Global.VTLive40.Base_WebUserControls_IdentifyMethods

    '''<summary>
    '''divConsents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConsents As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Img2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img2 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblSaveChangesBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveChangesBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUndoChangesBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndoChangesBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CaptchaObjectPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaptchaObjectPopup As Global.DevExpress.Web.ASPxPopupControl
End Class
